diff --git a/Makefile b/Makefile
index 86ba3cd..a2aedc0 100644
--- a/Makefile
+++ b/Makefile
@@ -6,7 +6,7 @@ HTSDIR=htslib-1.2.1
 include $(HTSDIR)/htslib.mk
 HTSLIB = $(HTSDIR)/libhts.a
 IFLAGS = -I$(HTSDIR)  -I./
-LFLAGS = -lz -lm
+LFLAGS = -L${PREFIX}/lib -lz -lm
 CXX=g++
 
 default: CFLAGS = -std=c++11 -O3 -DNDEBUG -fopenmp
