diff --git a/Makefile b/Makefile
index 86ba3cd..08a432e 100644
--- a/Makefile
+++ b/Makefile
@@ -9,7 +9,7 @@ IFLAGS = -I$(HTSDIR)  -I./
 LFLAGS = -lz -lm
 CXX=g++
 
-default: CFLAGS = -std=c++11 -O3 -DNDEBUG -fopenmp
+default: CFLAGS = -std=c++11 -O3 -DNDEBUG -fopenmp -I$(PREFIX)/include -L$(PREFIX)/lib
 default: all
 
 debug: CFLAGS = -std=c++11 -g -O1 -fopenmp
