{% set name = "neffy" %}
{% set version = "0.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/neffy/neffy-{{ version }}.tar.gz
  sha256: 49c256d1ebf441597a299777cfb8eb4fa9a9415054d72657e38b16f6383c5fd1
  patches:
    - 0001-setup.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - neffy

about:
  home: "https://github.com/Maryam-Haghani/NEFFy"
  license: "GPL-3.0-only"  # GNU General Public License v3
  license_family: GPL3
  license_file: "LICENSE.txt"
  summary: "A Python interface of NEFFy C++ tool: NEFF Calculator and MSA File Converter"
  doc_url: "https://maryam-haghani.github.io/NEFFy"
  dev_url: "https://github.com/Maryam-Haghani/NEFFy"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - Maryam-Haghani
