--- maf2synteny/Makefile	2020-10-25 19:12:17.057477058 +0700
+++ Makefile	2020-10-25 16:29:02.000000000 +0700
@@ -1,6 +1,6 @@
 SRC := src
 export BIN_DIR = $(shell pwd)
-export CXXFLAGS := -std=c++0x
+export CXXFLAGS := -std=c++0x -fPIE
 
 .PHONY: clean all
 
