diff --git a/Makefile b/Makefile
index f46b30d..e025d8d 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 MAKEFLAGS += --no-print-directory
-CC = g++
+CC ?= $(CXX)
 ifdef debug
 CFLAGS=         -O0 -g -fomit-frame-pointer -DDEBUG
 else
@@ -15,7 +15,7 @@ LIBS=       -pthread -lz -lm
 EXTRA_FLAGS= 
 
 BIT_ERR = 0
-ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64))
+ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64 aarch64 arm64))
 BIT_ERR = 1
 endif
 
diff --git a/fusion/Makefile b/fusion/Makefile
index 6b1159a..a625198 100755
--- a/fusion/Makefile
+++ b/fusion/Makefile
@@ -6,10 +6,10 @@ bindir = $(exec_prefix)/bin
 libdir = 
 mandir = 
 
-CC = gcc
-CCOPT = -O3 -fprefetch-loop-arrays -funroll-loops -fomit-frame-pointer -w 
-LIBS = -lm -lpthread
-INCDIRS = -Iinc/
+CC ?= $(CC)
+CCOPT = -O3 -fprefetch-loop-arrays -funroll-loops -fomit-frame-pointer -w -fcommon -Wno-implicit-function-declaration
+LIBS = -lm -pthread
+INCDIRS = -Iinc/ -I../sparsePregraph/inc/ -I../standardPregraph/inc/
 CFLAGS = ${CCOPT} ${INCDIRS}
 
 all: SOAPdenovo-fusion
diff --git a/sparsePregraph/Makefile b/sparsePregraph/Makefile
index e3551ff..9d94e45 100644
--- a/sparsePregraph/Makefile
+++ b/sparsePregraph/Makefile
@@ -1,4 +1,4 @@
-CC=            g++
+CC ?=            $(CXX)
 ifdef debug
 CFLAGS=         -O0 -g -fomit-frame-pointer -DDEBUG
 else
@@ -28,7 +28,7 @@ endif
 
 
 BIT_ERR = 0
-ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64))
+ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64 aarch64 arm64))
 BIT_ERR = 1
 endif
 
diff --git a/sparsePregraph/inc/libbam.a b/sparsePregraph/inc/libbam.a
index d86ebe0..aa9373d 100644
Binary files a/sparsePregraph/inc/libbam.a and b/sparsePregraph/inc/libbam.a differ
diff --git a/standardPregraph/Makefile b/standardPregraph/Makefile
index 1f20e7c..8a27aba 100644
--- a/standardPregraph/Makefile
+++ b/standardPregraph/Makefile
@@ -5,13 +5,13 @@
 #
 ###################################
 
-CC=             gcc
+CC ?=             $(CC)
 GCCVERSIONMAJOR := $(shell expr `$(CC) -dumpversion | cut -f1 -d.` \>= 4)
 GCCVERSIONMINOR := $(shell expr `$(CC) -dumpversion | cut -f2 -d.` \>= 4)
 ifdef debug
-CFLAGS=         -O0 -g -fomit-frame-pointer -DDEBUG#-msse4.2
+CFLAGS=         -O0 -g -fomit-frame-pointer -DDEBUG  #-msse4.2
 else
-CFLAGS=         -O3 -fomit-frame-pointer -w #-msse4.2
+CFLAGS=         -O3 -fomit-frame-pointer -w -fcommon -Wno-implicit-function-declaration  #-msse4.2
 endif
 DFLAGS=         
 OBJS=		arc.o attachPEinfo.o bubble.o check.o compactEdge.o \
@@ -32,7 +32,7 @@ LIBS=       -pthread -lz -lm
 EXTRA_FLAGS=
 
 BIT_ERR = 0
-ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64))
+ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64 aarch64 arm64))
 BIT_ERR = 1
 endif
 
