diff --git a/Makefile b/Makefile
index f46b30d..aaf9955 100644
--- a/Makefile
+++ b/Makefile
@@ -15,7 +15,7 @@ LIBS=       -pthread -lz -lm
 EXTRA_FLAGS= 
 
 BIT_ERR = 0
-ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64))
+ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64 aarch64 arm64))
 BIT_ERR = 1
 endif
 
diff --git a/fusion/Makefile b/fusion/Makefile
index 6b1159a..3ee74c9 100755
--- a/fusion/Makefile
+++ b/fusion/Makefile
@@ -7,9 +7,9 @@ libdir =
 mandir = 
 
 CC = gcc
-CCOPT = -O3 -fprefetch-loop-arrays -funroll-loops -fomit-frame-pointer -w 
-LIBS = -lm -lpthread
-INCDIRS = -Iinc/
+CCOPT = -O3 -fprefetch-loop-arrays -funroll-loops -fomit-frame-pointer -w -fcommon
+LIBS = -lm -pthread
+INCDIRS = -Iinc/ -I../sparsePregraph/inc/ -I../standardPregraph/inc/
 CFLAGS = ${CCOPT} ${INCDIRS}
 
 all: SOAPdenovo-fusion
diff --git a/sparsePregraph/Makefile b/sparsePregraph/Makefile
index e3551ff..11067e7 100644
--- a/sparsePregraph/Makefile
+++ b/sparsePregraph/Makefile
@@ -28,7 +28,7 @@ endif
 
 
 BIT_ERR = 0
-ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64))
+ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64 aarch64 arm64))
 BIT_ERR = 1
 endif
 
diff --git a/sparsePregraph/inc/libbam.a b/sparsePregraph/inc/libbam.a
index d86ebe0..aa9373d 100644
Binary files a/sparsePregraph/inc/libbam.a and b/sparsePregraph/inc/libbam.a differ
diff --git a/standardPregraph/Makefile b/standardPregraph/Makefile
index 1f20e7c..3c44f88 100644
--- a/standardPregraph/Makefile
+++ b/standardPregraph/Makefile
@@ -9,9 +9,9 @@ CC=             gcc
 GCCVERSIONMAJOR := $(shell expr `$(CC) -dumpversion | cut -f1 -d.` \>= 4)
 GCCVERSIONMINOR := $(shell expr `$(CC) -dumpversion | cut -f2 -d.` \>= 4)
 ifdef debug
-CFLAGS=         -O0 -g -fomit-frame-pointer -DDEBUG#-msse4.2
+CFLAGS=         -O0 -g -fomit-frame-pointer -DDEBUG  #-msse4.2
 else
-CFLAGS=         -O3 -fomit-frame-pointer -w #-msse4.2
+CFLAGS=         -O3 -fomit-frame-pointer -w -fcommon  #-msse4.2
 endif
 DFLAGS=         
 OBJS=		arc.o attachPEinfo.o bubble.o check.o compactEdge.o \
@@ -32,7 +32,7 @@ LIBS=       -pthread -lz -lm
 EXTRA_FLAGS=
 
 BIT_ERR = 0
-ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64))
+ifeq (,$(findstring $(shell uname -m), x86_64 ppc64 ia64 aarch64 arm64))
 BIT_ERR = 1
 endif
 
diff --git a/standardPregraph/inc/libbam.a b/standardPregraph/inc/libbam.a
index d86ebe0..aa9373d 100644
Binary files a/standardPregraph/inc/libbam.a and b/standardPregraph/inc/libbam.a differ
