{% set name = "itsxrust" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ayobi/ITSxRust/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5246aa234741d61d9e3b96e0682de47852c3dc4cddb3bc3319a746b277ed91b7

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host: []
  run:
    - hmmer

test:
  commands:
    - itsxrust --help
    - itsxrust extract --help

about:
  summary: "ITSxRust is a tool for extracting ITS regions from DNA sequences."
  home: https://github.com/ayobi/ITSxRust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ayobi

