diff --git a/Makefile b/Makefile
index 03b388e..946a94d 100644
--- a/Makefile
+++ b/Makefile
@@ -1,2 +1,2 @@
 Genrich: Genrich.c Genrich.h
-	gcc -g -Wall -std=gnu99 -O2 -o Genrich Genrich.c -lz -lm
+	$(CC) -g -Wall -std=gnu99 $(LDFLAGS) $(CFLAGS) -O2 -o Genrich Genrich.c -lz -lm
