Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: bgzf.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: bgzip.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: config.h
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: config.h.in
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: config.mk.in
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: configure.ac
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: cram
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: faidx.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: hfile.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: hfile_internal.h
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: hfile_irods.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: hfile_net.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: hts.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: htsfile.1
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: htsfile.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: hts_internal.h
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: htslib
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: htslib.mk
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: htslib.pc.in
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: htslib_vars.mk
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: kfunc.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: knetfile.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: kstring.c
diff -u /home/ryan/Documents/SourceCode/MethylDackel/htslib/Makefile new/Makefile
--- /home/ryan/Documents/SourceCode/MethylDackel/htslib/Makefile	2017-01-16 14:32:21.094711506 +0100
+++ new/Makefile	2017-01-27 11:59:02.448035849 +0100
@@ -30,7 +30,7 @@
 # TODO: probably update cram code to make it compile cleanly with -Wc++-compat
 CFLAGS   = -g -Wall -O2
 EXTRA_CFLAGS_PIC = -fpic
-LDFLAGS  =
+LDFLAGS  ?=
 LDLIBS   =
 
 # For now these don't work too well as samtools also needs to know to
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: Makefile.new
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: md5.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: regidx.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: sam.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: synced_bcf_reader.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: tabix.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: tbx.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: test
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: vcf.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: vcf_sweep.c
Only in /home/ryan/Documents/SourceCode/MethylDackel/htslib/: vcfutils.c
