diff -u htslib/Makefile htslib/Makefile
--- htslib/Makefile	2017-01-16 14:32:21.094711506 +0100
+++ htslib/Makefile	2017-01-16 14:32:21.094711506 +0100
@@ -30,7 +30,7 @@
 # TODO: probably update cram code to make it compile cleanly with -Wc++-compat
 CFLAGS   = -g -Wall -O2
 EXTRA_CFLAGS_PIC = -fpic
-LDFLAGS  =
+LDFLAGS  ?=
 LDLIBS   =
 
 # For now these don't work too well as samtools also needs to know to
