{% set name = "quarTeT" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aaranyue/quarTeT/archive/4fdd3e0ea2a4aae315ace99a67c1f54128759012.tar.gz
  sha256: 63e9464fe2eb474d93d008654efda55e02aff1bb31f83fcd188f81383948a193

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - r-rideogram
    - r-ggplot2
    - gnuplot
    - unimap
    - minimap2
    - mummer4
    - trf
    - cd-hit
    - blast
    - tidk
    - hifiasm

test:
  imports:
    - quarTeT
  commands:
    - quartet.py -h 2&>1 | grep "version"

about:
  home: "https://github.com/aaranyue/quarTeT"
  license: MIT
  license_family: MIT
  dev_url: "https://github.com/aaranyue/quarTeT"
  doc_url: "https://github.com/aaranyue/quarTeT/blob/main/README.md"

extra:
  identifiers:
    - doi:10.1093/hr/uhad127
    - biotools:quartet
