#!/usr/bin/env bash
# Build file is copied from VarScan
# https://github.com/bioconda/bioconda-recipes/blob/master/recipes/varscan/build.sh
# This file was automatically generated by the sbt-bioconda plugin.

outdir=$PREFIX/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM
mkdir -p $outdir
mkdir -p $PREFIX/bin
cp SeattleSeqKit-assembly-0.2.jar $outdir/SeattleSeqKit-assembly-0.2.jar
cp $RECIPE_DIR/biopet-seattleseqkit.py $outdir/biopet-seattleseqkit
ln -s $outdir/biopet-seattleseqkit $PREFIX/bin

