#!/bin/bash
mv DESCRIPTION DESCRIPTION.old
grep -v '^Priority: ' DESCRIPTION.old > DESCRIPTION
mkdir -p ~/.R
echo -e "CC=$CC
FC=$FC
CXX=$CXX -D_LIBCPP_DISABLE_AVAILABILITY
CXX98=$CXX -D_LIBCPP_DISABLE_AVAILABILITY
CXX11=$CXX -D_LIBCPP_DISABLE_AVAILABILITY
CXX14=$CXX -D_LIBCPP_DISABLE_AVAILABILITY
" > ~/.R/Makevars
$R CMD INSTALL --build .