diff --git a/Makefile b/Makefile
index e2ed080..c1fdd13 100644
--- a/Makefile
+++ b/Makefile
@@ -5,11 +5,11 @@ SEARCHDIRS := -I. -I${GCLDIR}
 SYSTYPE :=     $(shell uname)
 
 CXX   := $(if $(CXX),$(CXX),g++)
-LINKER  := $(if $(LINKER),$(LINKER),g++)
+LINKER  := $(CXX)
 
 LDFLAGS := $(if $(LDFLAGS),$(LDFLAGS),-g)
 
-BASEFLAGS  := -Wall -Wextra -std=c++11 ${SEARCHDIRS} -D_FILE_OFFSET_BITS=64 \
+BASEFLAGS  := -Wall -Wextra -std=c++14 ${SEARCHDIRS} -D_FILE_OFFSET_BITS=64 \
  -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing \
  -fno-exceptions -fno-rtti
 
