diff -ruN gffread-0.12.7/Makefile gffread-0.12.7/Makefile
--- gffread-0.12.7/Makefile	2021-07-23 16:31:39.000000000 +0200
+++ gffread-0.12.7/Makefile	2021-09-24 14:24:52.376666651 +0200
@@ -5,7 +5,7 @@
 SYSTYPE :=     $(shell uname)
 
 CXX   := $(if $(CXX),$(CXX),g++)
-LINKER  := $(if $(LINKER),$(LINKER),g++)
+LINKER  := $(CXX)
 
 LDFLAGS := $(if $(LDFLAGS),$(LDFLAGS),-g)
 
