{% set name = "RepeatAfterMe" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Dfam-consortium/RepeatAfterMe/archive/refs/tags/RepeatAfterMe_V{{ version }}.tar.gz
  sha256: 515cb962924ca1f0b5bbd65cd8967136abf6195d00666b0995349f3bf0983679
  patches:
    - 0001-Makefile.patch
    - 0002-dnautil-macOS.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('repeatafterme', max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - perl
    - libgomp  # [linux]
    - llvm-openmp  # [osx]

test:
  commands:
    - RAMExtend 2>&1 | grep 'RAMExtend Version'

about:
  home: "https://github.com/Dfam-consortium/RepeatAfterMe"
  license: "CC0"
  license_file: LICENSE
  summary: "A package for the extension of repetitive DNA sequences."
  dev_url: "https://github.com/Dfam-consortium/RepeatAfterMe"
  doc_url: "https://github.com/Dfam-consortium/RepeatAfterMe/blob/RepeatAfterMe_V{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
