#!/usr/bin/env bash

# abyss-pe is written in make and uses additional arguments in its #! line,
# so simply using /usr/bin/env make doesn't work.  Use a wrapper instead.
make -rRf `which abyss-pe-actual` "$@"
