{% set name = "nextclade" %}
{% set version = "3.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/nextstrain/nextclade/releases/download/{{ version }}/{{ name }}-x86_64-unknown-linux-gnu   # [linux64]
    sha256: 9d3bae84ec731e533197378013a49a78d85b2653895726c4e2837a897e157413                                           # [linux64]
  - url: https://github.com/nextstrain/nextclade/releases/download/{{ version }}/{{ name }}-aarch64-unknown-linux-gnu  # [aarch64]
    sha256: c28d3818b45126a73dce47a4652ceda61f96e0d543523998e95415ab3196d8ab                                           # [aarch64]
  - url: https://github.com/nextstrain/nextclade/releases/download/{{ version }}/{{ name }}-x86_64-apple-darwin        # [osx and x86_64]
    sha256: cb838e0c8166a076cd6a71bd9a8db008bea28229b0414e359e66cc140d94732c                                           # [osx and x86_64]
  - url: https://github.com/nextstrain/nextclade/releases/download/{{ version }}/{{ name }}-aarch64-apple-darwin       # [osx and arm64]
    sha256: c0216176beb843eca90f2ceaba14a5705762fc553f671a56348179582676bb2b                                           # [osx and arm64]

build:
  number: 0
  binary_relocation: False
  run_exports:
  - {{ pin_compatible(name, max_pin='x') }}

requirements:
# Disable test for aarch64, as nextclade requires glibc 2.18 not available on aarch64

test:
  commands:
    - nextclade --help  # [not aarch64]

about:
  home: "https://github.com/nextstrain/nextclade"
  license: MIT
  license_family: MIT
  summary: "Viral genome alignment, mutation calling, clade assignment, quality checks and phylogenetic placement."
  doc_url: "https://docs.nextstrain.org/projects/nextclade/en/stable"
  dev_url: "https://github.com/nextstrain/nextclade"

extra:
  identifiers:
    - doi:10.21105/joss.03773
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - pvanheus
    - corneliusroemer
    - ivan-aksamentov
  skip-lints:
    # repackaged binary
    - should_be_noarch_generic
