{% set name = "nextclade" %}
{% set version = "3.21.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/nextstrain/nextclade/releases/download/{{ version }}/{{ name }}-x86_64-unknown-linux-gnu   # [linux64]
    sha256: fc523e999d2ad11917f844a9932eda921b2712b9324650c1984d7598d5f5ee77                                           # [linux64]
  - url: https://github.com/nextstrain/nextclade/releases/download/{{ version }}/{{ name }}-aarch64-unknown-linux-gnu  # [aarch64]
    sha256: 721b42dc8872fc4350b0350296f9de3a239fc2c8e4f5948abcc02323f26479d0                                           # [aarch64]
  - url: https://github.com/nextstrain/nextclade/releases/download/{{ version }}/{{ name }}-x86_64-apple-darwin        # [osx and x86_64]
    sha256: 52a697d8e5d8656fa1ef08dd4fa76b3e1de16c2413dfe01de066392931ce63f1                                           # [osx and x86_64]
  - url: https://github.com/nextstrain/nextclade/releases/download/{{ version }}/{{ name }}-aarch64-apple-darwin       # [osx and arm64]
    sha256: 7b54d0aad006da729151871e4cde9836707688a02386bb36cd0c482a32d22545                                           # [osx and arm64]

build:
  number: 0
  binary_relocation: False
  run_exports:
    - {{ pin_compatible(name, max_pin="x") }}

requirements:
# Disable test for aarch64, as nextclade requires glibc 2.18 not available on aarch64

test:
  commands:
    - nextclade --help  # [not aarch64]

about:
  home: "https://github.com/nextstrain/nextclade"
  license: MIT
  license_family: MIT
  summary: "Viral genome alignment, mutation calling, clade assignment, quality checks and phylogenetic placement."
  doc_url: "https://docs.nextstrain.org/projects/nextclade/en/stable"
  dev_url: "https://github.com/nextstrain/nextclade"

extra:
  identifiers:
    - doi:10.21105/joss.03773
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - pvanheus
    - corneliusroemer
    - ivan-aksamentov
  skip-lints:
    # repackaged binary
    - should_be_noarch_generic
