{% set version = "0.8.0" %}
{% set name = "coverm" %}
{% set sha256 = "8e8718ce49379dd5bfb5a47ea60f1f68ae1db68e149df797ad68fab794918af3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/wwood/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - clangdev  # one of the rust submodules explicitly requires clang. As it's statically compiled that will hopefully work
    - pkg-config
    - make
    - cmake
  host:
    - zlib
    - gsl
    - openblas
  run:
    - gsl
    - openblas
    - coreutils
    - starcode
    - bwa >=0.7.17
    - samtools >=1.9
    - minimap2 >=2.28
    - skani >=0.2.2
    - python-dashing
    - fastani >=1.31
    - strobealign >=0.11.0

test:
  commands:
    - {{ name }} --version | grep '{{ version }}'

about:
  home: "https://github.com/wwood/CoverM"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file:
    - "LICENCE.txt"
    - "THIRDPARTY.yml"
  summary: "CoverM aims to be a configurable, easy to use and fast DNA read coverage and relative abundance calculator focused on metagenomics applications."
  description: "CoverM aims to be a configurable, easy to use and fast DNA read coverage and relative abundance calculator focused on metagenomics application."
  dev_url: "https://github.com/wwood/CoverM"
  doc_url: "https://github.com/wwood/CoverM/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1093/bioinformatics/btaf147
    - biotools:coverm
    - usegalaxy-eu:coverm_contig
    - usegalaxy-eu:coverm_genome
