{% set name = "TIR-Learner" %}
{% set version = "4.07" %}
{% set sha256 = "34f22246e71238a06ac65000f5b12d4f9bed752f5f40c76bb81b6a910816d32d" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/KGerhardt/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name | lower, max_pin='x') }}

requirements:
  run:
    - python >=3.9,<3.13
    - numpy
    - pyfastx
    - pywfa
    - keras
    - pytorch
    - genometools-genometools
    - grfmite-rs >=0.3.0
    - blast
    - pigz

test:
  commands:
    - TIR-Learner --help
    - tirlearner4 --help

about:
  home: https://github.com/KGerhardt/{{ name }}
  summary: "Accelerated tool for identifying TIR transposable elements"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  dev_url: https://github.com/KGerhardt/{{ name }}
  doc_url: https://github.com/KGerhardt/{{ name }}/blob/main/README.md
