{% set name = "isopedia" %}
{% set version = "1.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zhengxinchang/isopedia/releases/download/{{ version }}/isopedia-{{ version }}.linux.tar.gz
  sha256: d1b8cf0ee2edfdf0248a877b4d085b44546b87a264bf7b88ecaf3ac3c938700c  

build:
  number: 0
  skip: True  # [osx]
  binary_relocation: False  # 告诉 conda 这是预编译二进制
  run_exports:
    - {{ pin_subpackage('isopedia', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}  # 添加一个编译器声明以避免 noarch 误判
  host:
    - python >=3.6
    - zlib
    - bzip2
    - xz
    - libdeflate
    - curl
    - openssl
  run:
    - python >=3.6
    - zlib
    - bzip2
    - xz
    - libdeflate
    - curl
    - openssl

test:
  commands:
    - {{ name }} --help
    - {{ name }} --version

about:
  home: https://github.com/zhengxinchang/{{ name }}
  license: MIT  
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Simultaneous exploration of thousands of long-read transcriptomes by read-level indexing'
  description: |
    Simultaneous exploration of thousands of long-read transcriptomes by read-level indexing
  doc_url: https://github.com/zhengxinchang/{{ name }}
  dev_url: https://github.com/zhengxinchang/{{ name }}

extra:
  recipe-maintainers:
    - zhengxinchang  
  skip-lints:
    - should_be_noarch_generic  # 这是预编译二进制，不是 noarch
