{% set name = "isopedia" %}
{% set version = "1.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zhengxinchang/isopedia/releases/download/{{ version }}/isopedia-{{ version }}.linux.tar.gz
  sha256: a068974fbfe1c9b4f22ab44cf76c0bc9b696c9cc59d9d087109a9a41b35dbe1b  

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage('isopedia', max_pin="x") }}

requirements:
  host:
    - zlib
    - bzip2
    - xz
    - libdeflate
    - curl
    - openssl
  run:
    - zlib
    - bzip2
    - xz
    - libdeflate
    - curl
    - openssl

test:
  commands:
    - {{ name }} --help
    - {{ name }} --version

about:
  home: https://github.com/zhengxinchang/{{ name }}
  license: MIT  
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Simultaneous exploration of thousands of long-read transcriptomes by read-level indexing'
  description: |
    Simultaneous exploration of thousands of long-read transcriptomes by read-level indexing
  doc_url: https://github.com/zhengxinchang/{{ name }}
  dev_url: https://github.com/zhengxinchang/{{ name }}

extra:
  recipe-maintainers:
    - zhengxinchang  
