--- a/src/Makefile
+++ b/src/Makefile
@@ -55,7 +55,7 @@
 #
 #---------
 
-definedForAll = -Wall -Wextra -Werror -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
+definedForAll = -Wall -Wextra -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
 flagsFor32    = -Dmax_sequence_index=32 -Dmax_malloc_index=40 -Ddiag_hash_size=4194304
 flagsFor40    = -Dmax_sequence_index=63 -Dmax_malloc_index=40 -Ddiag_hash_size=4194304
 
