--- src/Makefile        2010-01-13 18:00:09.000000000 +0100
+++ src/Makefile.new    2016-02-04 10:02:46.037182250 +0100
@@ -28,7 +28,7 @@
 #
 #---------

-definedForAll = -Wall -Wextra -Werror -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
+definedForAll = -Wall -Wextra -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE


 VERSION_FLAGS= \

