--- src/makefile.old	2022-12-28 09:57:21.013609411 -0600
+++ src/makefile	2022-12-28 21:42:59.434522849 -0600
@@ -1,14 +1,10 @@
-CC      =  gcc
-CFLAGS  =  -g -Wall  -D DEBUG #-O2 
-LDFLAGS = -lz -lm
-
 OBJS = gfa.o opt.o paf.o sdict.o eg.o 
 PROG = calcuts purge_dups pbcstat split_fa get_seqs  ngscstat
 
 .SUFFIXS:.c .o
 
 all:$(PROG)
-	mkdir -p ../bin && cp $(PROG) ../bin
+	mkdir -p ${PREFIX}/bin && cp $(PROG) ${PREFIX}/bin
 calcuts: calcuts.o 
 	$(CC)  $(CFLAGS) $^ -o $@ $(LDFLAGS) 
 purge_dups:opt.o sdict.o asset.o cov.o paf.o purge_dups.o
