#!/usr/bin/env bash
>&2 echo "WARNING: All passed paths must be absolute."
cd PREFIX/Colombo/Colombo
./PROGRAM $@
code=$?
if [ "$code" = "255" ]; then
    >&2 echo "Exited 255"
    exit 0
fi
exit $code
