{% set name = "cutesvtrio" %}
{% set version = "1.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cutesvtrio/cutesvtrio-{{ version }}.tar.gz
  sha256: 6948fa3ce5a0096d665207bf6571ceb6f6700e4460c12c91752ac18e16841777

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - scipy
    - pysam
    - biopython
    - numpy
    - pyvcf3
    - scikit-learn

test:
  commands:
    - cuteSVTrio --help

about:
  home: https://github.com/XLeeHIT/cuteSVTrio
  license: MIT
  license_file: LICENSE
  summary: Long-read-based human genomic structural variation detection with cuteSVTrio

extra:
  recipe-maintainers:
    - XLeeHIT
