diff -u MSAProbs/Makefile MSAProbs.updated/Makefile
--- MSAProbs/Makefile	2012-04-13 09:26:13.000000000 +0100
+++ MSAProbs.updated/Makefie	2020-04-01 14:31:04.737278368 +0100
@@ -2,9 +2,8 @@
 CXXOBJS = MSA.o MSAGuideTree.o MSAClusterTree.o MSAPartProbs.o MSAReadMatrix.o main.o
 
 OPENMP = -fopenmp
-CXX = g++
-COMMON_FLAGS = -O3 $(OPENMP) -Wall -funroll-loops -I . -I /usr/include
-CXXFLAGS = $(COMMON_FLAGS)
+COMMON_FLAGS = -O3 $(OPENMP) -Wall -funroll-loops -I .
+CXXFLAGS = $(COMMON_FLAGS) $(CXX_FLAGS)
 
 EXEC = msaprobs
 
