{% set name = "uscophy" %}
{% set version = "0.1.1" %}
{% set hash = "1ebfae9e3ab8379e903b115c7a5c659c2b022251caa05ddf1153cc1c0877c75d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scicrow/bioconda_uscophy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage('uscophy', max_pin="x.x") }}

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools >=64
  run:
    - python >=3.11
    - snakemake-minimal >=8.0
    - biopython
    - busco >=5.0
    - click
    - diamond
    - hmmer
    - iqtree
    - mafft
    - pandas
    - r-base
    - r-ape
    - r-dplyr
    - r-ggplot2
    - r-patchwork
    - r-readr
    - r-tidyr
    - r-viridis
    - bioconductor-ggtree
    - spades
    - trimal
    - rich

test:
  imports:
    - uscophy
  commands:
    - uscophy --help
    - uscophy run --help
    - uscophy assemble --help

about:
  home: "https://github.com/scicrow/bioconda_uscophy"
  license: "GPL-3.0-only"
  license_family: "GPL"
  license_file: LICENSE
  summary: "A workflow to extract BUSCO genes from assembled genomes and use them for a phylogenetic reconstruction"
  dev_url: "https://github.com/scicrow/bioconda_uscophy"

extra:
  recipe-maintainers:
    - scicrow
