{% set name = "tau-community-detection" %}
{% set version = "1.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9961d32a8d0d6bf0a2b6c732b41cef5912294daa37d08f1fcdec81420d8b8c53

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - networkx >=3.4
    - numpy >=2.0
    - python-igraph >=0.10
    - scikit-learn >=1.6

test:
  imports:
    - tau_community_detection
  commands:
    - tau --help
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tau-community-detection/
  summary: Community detection via Louvain/Leiden + Genetic Algorithm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HillelCharbit
    