--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -1,14 +1,14 @@
 #	Makefile.in for splan/sortgrcd
 #	Copyright(c) Osamu Gotoh <<gotoh.osamu.67a@st.kyoto-u.ac.jp>>
 
-exec_prefix = /usr/local/bin
-table_dir = /usr/local/bin
-alndbs_dir = /db/seqdb
-CXX  = g++
+exec_prefix = $(PREFIX)/bin
+table_dir = $(PREFIX)/share/spaln/table
+alndbs_dir = $(PREFIX)/share/spaln/alndbs
+CXX  = $(CXX)
 #CXX  = clang++
-CFLAGS = -O3 -march=native
+CFLAGS = -O3 -march=native -I$(PREFIX)/include
 RANLIB = ranlib
-LD  = g++
+LD  = $(CXX)
 AR = ar ru
 DEL = rm -f
 DEFLT = -DM_THREAD=1
