diff --git a/src/Makefile.in b/src/Makefile.in
index 7e0ab8d..bd09001 100644
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -1,20 +1,20 @@
 #	Makefile.in for splan/sortgrcd
 #	Copyright(c) Osamu Gotoh <<gotoh.osamu.67a@st.kyoto-u.ac.jp>>
 
-exec_prefix = /usr/local/bin
-table_dir = /usr/local/bin
-alndbs_dir = /db/seqdb
-CXX  = g++
+exec_prefix = $(PREFIX)/bin
+table_dir = $(PREFIX)/share/spaln/table
+alndbs_dir = $(PREFIX)/share/spaln/alndbs
+CXX  = $(CXX)
 # for MACOS uncomment below line
 #CXX  = clang++ -std=c++11
-CFLAGS = -O3 -march=native
+CFLAGS = -O3
 RANLIB = ranlib
-LD  = g++
+LD  = $(CXX)
 AR = ar ru
 DEL = rm -f
 DEFLT = -DM_THREAD=1
 
-CXX := $(CXX) $(CFLAGS) $(DEFLT)
+CXX := $(CXX) $(CFLAGS) $(CPPFLAGS) $(DEFLT)
 
 .SUFFIXES: .o .cc .h .sh
 
