diff --git i/Makefile w/Makefile
index de28bc8..e352ed0 100644
--- i/Makefile
+++ w/Makefile
@@ -6,7 +6,7 @@ SRCS := $(shell find $(SRC_DIR) -type f -name *.cpp)
 OBJS := $(patsubst $(SRC_DIR)/%,$(BUILD_DIR)/%,$(SRCS:.cpp=.o))
 
 # Compiler
-CXX = g++ -std=c++14
+CXX ?= g++ -std=c++14
 CC = $(CXX)
 
 # SeqAn
