--- makefile	2015-09-09 12:28:26.000000000 +0200
+++ makefile	2019-05-18 16:53:17.069339241 +0200
@@ -7,12 +7,12 @@
 # External libraries:
 # 2. Please specify the base directory of your BamTools installation.
 # The BamTools C++ library can be downloaded from https://github.com/pezmaster31/bamtools
-BAMTOOLS=/YourPath/bamtools
+BAMTOOLS=${PREFIX}/include/bamtools
 
 # 3. Please specify the base directory of your SeqAn download as well.
 # The SeqAn C++ library headers can be downloaded from http://packages.seqan.de
 # Take care to pick a SeqAn version >= 2.0.0.
-SEQAN=/YourPath/seqan
+SEQAN=${PREFIX}/include/seqan
 
 # 4. Please make sure, that the Boost C++ libraries are installed on your machine.
 # See, for example, package libboost-dev for Ubuntu and Debian and http://www.boost.org for more information.
@@ -22,7 +22,7 @@
 src/%.o: src/%.cpp
 	@echo 'Building file: $<'
 	@echo 'Invoking: GCC C++ Compiler'
-	$(CC) -I${BAMTOOLS}/include -I${BAMTOOLS}/include/shared -I${SEQAN}/include -O3 -Wall -c -fmessage-length=0 -std=c++0x -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
+	$(CC) -I${BAMTOOLS} -I${BAMTOOLS}/include -I${BAMTOOLS}/include/shared -I${SEQAN}/include -O3 -Wall -c -fmessage-length=0 -std=c++0x -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
 	@echo 'Finished building: $<'
 	@echo ' '
 
