diff --git a/Makefile b/Makefile
index 43a9c91..d937ddd 100644
--- a/Makefile
+++ b/Makefile
@@ -65,6 +65,8 @@ else
   endif
 endif

+CFLAGS += -fPIC
+
 %.o : %.cpp
 	${CC} ${CFLAGS} -c $< -o $@

@@ -73,14 +75,17 @@ endif
 LINKER  := g++
 LIBS :=
 OBJS := GBase.o GStr.o GArgs.o
+GCLIBS := GFastaIndex.o GFaSeqGet.o gff.o gdna.o codons.o GBase.o GStr.o GArgs.o

 .PHONY : all
-all:    gtest threads
+all:    gtest threads gffcomparelibs

 version: ; @echo "GCC Version is: "$(GCC_MAJOR)":"$(GCC_MINOR)":"$(GCC_SUB)
 	@echo "> GCC Opt. string is: "$(GCC45OPTS)
 debug:  gtest threads
 nodebug:  gtest threads
+gffcomparelibs: ${GCLIBS}
+	${LINKER} ${LDFLAGS} $(GCC45OPTS) $(GCC45OPTMAIN) -shared -o libgffc.so ${GCLIBS}
 gtest.o : GBase.h GArgs.h GVec.hh GList.hh GBitVec.h
 GArgs.o : GArgs.h
 gtest: $(OBJS) gtest.o
