diff --git a/Makefile b/Makefile
index 43a9c91..d937ddd 100644
--- a/Makefile
+++ b/Makefile
@@ -75,12 +75,13 @@ LIBS :=
 OBJS := GBase.o GStr.o GArgs.o
 
 .PHONY : all
-all:    gtest threads
+all:    gtest threads gffcomparelibs
 
 version: ; @echo "GCC Version is: "$(GCC_MAJOR)":"$(GCC_MINOR)":"$(GCC_SUB)
 	@echo "> GCC Opt. string is: "$(GCC45OPTS)
 debug:  gtest threads
 nodebug:  gtest threads
+gffcomparelibs: codons.o gdna.o GFaSeqGet.o GFastaIndex.o gff.o
 gtest.o : GBase.h GArgs.h GVec.hh GList.hh GBitVec.h
 GArgs.o : GArgs.h
 gtest: $(OBJS) gtest.o
