--- Makefile.bk	2020-07-29 11:50:41.000000000 +0200
+++ Makefile	2020-07-29 11:50:58.000000000 +0200
@@ -38,7 +38,7 @@
 ## ---------- END EDIT ---------- ##
 
 ## option needed with gcc 6 series:
-C_OPTS=-fPIC
+C_OPTS?=-fPIC
 
 ifdef DEBUG
     BIN_NAME = nemoage$(VERSION)D
@@ -114,7 +114,7 @@
 
 OBJ_PATH = src/
 OBJECTS = $(shell for file in $(SOURCES);\
-                do echo -n $$file | sed -e "s/\(.*\)\.cc/\1\.o/"; echo -n " ";\
+                do echo $$file | sed -e "s/\(.*\)\.cc/\1\.o/"; echo " ";\
                 done)
 
 all : bin
@@ -129,7 +129,7 @@
 	$(CC) -o $(LIB) $(OBJECTS) $(LD_OPTS) $(LDFLAGS)
 
 bin : $(OBJECTS)
-	$(CC) -o $(BIN) $(OBJECTS) $(LD_OPTS)
+	$(CC) -o $(BIN) $(OBJECTS) $(LDFLAGS) $(LD_OPTS)
 
 clean :
 	rm -f $(OBJECTS)
