--- Makefile.bk	2020-07-29 11:50:41.000000000 +0200
+++ Makefile	2020-07-29 11:50:58.000000000 +0200
@@ -129,7 +129,7 @@
 	$(CC) -o $(LIB) $(OBJECTS) $(LD_OPTS) $(LDFLAGS)

 bin : $(OBJECTS)
-	$(CC) -o $(BIN) $(OBJECTS) $(LD_OPTS)
+	$(CC) -o $(BIN) $(OBJECTS) $(LD_OPTS) $(LDFLAGS)

 clean :
 	rm -f $(OBJECTS)
