{% set version = "2.2.1" %}
{% set sha256 = "74d74f8f0e771af3d88b3ab50b9d53604fff1538003eae1f65b5abcab2e8c245" %}

package:
  name: kmercamel
  version: {{ version }}

source:
  url: https://github.com/OndrejSladky/kmercamel/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('kmercamel', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - zlib
    - glpk
  run:
    - glpk

test:
  commands:
    - kmercamel -h 2>&1 | grep "KmerCamel"

about:
  home: https://github.com/OndrejSladky/kmercamel
  dev_url: https://github.com/OndrejSladky/kmercamel
  doc_url: "https://github.com/OndrejSladky/kmercamel/blob/v{{ version }}/README.md"
  license: MIT
  license_family: MIT
  license_file: "LICENSE.txt"
  summary: "KmerCamel🐫 - compressing k-mer sets using masked superstrings."

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1101/2023.02.01.526717
