{% set name = "blobtk" %}
{% set version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/genomehubs/blobtk/archive/{{ version }}.tar.gz
  sha256: 3fe9d4f99b0f648fb3eeeda8cc09b411b94f9966423890822ec446cb46264aee

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('blobtk', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - clangdev
    - llvmlite
    - pkg-config
  host:
    - python
    - pip
    - maturin
    - curl
    - wget
    - openssl
    - zlib
  run:
    - python

test:
  imports:
    - blobtk
  commands:
    - blobtk --help

about:
  home: "https://github.com/genomehubs/blobtk"
  summary: "Core functionality shared across BlobToolKit tools."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://github.com/genomehubs/blobtk"
  doc_url: "https://github.com/genomehubs/blobtk/wiki"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
