{% set name = "kfb2zarr" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/camlloyd/kfb2zarr/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bad1fcf0f0e01fe005b29d635924ea86a4f77b8e174d2707bfa6fbccf52a65ce

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config

test:
  commands:
    - kfb2zarr --help

about:
  home: https://github.com/camlloyd/kfb2zarr
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Convert KFBio whole slide images (.kfb, .kfbf) to OME-Zarr

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - camlloyd
