{% set version = "0.2.1" %}
{% set github = "https://github.com/acidgenomics/py-goalie" %}

package:
  name: goalie
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/a/acidgenomics-goalie/acidgenomics_goalie-{{ version }}.tar.gz"
  sha256: 0cc44fb25a8b9e7e11dfcffcf1d55d4954ba1da1952ec52e46f0f9d6ada4c2b8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
  run_exports:
    - {{ pin_subpackage('goalie', max_pin="x.x") }}

requirements:
  host:
    - python >=3.12
    - pip
    - uv-build >=0.11,<1
  run:
    - python >=3.12

test:
  imports:
    - goalie

about:
  home: https://python.acidgenomics.com/goalie/
  dev_url: "{{ github }}"
  license: Apache-2.0
  license_file: LICENSE
  summary: Assertive check functions for defensive Python programming.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
