--- Makefile	2016-09-19 09:15:23.000000000 +0000
+++ Makefile.new	2016-09-19 09:15:15.000000000 +0000
@@ -34,7 +34,7 @@
 SRC =
 
 CXX      = g++
-CXXFLAGS = -Wall -Wextra -g -O2 -I$(srcdir)
+CXXFLAGS = -Wall -Wextra -g -O2 -I$(srcdir) -I$(PREFIX)/include -L$(PREFIX)/lib
 LDFLAGS  =
 LDLIBS   = -lz
 AR       = ar
