{% set version = "2.3.3" %}

package:
  name: rapidnj
  version: {{ version }}

source:
  url: https://github.com/somme89/rapidNJ/archive/ed2d36e219d9db16778b941b5054c0fd021b528a.tar.gz
  sha256: 57ea662a3589459528beaa96de011bd1b389630484d9e3215a942bdb19518f21
  patches:
    - 0001-Makefile.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('rapidnj', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

test:
  commands:
    - rapidnj -h 2>&1 | grep "neighbour-joining"

about:
  home: "https://birc.au.dk/software/rapidnj"
  license: "GPL-2.0-only"
  license_family: GPL
  license_file: LICENSE
  summary: RapidNJ is an algorithmic engineered implementation of canonical
    neighbour-joining. It uses an efficient search heuristic to speed-up the
    core computations of the neighbour-joining method that enables RapidNJ to
    outperform other state-of-the-art neighbour-joining implementations.
  dev_url: "https://github.com/somme89/rapidNJ"
  doc_url: "https://github.com/somme89/rapidNJ/blob/master/README"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1007/978-3-540-87361-7_10
    - biotools:rapidnj
  skip-lints:
    - compiler_needs_stdlib_c
