{% set name = "vcf-validator" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tcezard/vcf-validator/archive/refs/tags/test_artifacts.tar.gz
  sha256: 68533d3826dc6bd4526a8413b8b04b298bb0f4dd8b1110dfed4465282575fbe4


build:
  script:
  number: 0
  run_exports:
    - {{ pin_subpackage("vcf-validator", max_pin="x.x") }}

requirements:
  host:
    - cmake >=2.8
    - sqlite
    - libsqlite
    - zlib
    - automake
    - bootstrap
    - libboost-devel
    - libtool
    - zstd
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake >=2.8
    - sqlite
    - libsqlite
    - zlib
    - automake
    - bootstrap
    - libboost-devel
    - libtool
    - zstd
    - c-ares
    - wget
  run:
    - zstd


test:
  commands:
    - vcf_validator --help
    - vcf_assembly_checker --help

about:
  home: https://github.com/EBIVariation/vcf-validator
  summary: EBI EVA - Validation tool for VCF file format compliance
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apriltuesday
    - tcezard
    - ebi-variation