{% set name = "vcf-validator" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tcezard/vcf-validator/archive/refs/tags/test_artifacts.tar.gz
  sha256: 13c738847ec701278ff5cfadde67a13768ae67da487b08dd7f2da06c0f48a22d


build:
  script:
  number: 0
  run_exports:
    - {{ pin_subpackage("vcf-validator", max_pin="x.x") }}

requirements:
  host:
    - libboost-devel
    - libcurl
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libboost-devel
    - libtool
    - zstd
    - c-ares
    - libcurl
    - openssl
    - bzip2
    - libzlib
  run:
    - zstd
    - libcurl


test:
  commands:
    - vcf_validator --help
    - vcf_assembly_checker --help

about:
  home: https://github.com/EBIVariation/vcf-validator
  summary: EBI EVA - Validation tool for VCF file format compliance
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apriltuesday
    - tcezard
    - ebi-variation