--- bin/Makefile	2019-06-26 21:23:07.000000000 +1000
+++ bin/Makefilefixed	2025-03-24 10:00:00.450190734 +1100
@@ -33,22 +33,22 @@
 # # Top-level targets
  all: 
 	rm -rf AccSurf.o CalcAccSurf.o  Contacts.o  Date.o  DsspCMBI.o  p2clib.o Vector.o  .//serialcompare .//pipe .//filter95fitz .//selfdccp .//pipedccp .//fssp .//puu .//puutos .//dsspcmbi .//mpicompare dalicon.mod  dp.mod  filter95.mod  parsi.mod  soap.mod  wolf.mod
-	gcc -c -O -Wall -DGCC ../src/dsspcmbi/AccSurf.c
-	gcc -c -O -Wall -DGCC ../src/dsspcmbi/CalcAccSurf.c
-	gcc -c -O -Wall -DGCC ../src/dsspcmbi/Contacts.c
-	gcc -c -O -Wall -DGCC ../src/dsspcmbi/Date.c
-	gcc -c -O -Wall -DGCC ../src/dsspcmbi/DsspCMBI.c
-	gcc -c -O -Wall -DGCC ../src/dsspcmbi/p2clib.c
-	gcc -c -O -Wall -DGCC ../src/dsspcmbi/Vector.c
-	gcc -o .//dsspcmbi DsspCMBI.o p2clib.o Date.o Vector.o AccSurf.o CalcAccSurf.o Contacts.o -lm
-	gfortran -O3                     ../src/util.f ../src/subfitzfast.f ../src/parsi-admin.f ../src/parsi-align.f ../src/parsi-score.f ../src/parsi-stack.f ../src/parsi-1.f ../src/gagadccp.f ../src/gagagene.f ../src/gagahash.f ../src/gagatool.f ../src/lean.f ../src/clean.f ../src/ssap.f ../src/dimple.f ../src/triplet.f ../src/testi.f ../src/soap4.f ../src/wolf_original.f ../src/u3b-8.f  ../src/comparemodules.f ../src/serialcompare.f -o .//serialcompare
-	gfortran -O3                     ../src/pipe.f ../src/util.f -o .//pipe
-	gfortran -O3                     ../src/filter95fitz.f ../src/util.f ../src/u3b-8.f ../src/subfitzfast.f -o .//filter95fitz
-	gfortran -O3                     ../src/selfdccp.f ../src/util.f -o .//selfdccp
-	gfortran -O3                     ../src/pipedccp.f -o .//pipedccp
-	gfortran -O3                     ../src/fssp.f ../src/util.f ../src/u3b-8.f -o .//fssp
-	gfortran -O3                     ../src/main.f ../src/puu.f ../src/util.f -o .//puu
-	gfortran -O3                     ../src/puutos.f ../src/util.f -o .//puutos
+	${CC} -c -O -Wall -DGCC ../src/dsspcmbi/AccSurf.c
+	${CC} -c -O -Wall -DGCC ../src/dsspcmbi/CalcAccSurf.c
+	${CC} -c -O -Wall -DGCC ../src/dsspcmbi/Contacts.c
+	${CC} -c -O -Wall -DGCC ../src/dsspcmbi/Date.c
+	${CC} -c -O -Wall -DGCC ../src/dsspcmbi/DsspCMBI.c
+	${CC} -c -O -Wall -DGCC ../src/dsspcmbi/p2clib.c
+	${CC} -c -O -Wall -DGCC ../src/dsspcmbi/Vector.c
+	${CC} -o .//dsspcmbi DsspCMBI.o p2clib.o Date.o Vector.o AccSurf.o CalcAccSurf.o Contacts.o -lm
+	${FC} -O3                     ../src/util.f ../src/subfitzfast.f ../src/parsi-admin.f ../src/parsi-align.f ../src/parsi-score.f ../src/parsi-stack.f ../src/parsi-1.f ../src/gagadccp.f ../src/gagagene.f ../src/gagahash.f ../src/gagatool.f ../src/lean.f ../src/clean.f ../src/ssap.f ../src/dimple.f ../src/triplet.f ../src/testi.f ../src/soap4.f ../src/wolf_original.f ../src/u3b-8.f  ../src/comparemodules.f ../src/serialcompare.f -o .//serialcompare
+	${FC} -O3                     ../src/pipe.f ../src/util.f -o .//pipe
+	${FC} -O3                     ../src/filter95fitz.f ../src/util.f ../src/u3b-8.f ../src/subfitzfast.f -o .//filter95fitz
+	${FC} -O3                     ../src/selfdccp.f ../src/util.f -o .//selfdccp
+	${FC} -O3                     ../src/pipedccp.f -o .//pipedccp
+	${FC} -O3                     ../src/fssp.f ../src/util.f ../src/u3b-8.f -o .//fssp
+	${FC} -O3                     ../src/main.f ../src/puu.f ../src/util.f -o .//puu
+	${FC} -O3                     ../src/puutos.f ../src/util.f -o .//puutos
 	$(FC) $(CFLAGS) $(SRC)/pipe.f $(SRC)/util.f -o $(BIN)/pipe
 	$(FC) $(CFLAGS) $(SRC)/filter95fitz.f $(SRC)/util.f $(SRC)/u3b-8.f $(SRC)/subfitzfast.f -o $(BIN)/filter95fitz
 	$(FC) $(CFLAGS) $(SRC)/selfdccp.f $(SRC)/util.f -o $(BIN)/selfdccp
