{% set name = "somatem" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/treangenlab/somatem/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0d9f84f2c9691d6d33837fd1c6ca5bc729ea21ff0993b1b97584f2b8bc8142de

build:
  noarch: generic
  number: 0

requirements:
  run:
    - bash
    - nextflow >=26.04.4
    - micromamba
    - coreutils

test:
  commands:
    - somatem --help
    - test -f "${PREFIX}/share/{{ name }}-{{ version }}/main.nf"
    - test -f "${PREFIX}/share/{{ name }}-{{ version }}/nextflow.config"
    - test -f "${PREFIX}/bin/{{ name }}"

about:
  home: https://github.com/treangenlab/somatem
  summary: "Best practices pipeline for long-read metagenomics analysis."
  license: GPL-3.0
  license_file: LICENSE
  dev_url: https://github.com/treangenlab/somatem
  doc_url: https://github.com/treangenlab/somatem#readme

extra:
  notes: |
    Somatem installs a wrapper command that launches bundled Nextflow workflows from
    $PREFIX/share/{{ name }}-{{ version }}. Use `somatem --help` to see supported
    workflow shortcuts and common arguments.
  watch:
    enable: true
  skip-lints:
    - missing_run_exports
  recipe-maintainers:
    - ppreshant
    - microbemarsh
