diff --git a/Makefile b/Makefile
index 5d6b76a..66ea8dd 100755
--- a/Makefile
+++ b/Makefile
@@ -23,11 +23,11 @@
 # Uncomment and change these variables as necessary.
 #
 
-INC_FLAG =
-LIB_FLAG =
+INC_FLAG = -I${PREFIX}/include
+LIB_FLAG = -L${PREFIX}/lib
 #INC_FLAG = -I/home/gradstud/myBoost/include -I/home/gradstud/myGSL/include
 #LIB_FLAG = -L/home/gradstud/myBoost/lib -L/home/gradstud/myGSL/lib
-LIB = -lboost_thread -lboost_program_options -lboost_system -lgsl -lgslcblas
+LIB = -lpthread -lboost_thread -lboost_program_options -lboost_system -lgsl -lgslcblas
 
 
 # Typical for OS X:
