--- a/LDhelmet_v1.10/Makefile
+++ b/LDhelmet_v1.10/Makefile
@@ -30 +30 @@
-LIB = -lboost_thread -lboost_program_options -lboost_system -lgsl -lgslcblas
+LIB = -lpthread -lboost_thread -lboost_program_options -lboost_system -lgsl -lgslcblas
