{% set name = "sercol" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7d591005a98e39c9a5574a6a832de1543f1a120f863b81cbf1fc25a915057bf3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv"
  run_exports:
    - {{ pin_subpackage('sercol', max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=64
  run:
    - pandas >=2.0.0,<3
    - python >=3.9
    - serializable >=1.0.0,<2

test:
  imports:
    - sercol

about:
  home: "https://github.com/openvax/sercol"
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: "Rich collection class with grouping and filtering helpers"

extra:
  recipe-maintainers:
    - jonasscheid
