--- Makefile.bak	2016-03-07 21:43:37.000000000 +0100
+++ Makefile	2016-03-07 21:55:08.000000000 +0100
@@ -14,7 +14,7 @@
 CFLAGS=-O3
 CXX=g++
 CC=gcc
-HDF5=install
+#HDF5=install
 
 # Check operating system, OSX doesn't have -lrt
 UNAME_S := $(shell uname -s)
@@ -35,11 +35,11 @@
 endif
 
 # Bulild and link the libhts submodule
-HTS_LIB=./htslib/libhts.a
-HTS_INCLUDE=-I./htslib
+HTS_LIB=${PREFIX}/lib/libhts.a
+HTS_INCLUDE=-I${PREFIX}/include/htslib
 
 # Include the header-only fast5 library
-FAST5_INCLUDE=-I./fast5
+FAST5_INCLUDE=-I${PREFIX}/include/fast5
 
 # Include the src subdirectories
 NP_INCLUDE=$(addprefix -I./, $(SUBDIRS))
