{% set name = "pyrle" %}
{% set version = "0.0.44" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24c067dc7e87e381a1b5ff81247608ff67aa5fa40b6ec55146f0c76f7d177770

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python
    - pandas
    - tabulate
    - numpy
    - natsort
    - setuptools

test:
  imports:
    - pyrle

about:
  home: "https://github.com/endrebak/pyrle"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Genomic Rle-objects for Python."
  dev_url: "https://github.com/endrebak/pyrle"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  skip-lints:
    - uses_setuptools
