{% set name = "vcfexpress" %}
{% set version = "0.3.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/brentp/vcfexpress/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f60b7d2eeccff4ce923a73ebdaa5e48200f2bcdfdbe15d17391c5c08a9b9cde3

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage('vcfexpress', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    - clangdev
    - cmake
    - make
    - pkg-config

test:
  commands:
    - vcfexpress --help

about:
  home: "https://github.com/brentp/vcfexpress"
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "Expressions on VCFs."
  dev_url: "https://github.com/brentp/vcfexpress"
  doc_url: "https://github.com/brentp/vcfexpress/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
