{% set version = "2026_06" %}

package:
  name: ngs-bits
  version: {{ version }}

source:
  url: https://github.com/imgag/ngs-bits/releases/download/{{ version }}/ngs-bits-{{ version }}.tgz
  sha256: 9d67392ce9bc01fe75db0171535ed06f58901945b465e2ad0acee8120752bbd2

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('ngs-bits', max_pin=None) }}

# Note: pinning of sysroot_linux-64 =2.17 enforces cos7 and is currently needed to prevent an memcpy@GLIBC2.14 error
requirements:
  build:
    - {{ stdlib('c') }}
    - make
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - qt6-main
    - qt6-charts
    - libxml2
    - bzip2
    - xz
    - zlib
    - htslib
    - libgl-devel     # [linux]
    - libegl-devel    # [linux]
    - libopengl-devel # [linux]
  run:
    - qt6-main
    - qt6-charts
    - htslib

about:
  home: "https://github.com/imgag/ngs-bits"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Short-read and long-read sequencing tools for diagnostics."
  dev_url: "https://github.com/imgag/ngs-bits"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  #For libGL dependency docu see: https://conda-forge.org/docs/maintainer/knowledge_base.html#core-dependency-tree-packag>extra:
  container:
    extended-base: True
