{% set version = "0.1.0" %}

package:
  name: metacontextify
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metacontextify-{{ version }}.tar.gz
  sha256: f78dc860b5261770690e77b886a9c684f524f1b114565a6779879bdb6d79bc48

build:
  entry_points:
    - metacontextify = metacontextify.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - pandas >=1.3.0
    - requests >=2.25.0
    - urllib3 >=1.26.0
    - xarray >=0.20.0
    - copernicusmarine >=0.1.0
    - beautifulsoup4 >=4.9.0
    - appdirs >=1.4.4
    - typer
    - netcdf4

test:
  imports:
    - metacontextify
  commands:
    - pip check
    - metacontextify --help
  requires:
    - pip

about:
  summary: Automated environmental annotation of marine metagenomic samples
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MaartenLangen
