{% set name = "cadd_threshold_app" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower|replace('_', '-') }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 724ef641a4826183c121334b8a6244c64ad2ab0e2a3eff8ac1ca560e9904ba7c

build:
  run_exports:
    - {{ pin_subpackage('cadd-threshold-app', max_pin="x.x") }}
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.10
    - pandas
    - requests
    - anywidget
    - click
    - numpy
    - plotly
    - shiny
    - shinywidgets
    - scikit-learn

test:
  imports:
    - cadd_threshold_app
  commands:
    - cadd-threshold-app --help
  requires:
    - pip

about:
  home: https://github.com/kircherlab/CADD_threshold_app
  summary: Shiny-for-Python app for exploring ClinVar distributions across CADD score thresholds.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - visze
    - coraleif
