{% set version = "0.0.12" %}
{% set sha256 = "45bd4e0a585ccb828741fa53ae10bb5a1d19638e77eadc8f16ae8dbc1de49dcc" %}

package:
  name: proteomiqon-psmbasedquantificationtims
  version: '{{ version }}'

source:
  url: https://www.nuget.org/api/v2/package/ProteomIQon.PSMBasedQuantificationTIMs/{{ version }}
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 1
  run_exports:
    - dotnet-runtime =8.0

requirements:
  host:
    - unzip
  run:
    - dotnet-runtime =8.0
    - libzlib

test:
  commands:
    - proteomiqon-psmbasedquantificationtims --help

about:
  home: https://csbiology.github.io/ProteomIQon/
  license: MIT
  summary: PSM-based quantification for trapped ion mobility spectrometry data
  description: >-
    ProteomIQon.PSMBasedQuantificationTIMs performs PSM-based peptide ion
    quantification for mass spectrometry data with ion mobility information.
  dev_url: https://github.com/CSBiology/ProteomIQon
  doc_url: https://csbiology.github.io/ProteomIQon/


