package:
  name: ilesta
  version: "1.0.0"

source:
  url: https://github.com/yvlaere/Ilesta/archive/refs/tags/v1.0/Ilesta-1.0.tar.gz
  sha256: c8f1ee1456b550ed67a5d039390ee21ca808f3607c97de4c59535d6e0dd3fa6a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('ilesta', max_pin="1.0") }}
  script:
    - cargo install -v --locked --no-track --root $PREFIX --path .

requirements:
  build:
    - {{ compiler('rust') }}
  run: []

test:
  commands:
    - Ilesta --help

about:
  home: https://github.com/yvlaere/Ilesta
  license: GLP-3.0
  summary: "De novo genome assembler for long-read sequencing data"

extra:
  recipe-maintainers:
    - yvlaere
