FROM bioconda/bioconda-utils-build-env
# Retrieve index and set TTL to make it last over the duration of the test.
RUN \
    conda search bioconda-utils > /dev/null && \
    conda config --set local_repodata_ttl 3600
