#!/bin/bash

mkdir build
cd build

cmake \
    -D CMAKE_INSTALL_PREFIX=${PREFIX} \
    -D CMAKE_INSTALL_RPATH:STRING=${PREFIX}/lib \
    -D CMAKE_BUILD_TYPE=Release \
    -D BUILD_DIAG_PATHOLOGY_EXECUTABLES:BOOL=ON \
    -D BUILD_DIAG_PATHOLOGY_WORKSTATION:BOOL=ON \
    -D BUILD_DIAG_PATHOLOGY_IMAGEPROCESSING:BOOL=ON \
    -D DCMTKJPEG_LIBRARY:STRING=${PREFIX}/lib \
    -D DCMTKJPEG_INCLUDE_DIR:STRING=${PREFIX}/include \    
    -D OPENSLIDE_LIBRARY:STRING=${PREFIX}/lib \
    -D OPENSLIDE_INCLUDE_DIR:STRING=${PREFIX}/include \
        ..

make -j$CPU_COUNT
make install
