#!/bin/bash

mkdir build
cd build

export OPENSLIDE_LIBRARY=${PREFIX}/lib
export OPENSLIDE_INCLUDE_DIR=${PREFIX}/include

cmake \
    -D CMAKE_INSTALL_PREFIX=${PREFIX} \
    -D CMAKE_INSTALL_RPATH:STRING=${PREFIX}/lib \
    -D CMAKE_BUILD_TYPE=Release \
    -D BUILD_DIAG_PATHOLOGY_EXECUTABLES:BOOL=ON \
    -D BUILD_DIAG_PATHOLOGY_WORKSTATION:BOOL=ON \
    -D BUILD_DIAG_PATHOLOGY_IMAGEPROCESSING:BOOL=ON \
    -D OPENSLIDE_LIBRARY:STRING=${OPENSLIDE_LIBRARY} \
    -D OPENSLIDE_INCLUDE_DIR:STRING=${OPENSLIDE_INCLUDE_DIR} \
        ..

make -j$CPU_COUNT
make install
