{% set name = "viral_consensus" %}
{% set version = "1.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/niemasd/ViralConsensus/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2aa7e0e4d8dc2620a938461b0288fafb7a1b76fc5c74dc0ad69a1c62a5d89f05

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('viral_consensus', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
  host:
    - htslib
    - libcurl
    - bzip2
    - xz
    - zlib

test:
  commands:
    - viral_consensus --version

about:
  home: "https://niema.net/ViralConsensus"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Fast viral consensus genome reconstruction."
  dev_url: "https://github.com/niemasd/ViralConsensus"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - biotools:viral_consensus
    - doi:10.1093/bioinformatics/btad317
    - doi:10.1093/bioinformatics/btae018
  recipe-maintainers:
    - niemasd
