--- c++/Makefile    2016-09-19 09:15:23.000000000 +0000
+++ c++/Makefile.new    2016-09-19 09:15:15.000000000 +0000
@@ -33,7 +33,7 @@
 
-CANSAM = ../cansam
+CANSAM = $(PREFIX)/lib
 
-CXXFLAGS = -Wall -Wextra -g -I$(CANSAM) -O2
+CXXFLAGS = -Wall -Wextra -g -I$(CANSAM) -O2 -I$(PREFIX)/include
 LDFLAGS  = -L$(CANSAM)
 
 ALL_TARGETS = augment-bam brass-group filterout-bam
