diff --git a/Makefile b/Makefile
index 61c56fc..3062ade 100644
--- a/Makefile
+++ b/Makefile
@@ -12,7 +12,7 @@ INSTALLDIR=/usr/local/bin
 
 # default C++ compiler and flags
 CXX=g++
-CFLAGS=-O -I./libsrc -D__ZLIB_AVAILABLE__
+CFLAGS=-O -I./libsrc -I$(PREFIX)/include -L$(PREFIX)/lib -lz -D__ZLIB_AVAILABLE__
 
 # executable file names and locations
 BINDIR = executables
