{% set name = "perl-gd" %}
{% set version = "2.90" %}
{% set sha256 = "4383e4b345a65e94921e4e6b1db61fddabe8af7ce72f5442e026c014149ffdbf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RU/RURBAN/GD-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - libgd
  host:
    - perl
    - perl-extutils-makemaker
    - perl-extutils-pkgconfig
    - perl-test-fork
    - perl-test-nowarnings
    - perl-extutils-constant
    - perl-file-which
    - libgd
    - zlib
    - expat
  run:
    - libgd
    - perl

test:
  imports:
    - GD
    - GD::Simple

about:
  home: "https://metacpan.org/pod/GD"
  license: "perl_5"
  summary: "Perl interface to the gd2 graphics library."
  dev_url: "https://metacpan.org/pod/GD"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
