{% set name = "vicmag" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TsudaYusuke/VicMAG/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8e148cc7c072be06c6fae0065cb132d6fd71b2b102d16192ba1826674e93a858

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  host:
    - python

  run:
    - python
    - pandas
    - numpy
    - matplotlib-base
    - biopython
    - biotite
    - pillow

test:
  commands:
    - vicmag --help

about:
  home: https://github.com/TsudaYusuke/VicMAG
  license: MIT
  license_file: LICENSE
  summary: A visualization tool for circular metagenome-assembled genomes
  description: |
    VicMAG is a visualization tool for circular metagenome-assembled genomes
    focusing on virulence genes, antimicrobial resistance genes, plasmids,
    and viral regions.

extra:
  recipe-maintainers:
    - TsudaYusuke
