{% set name = "kma" %}
{% set version = "1.6.10" %}
{% set sha256 = "45719d0ce74fa59a76e4352b7a0800c193bf6f65643375f6576b940b4735cc16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://bitbucket.org/genomicepidemiology/kma/get/fdfc9b4bf3cc6fd252da0478685b1d8f5da6bd0a.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib

test:
  commands:
   - kma -h | grep KMA >/dev/null
   - kma index -h | grep kma_index
   - kma shm -h | grep kma_shm >/dev/null
   - kma update -h | grep KMA_update >/dev/null

about:
  home: "https://bitbucket.org/genomicepidemiology/kma"
  summary: 'KMA is a mapping method designed to map raw reads directly against redundant databases, in an ultra-fast manner using seed and extend.'
  license: "Apache-2.0"
  license_family: APACHE
  license_file: LICENSE
  dev_url: "https://bitbucket.org/genomicepidemiology/kma"
  doc_url: "https://bitbucket.org/genomicepidemiology/kma/src/{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1093/nargab/lqaf116
    - usegalaxy-eu:kma_map
    - biotools:kma
  skip-lints:
    - compiler_needs_stdlib_c
