{% set name = "kma" %}
{% set version = "1.6.11" %}
{% set sha256 = "5f386bf3a8d8a56373c1d41b6b6ea52d393d3032d40e6ec42224c87d5da1859e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://bitbucket.org/genomicepidemiology/kma/get/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - zlib

test:
  commands:
   - kma -h | grep KMA >/dev/null
   - kma index -h | grep kma_index
   - kma shm -h | grep kma_shm >/dev/null
   - kma update -h | grep KMA_update >/dev/null

about:
  home: "https://bitbucket.org/genomicepidemiology/kma"
  summary: 'KMA is a mapping method designed to map raw reads directly against redundant databases, in an ultra-fast manner using seed and extend.'
  license: "Apache-2.0"
  license_family: APACHE
  license_file: LICENSE
  dev_url: "https://bitbucket.org/genomicepidemiology/kma"
  doc_url: "https://bitbucket.org/genomicepidemiology/kma/src/{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1093/nargab/lqaf116
    - usegalaxy-eu:kma_map
    - biotools:kma
