--- Makefile
+++ Makefile
@@ -26,9 +26,16 @@
 	rm -fr ${INCLDIR}/simde && cp -r taffy/submodules/abPOA/include/simde ${INCLDIR}
 
+hal: sonLib
+	mkdir -p ${LIBDIR} ${INCLDIR}
+	cd taffy/submodules/hal && ${MAKE}
+	ln -f taffy/submodules/hal/lib/*.a ${LIBDIR}
+
 ${LIBDIR}/libabpoa.a : abPOA

 ${sonLibDir}/sonLib.a : sonLib

 ${sonLibDir}/cuTest.a : sonLib

+${LIBDIR}/libHalBlockViz.a : hal
+
-stTafDependencies = ${sonLibDir}/sonLib.a ${sonLibDir}/cuTest.a ${LIBDIR}/libabpoa.a
+stTafDependencies = ${sonLibDir}/sonLib.a ${sonLibDir}/cuTest.a ${LIBDIR}/libabpoa.a ${LIBDIR}/libHalBlockViz.a
