{% set name = "taffy" %}
{% set version = "0.0.3" %} 

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/taffy-{{ version }}.tar.gz
  sha256: 6847c5826eb6d7495a579559e4c59f51ace79dcb21eb276bd0e7dcbea072b962

build:
  number: 0
  skip: true  # [py<37]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - cffi >=1.0.0
    - numpy
    - htslib
  run:
    - python >=3.8
    - cffi >=1.0.0
    - pytorch
    - numpy
    - matplotlib-base
    - htslib

test:
  imports:
    - taffy
  commands:
    - taffy view -h
    - taffy norm -h
    - taffy add-gap-bases -h
    - taffy index -h 
    - taffy sort -h           
    - taffy stats -h
    - taffy coverage -h
    - taffy annotate -h

about:
  home: https://github.com/ComparativeGenomicsToolkit/taffy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Taffy is a tool for manipulating taf and maf format alignments'
  description: |
    Taffy converts between pangenome graph formats (GFA, VG, MAF) and 
    provides utilities for working with pangenome alignments.
  dev_url: https://github.com/ComparativeGenomicsToolkit/taffy

extra:
  recipe-maintainers:
    - SaimMomin12