--- src_2.0/Makefile	2015-06-17 21:38:40.000000000 +0000
+++ src_2.0/Makefile.new	2018-09-24 22:49:08.524133645 +0000
@@ -2,7 +2,6 @@

 # CXX = /usr/bin/c++
 # CXX = /usr/bin/g++
-CXX = g++-8

 CXXFLAGS = -std=c++14 -fopenmp -O3 -g -fmessage-length=0 -Wall -fpermissive
