diff --git a/src/libbsc/bsc.h b/src/libbsc/bsc.h
index 25230dc..caca189 100644
--- a/src/libbsc/bsc.h
+++ b/src/libbsc/bsc.h
@@ -48,6 +48,7 @@ preprocessor macro LIBBSC_SORT_TRANSFORM_SUPPORT at compile time.
 #ifndef SPRING_LIBBSC_BSC_H_
 #define SPRING_LIBBSC_BSC_H_
 
+#include <cstdint>
 #include "params.h"
 
 namespace spring {
diff --git a/src/util.h b/src/util.h
index 30bad68..a72a0b6 100644
--- a/src/util.h
+++ b/src/util.h
@@ -17,6 +17,7 @@ limitations under the License.
 
 #include <fstream>
 #include <string>
+#include <cstdint>
 
 namespace spring {