#!/bin/bash

# Create Conda directories
mkdir -p ${PREFIX}/bin
mkdir -p ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}

# Copy the pipeline contents
cp -R workflow config data profiles resources slurm_scripts ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}/ 2>/dev/null || true
cp DiscoVir.sh README.md LICENSE accessions.txt ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}/ 2>/dev/null || true

# Construct the executable proxy script
cat << EOF > ${PREFIX}/bin/discovir
#!/bin/bash
# DiscoVir wrapper generated by Conda
DIR="\$( cd "\$( dirname "\${BASH_SOURCE[0]}" )" && pwd )"
bash "\$DIR/../share/${PKG_NAME}-${PKG_VERSION}/DiscoVir.sh" "\$@"
EOF

# Make it executable
chmod +x ${PREFIX}/bin/discovir
