{% set name = "discovir" %}
{% set version = "1.0.1.beta" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/matheus-cosentino/discovir/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: "79a6b594f16bd6c62148f506cd634be90465f28469901d44251b8bffc55deaea"

build:
  number: 0
  noarch: generic

requirements:
  host:
    - python >=3.11,<3.13
  run:
    - bash
    - python >=3.11,<3.13
    - snakemake >=9.11.1
    - snakemake-executor-plugin-slurm >=2.0.0
    - coreutils

test:
  commands:
    - discovir --help
    - discovir --version

about:
  home: "https://github.com/matheus-cosentino/discovir"
  license: "GPL-3.0-or-later"
  license_family: GPL
  license_file: LICENSE
  summary: "A Snakemake Pipeline for Integrated Viral Discovery."
