{% set name = "fmh-funprofiler" %}
{% set commit = "806045cc6b9cbd1a2f227185356a4dd9217f3db9" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/KoslickiLab/fmh-funprofiler/archive/806045cc6b9cbd1a2f227185356a4dd9217f3db9.tar.gz
  sha256: dd95a1ee5012c2ec529ae2b475a26fda31abc37544acb35238c3514c2fddbcbb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pandas
    - numpy
    - sourmash
    - biom-format

test:
  import:
    - fmh-funprofiler
  commands:
    - funcprofiler --help

about:
  home: https://github.com/KoslickiLab/fmh-funprofiler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "fmh-funprofiler is a pipeline that leverages FracMinHash (implemented in sourmash) to functionally profile metagenomic samples, offering a faster and more memory-efficient alternative to alignment-based methods."
  dev_url: https://github.com/KoslickiLab/fmh-funprofiler

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btae397
    - biotools:fmh-funprofiler
  recipe-maintainers:
    - miraep8
