{% set name = "hipstr" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tfwillems/HipSTR/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f44b6d09e9eb92c0798c1c5e36432f2255b7c13eee90295ba2a455df309e3bf3

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('hipstr', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
  host:
    - zlib
    - bzip2
    - xz
  run:
    - python

test:
  commands:
    - HipSTR --help

about:
  home: https://github.com/tfwillems/HipSTR
  license: GPL-2.0-only
  license_file: LICENSE
  summary: Genotype and phase short tandem repeats using Illumina whole-genome sequencing data

extra:
  identifiers:
    - doi:10.1038/nmeth.4267
    - biotools:hipstr