{% set name = "emits" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/ayobi/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0cd8e6fd293bcbe9785e58be3e105d3d764575648949da817e48fd242676026b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
  host:
  run:
    - minimap2

test:
  commands:
    - emits --help

about:
  home: https://github.com/ayobi/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "EM abundance estimation for fungal ITS communities from long-read sequencing"
  dev_url: https://github.com/ayobi/{{ name }}

extra:
  recipe-maintainers:
    - ayobi
