{% set version = "0.3.2" %}
{% set github = "https://github.com/acidgenomics/r-eggnog" %}

package:
  name: r-eggnog
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 6cfba92caa93c751adde10134d7f3568a7fadfb86b953b5a97baceebe23d9c99

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('r-eggnog', max_pin="x.x") }}

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.46.0
    - bioconductor-iranges >=2.34.0
    - bioconductor-s4vectors >=0.38.0
    - r-acidbase >=0.7.1
    - r-goalie >=0.7.3
    - r-pipette >=0.14.1
  run:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.46.0
    - bioconductor-iranges >=2.34.0
    - bioconductor-s4vectors >=0.38.0
    - r-acidbase >=0.7.1
    - r-goalie >=0.7.3
    - r-pipette >=0.14.1

test:
  commands:
    - $R -e "library('EggNOG')"

about:
  home: https://r.acidgenomics.com/packages/eggnog/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: EggNOG database annotations.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
