{% set name = "minimod" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/warp9seq/minimod/releases/download/v{{ version }}/minimod-v{{ version }}-release.tar.gz
  sha256: 7bf5ebff9a94cf5fe43d326937b09de68d861ebcb37e9e3c3990d2c6d7a3e20e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('minimod', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
    - wget
  run:
    - zlib

test:
  commands:
    - minimod --help
    - minimod --version

about:
  home: https://github.com/warp9seq/minimod
  license: MIT
  license_file: LICENSE
  summary: 'A bioinformatics tool for viewing and calculating base modification frequencies from BAM files'

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
