{% set name = "tir-learner4" %}
{% set version = "1.0" %}
{% set sha256 = "6f0f5725476576ae224211e7e11605cc7ddeb42a99cae28a02cedebb79cdac40" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/KGerhardt/TIR-Learner/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('tir-learner4', max_pin='x') }}

requirements:
  run:
    - python >=3.9,<3.13
    - numpy
    - pyfastx
    - pywfa
    - keras
    - pytorch
    - genometools-genometools
    - genericrepeatfinder
    - blast
    - pigz

test:
  commands:
    - tirlearner4 --help

about:
  home: https://github.com/KGerhardt/TIR-Learner
  summary: "Accelerated tool for identifying TIR transposable elements"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  dev_url: https://github.com/KGerhardt/TIR-Learner
  doc_url: https://github.com/KGerhardt/TIR-Learner/blob/main/README.md
