{% set name = "bactopia" %}
{% set version = "4.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

source:
  url: https://github.com/bactopia/bactopia/archive/v{{version}}.tar.gz
  sha256: 81e194a05b826edac6df8faca5df268b7e5c0cf0697d3c2eb03bdd52d8241c00

requirements:
  run:
    - bactopia-py >=2.1.6
    - conda >=25
    - coreutils
    - mamba >=2
    - nextflow >=26
    - nf-test
    - python >3.9,<3.14
    - sed
    - wget
    - importlib-metadata <5
    - openpyxl

test:
  commands:
    - "bactopia --version"
    - "bactopia prepare"
    - "bactopia search"

about:
  home: https://bactopia.io/
  license: MIT
  license_file: LICENSE
  summary: Bactopia is a flexible pipeline for complete analysis of bacterial genomes.
  dev_url: https://github.com/bactopia/bactopia/

extra:
  recipe-maintainers:
    - rpetit3
  identifiers:
    - biotools:bactopia
    - doi:10.1128/mSystems.00190-20
