*** Makefile	2018-10-02 09:49:04.550508012 +0200
--- MakefileConda	2018-10-02 10:42:21.608584390 +0200
***************
*** 1,10 ****
- # Use version 4.9 of g++
- 
- # Set dependencies, s.t. make detects changes in header files.
- %.o: %.cc %.h
- 	g++ -c $^
- 
- CXX=g++
  CC=$(CXX)
  
  # Set this to include SeqAn libraries, either system wide
--- 1,3 ----
***************
*** 14,21 ****
  CXXFLAGS+=-I$(SEQAN_LIB) -DSEQAN_HAS_ZLIB=1 -std=c++14 -DSEQAN_DISABLE_VERSION_CHECK
  LDLIBS=-lz -lpthread
  
! DATE=on 2018-10-01
! VERSION=1.0.1
  CXXFLAGS+=-DDATE=\""$(DATE)"\" -DVERSION=\""$(VERSION)"\"
  
  # Enable warnings
--- 7,14 ----
  CXXFLAGS+=-I$(SEQAN_LIB) -DSEQAN_HAS_ZLIB=1 -std=c++14 -DSEQAN_DISABLE_VERSION_CHECK
  LDLIBS=-lz -lpthread
  
! DATE=on 2018-10-01 16:57:32
! VERSION=1.0.1-cb5783f
  CXXFLAGS+=-DDATE=\""$(DATE)"\" -DVERSION=\""$(VERSION)"\"
  
  # Enable warnings
***************
*** 30,43 ****
  all: CXXFLAGS+=-O3 -DSEQAN_ENABLE_TESTING=0 -DSEQAN_ENABLE_DEBUG=0
  all: popdel
  
- .PHONY: profiling
- profiling: CXXFLAGS+=-g -O3 -DSEQAN_ENABLE_TESTING=0 -DSEQAN_ENABLE_DEBUG=1
- profiling: popdel
- 
- .PHONY: debug
- debug: CXXFLAGS+=-g -O0 -DSEQAN_ENABLE_TESTING=0 -DSEQAN_ENABLE_DEBUG=1
- debug: popdel
- 
  PREFIX = /usr/local
  .PHONY: install
  install: popdel
--- 23,28 ----
