diff --git a/makefile b/makefile
index 8bff87b..94d8c8d 100644
--- a/makefile
+++ b/makefile
@@ -1,5 +1,5 @@
 CXX = g++
-CXXFLAGS = -g -Wall -O3
+CXXFLAGS = -g -Wall -O3 -I$(PREFIX)/include -L$(PREFIX)/lib
 LINKFLAGS = -lz -lpthread
 DEBUG=
 OBJECTS = BinaryStore.o GraphUtil.o FringeLine.o KmerUtil.o GraphTraversal.o Utility.o ReadsParsing.o LargeInt.o
