{% set name = "alignoth" %}
{% set version = "1.10.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/alignoth/alignoth/archive/v{{ version }}.tar.gz
  sha256: 1837f257caae3607f6c7bf3f34f93c8b43d2b43c32875484982542c4fd659bc2

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('alignoth', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - clangdev <22
    - pkg-config
    - make
    - cmake
  host:
    - libcblas
    - libcurl
    - openssl

test:
  commands:
    - alignoth --help

about:
  home: "https://alignoth.github.io"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A tool for creating alignment plots from bam files."
  dev_url: "https://github.com/alignoth/alignoth"
  doc_url: "https://github.com/alignoth/alignoth/blob/v{{ version }}/README.md"

extra:
  recipe-maintainers:
    - fxwiegand
    - johanneskoester
  additional-platforms:
    - linux-aarch64
    - osx-arm64
