{% set name = "dist2mst-rs" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/genpat-it/dist2mst-rs/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1331fc3f46e60f27fba3c2213ed266e510f8abdc50a5b1f99f22410df671aa2d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - {{ stdlib('c') }}

test:
  commands:
    - dist2mst --version

about:
  home: https://github.com/genpat-it/dist2mst-rs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Ultra-fast Minimum Spanning Tree construction from distance matrices (Rust)"
  dev_url: https://github.com/genpat-it/dist2mst-rs

extra:
  recipe-maintainers:
    - andreaderuvo
