#!/bin/sh
#
# Run the development version of dbcan from the current directory.
# This script is necessary since this software has been packaged,
# which means it expects to find its data files under the Hotpep module.

PATH=.:$PATH
export PATH

PYTHONPATH=$PWD:$PYTHONPATH
export PYTHONPATH

exec run_dbcan.py "$@"
