{% set version = "0.1.7" %}

package:
  name: turboani
  version: {{ version }}

source:
  url: https://github.com/jianshu93/turboani/archive/v{{ version }}.tar.gz
  sha256: f700837d89859206b279d16275e0c7639d28b0d09d5d4291f29c6526a27ebe1d

build:
  number: 0
  run_exports:
      - {{ pin_subpackage('turboani', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - pkg-config
    - make
    - cmake
  host:
    # Only needed on macOS (any arch) and Linux aarch64
    - fontconfig
    - freetype
    - expat  # [linux]
  run:
    - fontconfig
    - freetype

test:
  commands:
    - turboani -h
    - fastani -h

about:
  home: "https://github.com/jianshu93/turboani"
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: "TurboANI is a super fast homology-aware average nucleotide identity estimation algorithm at unprecedented scale"
  dev_url: "https://github.com/jianshu93/turboani"
  doc_url: "https://github.com/jianshu93/turboani/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - osx-arm64
    - linux-aarch64 
  recipe-maintainers:
   - jianshu93
