{% set name = "GFAffix" %}
{% set version = "0.2.2" %}
{% set sha256 = "c92769443999780cca9ed1b9a9b4f6444a97200aef2178c335c4d7623abd4708" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/codialab/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x.x", allow_no_other_outputs=True) }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cmake
    - make

test:
  commands:
    - gfaffix --help

about:
  home: https://github.com/codialab/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "GFAffix identifies and collapses walk-preserving shared affixes in variation graphs" 
  dev_url: https://github.com/codialab/{{ name|lower }}


extra:
  additional-platforms:
    - osx-arm64
    - linux-aarch64
  recipe-maintainers:
    - danydoerr
