{% set name = "bio" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bio-{{ version }}.tar.gz
  sha256: 5c01920d842fdc7a15212c1af50296db30fa76a3bd3597f8c65724b294557937

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage('bio', max_pin="x") }}

requirements:
  host:
    - python >=3.10,<3.15
    - hatchling
    - pip
  run:
    - python >=3.10,<3.15
    - biopython >=1.80
    - requests
    - tqdm
    - mygene
    - pandas
    - pooch
    - gprofiler-official

test:
  imports:
    - biorun
  commands:
    - pip check
    - bio 2>&1 | grep '^bio'

about:
  home: https://github.com/ialbert/bio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Command-line utilities to make bioinformatics explorations more enjoyable."
  dev_url: https://github.com/ialbert/bio
