{% set name = "metadmg" %}
{% set version = "0.5.0" %}
{% set sha256 = "7dc16550035fc42fe0b2c5e90a5b70d32b50787f80f0c1ea168f919078b2e143" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/metaDMG-dev/metaDMG-cpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - pkg-config
  host:
    - htslib
    - gsl
    - zlib

test:
  commands:
    - metaDMG-cpp >/dev/null 2>&1
    - metaDMG-cpp getdamage  >/dev/null 2>&1 
    - metaDMG-cpp lca > /dev/null 2>&1
    - compressbam  > /dev/null 2>&1 
    - extract_reads > /dev/null 2>&1

about:
  home: "https://github.com/metaDMG-dev/metaDMG-cpp"
  license: "GPL-3.0-or-later, MIT"
  license_family: "GPL3"
  license_file: "{{ RECIPE_DIR }}/gpl-3.0.txt"
  summary: "metaDMG-cpp: fast and efficient method for estimating mutation and damage rates in ancient DNA data."
  dev_url: "https://github.com/metaDMG-dev/metaDMG-cpp"
  doc_url: "https://github.com/metaDMG-dev/metaDMG-cpp/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - ANGSD
    - fgvieira
  identifiers:
    - doi:10.1101/2022.12.06.519264
