--- src/Makefile	2014-04-15 04:37:16.000000000 +0000
+++ src/Makefile.new	2017-03-02 22:43:31.155687817 +0000
@@ -1,5 +1,5 @@
 CC=             gcc
-CFLAGS=         -O3 -fomit-frame-pointer -static
+CFLAGS=         -O3 -fomit-frame-pointer
 #CFLAGS=         -O3 -g -D_DEBUG
 DFLAGS= 
 
@@ -31,7 +31,7 @@
 endif
 INCLUDES=	-Iinc
 SUBDIRS=        . 
-LIBPATH=	
+LIBPATH= -L${PREFIX}/lib	
 LIBS=      	-pthread -lm -lrt -lbam -lz -L./inc
 EXTRA_FLAGS=
 
