{% set name = "negspy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/negspy-{{ version }}.tar.gz
  sha256: 2dc5e1dfb9725c8364bc6cd3d16a0a761575098261f391ccae773f3d04fc6d8e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - negspy
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/pkerpedjiev/negspy"
  summary: Python NGS tools
  license: MIT
  dev_url: "https://github.com/pkerpedjiev/negspy"
  doc_url: "https://github.com/pkerpedjiev/negspy?tab=readme-ov-file#readme"
