{% set version = "0.16.0" %}

package:
  name: alevin-fry
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("alevin-fry", max_pin="x.x") }}

source:
  url: https://github.com/COMBINE-lab/alevin-fry/releases/download/v{{ version }}/source.tar.gz
  sha256: 638181c7ab52613c7bd0ce099d27e72da05a2cb235b55012d5ac2b35209f0f8b
  #patches:
  #  - use-libradicl-0.8.2.patch

requirements:
  build:
    - {{ compiler('rust') }} 
    - cmake
    - autoconf
    - make
    - {{ compiler('cxx') }}
    - pkg-config
  host:
  run:

test:
  commands:
    - alevin-fry --help

about:
  home: https://github.com/COMBINE-lab/alevin-fry
  license: BSD 3-Clause
  license_file: LICENSE
  summary: alevin-fry is a tool for the efficient processing of single-cell data based on RAD files produced by alevin

extra:
  skip-lints: 
    - compiler_needs_stdlib_c
  additional-platforms:
    - linux-aarch64
    - osx-arm64
