--- makefile.old	2022-10-03 01:29:21.457600256 -0500
+++ makefile	2022-10-03 01:31:37.547157385 -0500
@@ -1,17 +1,12 @@
-all: phist matcher subsystem
-
-ZLIB_DIR=./kmer-db/libs
+all: phist matcher
 
 phist:  utils/phist.cpp
-	g++ -std=c++11 -O3 utils/phist.cpp -o utils/phist
+	$(CXX) -std=c++11 -O3 utils/phist.cpp -o utils/phist
 
 matcher: utils/matcher.cpp utils/input_file.cpp
-	g++ -std=c++11 -o utils/matcher -I${ZLIB_DIR} -O3 utils/matcher.cpp utils/input_file.cpp -lz
-
-subsystem: 
-	$(MAKE) -C kmer-db
+	$(CXX) -std=c++11 -o utils/matcher -I${PREFIX}/include -I${ZLIB_DIR} -O3 utils/matcher.cpp utils/input_file.cpp -lm ${PREFIX}/lib/libz.a
 
 clean:
-	$(MAKE) clean -C kmer-db
-	-rm utils/phist
-	-rm utils/matcher  
+	make clean
+	rm utils/phist
+	rm utils/matcher  
