{% set version = '4.5-1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-devemf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/devEMF_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/devEMF/devEMF_{{ version }}.tar.gz
  sha256: cbb0f832dd59cea7c546ad0cdec100f49a7310694b3b32ef1c188bfa19dcf8e7

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - fontconfig  # [linux]
    - zlib  # [linux]
  run:
    - r-base

test:
  commands:
    - $R -e "library('devEMF')"           # [not win]
    - "\"%R%\" -e \"library('devEMF')\""  # [win]

about:
  home: https://github.com/plfjohnson/devEMF
  license: GPL-3.0-only
  summary: Output graphics to EMF+/EMF.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: devEMF
# Type: Package
# Title: EMF Graphics Output Device
# Version: 4.5-1
# Date: 2025-03-24
# Authors@R: person(given = "Philip", family = "Johnson", role = c("aut", "cre"), email = "plfj@umd.edu", comment = c(ORCID = "0000-0001-6087-7064"))
# Depends: R (>= 2.10.1)
# SystemRequirements: fontconfig or zlib (only needed for platforms other than modern OSX and Windows)
# Description: Output graphics to EMF+/EMF.
# License: GPL-3
# URL: https://github.com/plfjohnson/devEMF
# BugReports: https://github.com/plfjohnson/devEMF/issues
# NeedsCompilation: yes
# Packaged: 2025-03-24 15:09:00 UTC; pjohnson
# Author: Philip Johnson [aut, cre] (<https://orcid.org/0000-0001-6087-7064>)
# Maintainer: Philip Johnson <plfj@umd.edu>
# Repository: CRAN
# Date/Publication: 2025-03-24 16:20:01 UTC
