{% set name = "selenzy_wrapper" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/selenzy-wrapper/archive/{{ version }}.tar.gz
  sha256: d4289dce74f2792c4f22c784b69de731ed5518a19b76d5f2c14d578e6819926a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.7,<3.10
    - pip
    - setuptools
  run:
    - python >=3.7,<3.10
    - biopython
    - brs_utils <=1.24.2
    - emboss
    - rptools <=6.0.2
    - pandas
test:
  source_files:
    - tests/
  imports:
    - selenzy_wrapper

about:
  home: https://github.com/brsynth/selenzy-wrapper
  summary: Python wrapper of selenzy tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ramez17khaled
    - breakthewall
    - kenza12
