{% set name = "correlationplus" %} 
{% set version = "0.2.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: git checkout -b update-correlationplus-0.2.x  # use your new version

build:
  number: 0
  noarch: python
  entry_points:
    - correlationplus=correlationplus.scripts.correlationplus:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v
  run_exports:
    - {{ pin_subpackage('correlationplus', max_pin="x.x") }}

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - networkx
    - numpy
    - prody
    - mdanalysis
    - numba
    - python
    - scipy

test:
  imports:
    - correlationplus
    - correlationplus.scripts
  commands:
    - correlationplus --help

about:
  home: "https://github.com/tekpinar/correlationplus"
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: "A Python package to calculate, visualize and analyze dynamical correlations of proteins."
  doc_url: https://github.com/tekpinar/correlationplus
  dev_url: https://github.com/tekpinar/correlationplus

extra:
  recipe-maintainers:
    - bneron
    - tekpinar