cmake -B build -DCMAKE_C_FLAGS="-msse4.2" -DCMAKE_CXX_FLAGS="-msse4.2" -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_C_STANDARD=11 -DCMAKE_C_STANDARD_REQUIRED=ON
make -C build VERBOSE=1
make -C build install
