{% set name = "scinexus" %}
  {% set version = "2026.4.25b0" %}

  package:
    name: {{ name|lower }}
    version: {{ version }}

  source:
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ae73a71a0d955f0aed58dd43c973c28b053e6c3449a38b27abe9302e176b9943

  build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
    run_exports:
      - {{ pin_subpackage(name, max_pin=None) }}

  requirements:
    host:
      - python >=3.11
      - pip
      - hatchling
    run:
      - python >=3.11
      - charset-normalizer
      - citeable
      - scitrack
      - tqdm
      - typeguard

  test:
    imports:
      - scinexus

  about:
    home: https://github.com/cogent3/scinexus
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Python framework for rapid development of data processing applications
    doc_url: https://scinexus.readthedocs.io
    dev_url: https://github.com/cogent3/scinexus

  extra:
    recipe-maintainers:
      - GavinHuttley