{% set version = "0.14.0" %}

package:
  name: taxopy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/taxopy/taxopy-{{ version }}.tar.gz
  sha256: c39c4c4330b322f2e0505de45c2980a53eb945f8129fc679dd655a093042dbe6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.5

test:
  imports:
    - taxopy
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/taxopy/
  summary: A Python package for obtaining complete lineages and the lowest common ancestor (LCA) from a set of taxonomic identifiers.
  doc_url: https://apcamargo.github.io/taxopy
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hellojung0810
