{% set version = "3.6.4" %}

package:
  name: submission-excel2xml
  version: {{ version }}

source:
  url: https://github.com/ddbj/submission-excel2xml/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d00701114b0985547747e0e69054d46f8606bb20f76cd3e4318a4e8e60b3e842 

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('submission-excel2xml', max_pin="x") }}

requirements:
  build:
    - make
    - compilers
  host:
    - ruby <4
    - libxml2
  run:
    - ruby <4
    - rb-nokogiri  # [x86_64]

test:
  commands:
    # - excel2xml_dra -h
    # - excel2xml_jga -h
    - excel2xml_dra -a example -i 0001 -p PRJDB7252  ${XDG_DATA_HOME}/submission-excel2xml/example/example-0001_dra_metadata.xlsx && validate_meta_dra -a example -i 0001
    - excel2xml_dra -a example -i 0002 -p PRJDB7252 -c "National Institute of Genetics" ${XDG_DATA_HOME}/submission-excel2xml/example/example-0002_dra_metadata.xlsx && validate_meta_dra -a example -i 0002
    - excel2xml_jga -j JSUB999999 ${XDG_DATA_HOME}/submission-excel2xml/example/JSUB999999_jga_metadata.xlsx && validate_meta_jga -j JSUB999999

about:
  home: "https://github.com/ddbj/submission-excel2xml"
  license: "Apache-2.0"
  license_family: APACHE
  license_file: "LICENSE.txt"
  summary: "Generate DRA metadata XML files from Excel spreadsheet."
  dev_url: "https://github.com/ddbj/submission-excel2xml"
  doc_url: "https://github.com/ddbj/submission-excel2xml/blob/v{{ version }}/README.md"
