#!/usr/bin/env python

from quast_libs import qconfig
from quast_libs.log import get_logger
from quast_libs.run_busco import download_all_db, download_augustus

logger = get_logger(qconfig.LOGGER_DEFAULT_NAME)
logger.set_up_console_handler()

download_augustus(logger)
download_all_db(logger)
