#!/usr/bin/env python

from quast_libs import qconfig
from quast_libs.log import get_logger
from quast_libs.search_references_meta import download_blastdb

logger = get_logger(qconfig.LOGGER_DEFAULT_NAME)
logger.set_up_console_handler()

download_blastdb(logger)
