--- src/Makefile	2018-10-13 21:25:02.000000000 +0200
+++ src/Makefile	2018-10-13 21:25:17.000000000 +0200
@@ -1,4 +1,4 @@
-CXX = g++
+#CXX = g++
 CXXFLAGS = -Wall -fopenmp -O3
 PROGS = db_sort set_lcas classify make_seqid_to_taxid_map db_shrink kmer_estimator
