{% set version = "1.1.0" %}

package:
  name: ecolityper-mlst-data
  version: {{ version }}

source:
  url: https://github.com/bbeckley-hub/EcoliTyper/releases/download/v{{ version }}/ecolityper-mlst-data-v{{ version }}.tar.gz
  sha256: 17c8c75c58ddd5499bfb164b54087c57e29d4643acb3bf340d9df40945589ac2

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage('ecolityper-mlst-data', max_pin="x") }}

requirements:
  run:
    - python

test:
  commands:
    - test -f $SP_DIR/ecoliTyper/modules/mlst_module/db/scheme_species_map.tab

about:
  home: https://github.com/bbeckley-hub/EcoliTyper
  license: MIT
  summary: 'MLST database for ecoliTyper (E. coli)'
