{% set version = "0.5.1" %}
{% set name = "nohuman" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mbhall88/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e0840bf16f23b8269f08884b32a9d905ce1af9dd35cf455b5a85364c84492a7d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('nohuman', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - xz
  run:
    - kraken2 =2

test:
  commands:
    - nohuman --help
    - nohuman --check

about:
  home: "https://github.com/mbhall88/nohuman"
  license: MIT
  license_family: MIT
  license_file: 
    - LICENSE
    - THIRDPARTY.yml
  summary: "Remove human reads from a sequencing run."
  dev_url: "https://github.com/mbhall88/nohuman"
  doc_url: "https://github.com/mbhall88/nohuman/blob/{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1093/gigascience/giae010
  skip-lints:
    - version_constraints_missing_whitespace  # TODO: remove once resolved here: https://github.com/bioconda/bioconda-utils/pull/1044
  recipe-maintainers:
    - mbhall88
