{% set name = "fxsplit" %}
{% set version = "0.0.3" %}

package:
 name: {{ name }}
 version: {{ version }}

source:
 url: https://github.com/alejandrogzi/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
 sha256: eb7d130c45c7b557dfe986e870b37b8bcb853b24f1698667a7ad6b3b0992bca6

build:
 number: 0
 run_exports:
    - {{ pin_subpackage('fxsplit', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config

test:
 commands:
   - fxsplit --help
   - fxsplit --version

about:
 home: https://github.com/alejandrogzi/fxsplit
 license: Apache-2.0
 license_family: APACHE
    - THIRDPARTY.yml
 summary: "split FASTX (and 2bit) into N chunks/files/headers"

extra:
  recipe-maintainers:
    - alejandrogzi
  dev_url: https://github.com/alejandrogzi/fxsplit
