{% set version = "3.0.1" %}
{% set sha256 = "51c237092169114e813e6ab43393f2fec630ee4289629d24da3878c43b140bd6" %}

package:
  name: scaffold_builder
  version: '{{ version }}'

source:
  url: https://github.com/metageni/Scaffold_builder/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  run_exports:
    - {{ pin_subpackage('scaffold_builder', max_pin="x") }}

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61
    - wheel
  run:
    - python >=3.8
    - click >=8.0
    - mummer

test:
  commands:
    - scaffold_builder --help

about:
  home: https://github.com/metageni/Scaffold_builder
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Scaffold_builder: Combining de novo and reference-guided assembly with Scaffold_builder.'
  dev_url: https://github.com/metageni/Scaffold_builder
