{% set version = "3.0.1" %}
{% set sha256 = "51c237092169114e813e6ab43393f2fec630ee4289629d24da3878c43b140bd6" %}

package:
  name: scaffold_builder
  version: '{{ version }}'

source:
  url: https://github.com/metageni/Scaffold_builder/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'
  patches:
    - patch

build:
  noarch: python
  number: 0

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3
    - mummer

test:
  commands:
    - scaffold_builder.py

about:
  home: http://edwards.sdsu.edu/scaffold_builder
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Scaffold_builder: Combining de novo and reference-guided assembly with Scaffold_builder.'
  dev_url: https://github.com/metageni/Scaffold_builder
