#!/bin/bash

## Add safestringlib external dependency
## It does not exist by default in the source code zip file auto-generated by GitHub
rm -rf $SRC_DIR/ext/safestringlib/
cd $SRC_DIR/ext/
git clone https://github.com/intel/safestringlib
cd $SRC_DIR/ext/safestringlib/
git checkout 245c4b8 ## Ensure updates to safestringlib do not break compilation

## Fix error "implicit declaration of function" when compiling safestringlib
## Using -i.bak to make file backup and $'...' C-style escape syntax prevents sed command failing with MacOSX
sed -i.bak $'1i\\\n#include <stdlib.h>\n' $SRC_DIR/ext/safestringlib/safeclib/abort_handler_s.c
sed -i.bak $'1i\\\n#include <ctype.h>\n'  $SRC_DIR/ext/safestringlib/safeclib/strcasestr_s.c
sed -i.bak $'1i\\\n#include <ctype.h>\n'  $SRC_DIR/ext/safestringlib/safeclib/strcasecmp_s.c

## Compile
make -C $SRC_DIR

## Move binary to final location
mkdir -p $PREFIX/bin
mv $SRC_DIR/bwa-plus* $PREFIX/bin
chmod +x $PREFIX/bin/bwa-plus*
