#!/bin/bash

cd "${SRC_DIR}"
mv bwa-plus-bwa-plus-v${PKG_VERSION}/ bwa-plus/

## Add safestringlib external dependency
## It does not exist by default in the source code zip file auto-generated by GitHub
cd bwa-plus/ext/
rm -rf safestringlib/
git clone https://github.com/intel/safestringlib
cd safestringlib/
git checkout 245c4b8 ## Ensure updates to safestringlib do not break compilation

## Fix error "implicit declaration of function" when compiling safestringlib
sed -i "1i#include <stdlib.h>" bwa-plus/ext/safestringlib/safeclib/abort_handler_s.c
sed -i "1i#include <ctype.h>"  bwa-plus/ext/safestringlib/safeclib/strcasestr_s.c
sed -i "1i#include <ctype.h>"  bwa-plus/ext/safestringlib/safeclib/strcasecmp_s.c

## Compile
make -C bwa-plus/

## Move binary to final location and clean up
mkdir -p $PREFIX/bin
chmod +x bwa-plus/bwa-plus*
mv bwa-plus/bwa-plus* $PREFIX/bin
rm -r bwa-plus/

## Add aliases
for binary in /usr/local/bin/bwa-plus*; do
    ln -sf $binary $(echo $binary | sed "s/bwa-plus/bwa-mem2/")
done
