#!/bin/bash

cd "${SRC_DIR}"

## Add safestringlib external dependency
## It does not exist by default in the source code zip file auto-generated by GitHub
rm -rf ext/safestringlib/
git clone https://github.com/intel/safestringlib
cd ext/safestringlib/
git checkout 245c4b8 ## Ensure updates to safestringlib do not break compilation

## Fix error "implicit declaration of function" when compiling safestringlib
sed -i "1i#include <stdlib.h>" ext/safestringlib/safeclib/abort_handler_s.c
sed -i "1i#include <ctype.h>"  ext/safestringlib/safeclib/strcasestr_s.c
sed -i "1i#include <ctype.h>"  ext/safestringlib/safeclib/strcasecmp_s.c

## Compile
make

## Move binary to final location and clean up
mkdir -p $PREFIX/bin
chmod +x bwa-plus*
mv bwa-plus* $PREFIX/bin

## Add aliases
for binary in $PREFIX/bin/bwa-plus*; do
    ln -sf $binary $(echo $binary | sed "s/bwa-plus/bwa-mem2/")
done
