package:
  name: metastrand
  version: "0.1.1"

source:
  url: https://gitlab.com/mpust/metastrand/-/archive/v0.1.1/metastrand-v0.1.1.tar.gz
  sha256: edb49260149298c4f6a64d6a003bb5d506b7844c797af459cbcfebbe6d7aa29c

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('metastrand', max_pin="x.x") }}

requirements:
  run:
    - python >=3.9
    - pandas
    - pysam
    - numpy
    - scipy
    - bwa
    - samtools >=1.23
    - subread >=2.1.1
    - htslib >=1.23
    - bedtools >=2.31.1
    - sambamba >=1.0.1
    - bbmap >=39.52

about:
  home: "https://gitlab.com/mpust/metastrand"
  license: MIT
  license_file: LICENSE
  summary: "Metastrand: Making sense of antisense"

extra:
  recipe-maintainers:
    - mpust

test:
  commands:
    - which metastrand
    - metastrand --help
    - test -f "$PREFIX/share/metastrand/config.template.txt"
    - test -f "$PREFIX/share/metastrand/config.test.txt"