{% set name = "sincei" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 054f5bb6fd7650164f17aacb2438af09cafd2491889b55b01b45bb0e449e0aa7

build:
  number: 0
  noarch: python
  entry_points:
    - sincei = sincei.sincei:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  run_exports:
    - {{ pin_subpackage("sincei", max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - umap-learn
    - pandas
    - deeptools
    - scanpy
    - anndata
    - loompy
    - gensim
    - networkx
    - leidenalg
    - python-igraph
    - session-info
    - pytorch
    - importlib-metadata

test:
  imports:
    - sincei
  commands:
    - sincei -h

about:
  home: https://github.com/bhardwaj-lab/sincei
  license: MIT
  license_file: LICENCE.txt
  summary: A user-friendly toolkit for QC, counting, clustering and plotting of single-cell (epi)genomics data.

extra:
  identifiers:
    - biotools:sincei
    - doi:10.5281/zenodo.8105536
