diff --git a/src/main.mk b/src/main.mk
index 5f33ff4..25c2285 100644
--- a/src/main.mk
+++ b/src/main.mk
@@ -155,6 +155,7 @@


 SRC_INCDIRS  := . \
+                utility/src \
                 stores \
                 stores/libsnappy \
                 alignment \
