diff --git a/src/main.mk b/src/main.mk
index 5f33ff4..25c2285 100644
--- a/src/main.mk
+++ b/src/main.mk
@@ -147,23 +147,22 @@
                 utility/src/system/libbacktrace/posix.c \
                 utility/src/system/libbacktrace/print.c \
                 utility/src/system/libbacktrace/simple.c \
                 utility/src/system/libbacktrace/sort.c \
                 utility/src/system/libbacktrace/state.c \
                 utility/src/system/libbacktrace/unknown.c
 endif



 SRC_INCDIRS  := . \
-                utility/src \
                 stores \
                 stores/libsnappy \
                 alignment \
                 utgcns/libNDalign \
                 utgcns/libcns \
                 utgcns/libpbutgcns \
                 utgcns/libNDFalcon \
                 utgcns/libboost \
                 overlapInCore \
                 overlapInCore/liboverlap

