{% set name = "PlasmidCommunity" %} 
{% set version = "1.0.1" %}

package:
  name: plasmidcommunity
  version: 1.0.1

source:
  url: "https://github.com/wuxinmiao5/PlasmidCommunity/archive/refs/tags/v1.0.1.tar.gz"
  sha256: "aef46a05044d7b6d0eb4539aed0893c2114da4e9f6c9c7687fbcec2f8f21b961"

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p ${PREFIX}/bin
    - cp ${SRC_DIR}/PlasmidCommunity/plasmidCommunity.sh ${PREFIX}/bin/
    - chmod +x ${PREFIX}/bin/plasmidCommunity.sh
  run_exports:  
    - r-base

requirements:
  host:
    - r-base >=4.3.3
  run:
    - util-linux
    - bash
    - r-base >=4.3.3
    - r-tidyverse >=2.0.0
    - r-readr >=2.1.5
    - r-readxl >=1.4.3
    - bioconductor-biostrings >=2.70.3
    - r-seqinr >=4.2.36
    - prodigal >=2.6.3
    - fastani >=1.33
    - blast >=2.1.2

test:
  commands:
    - plasmidCommunity.sh -h

about:
  home: "https://github.com/wuxinmiao5/PlasmidCommunity"
  license: GPL-3.0
  summary: "PlasmidCommunity: A Software Suite for Klebsiella pneumoniae Plasmid Classification Framework, Assignment, and Transmission Risk Prediction"
  doc_url: "https://github.com/wuxinmiao5/PlasmidCommunity/blob/main/README.md"
