--- a/Makefile
+++ b/Makefile
@@ -12,9 +12,8 @@ exec_prefix = $(prefix)
 bindir ?= $(exec_prefix)/bin
 
 # Flags
-CXX=g++
-CXXFLAGS += -isystem ${EBROOTHTSLIB} -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive
-LDFLAGS += -L${EBROOTHTSLIB} -L${EBROOTHTSLIB}/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time 
+CXXFLAGS += -isystem ${PREFIX} -isystem ${BOOST_ROOT} -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive
+LDFLAGS += -L${PREFIX}/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time
 
 # Flags for parallel computation
 ifeq (${PARALLEL}, 1)
@@ -27,7 +26,7 @@ endif
 ifeq (${STATIC}, 1)
 	LDFLAGS += -static -static-libgcc -pthread -lhts -lz -llzma -lbz2
 else
-	LDFLAGS += -lhts -lz -llzma -lbz2 -Wl,-rpath,${EBROOTHTSLIB}
+	LDFLAGS += -lhts -lz -llzma -lbz2
 endif
 
 # Flags for debugging, profiling and releases
@@ -50,14 +49,14 @@ SOURCES = $(wildcard src/*.h) $(wildcard src/*.cpp)
 
 # Targets
 BUILT_PROGRAMS = src/delly
-TARGETS = ${SUBMODULES} ${BUILT_PROGRAMS}
+TARGETS = src/delly
 
 all:   	$(TARGETS)
 
 .htslib: $(HTSLIBSOURCES)
 	if [ -r src/htslib/Makefile ]; then cd src/htslib && make && make lib-static && cd ../../ && touch .htslib; fi
 
-src/delly: ${SUBMODULES} $(SOURCES)
+src/delly: $(SOURCES)
 	$(CXX) $(CXXFLAGS) $@.cpp -o $@ $(LDFLAGS)
 
 src/dpe: ${SUBMODULES} $(SOURCES)
@@ -69,7 +68,7 @@ install: ${BUILT_PROGRAMS}
 
 clean:
 	if [ -r src/htslib/Makefile ]; then cd src/htslib && make clean; fi
-	rm -f $(TARGETS) $(TARGETS:=.o) ${SUBMODULES}
+	rm -f $(TARGETS) $(TARGETS:=.o)
 
 distclean: clean
 	rm -f ${BUILT_PROGRAMS}
