{% set name = "gfatk" %}
{% set version = "0.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/tolkit/gfatk/archive/refs/tags/{{ version }}.tar.gz
  sha256: cc3e3e806ca6ff6938a24ce2c32e7c58ee331833baa4fbee38c6369b6ce0c3bc

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - gfatk --help

about:
  home: https://github.com/tolkit/gfatk
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Explore and linearise (plant organellar) GFA assembly graphs
  dev_url: https://github.com/tolkit/gfatk

extra:
  recipe-maintainers:
    - Euphrasiologist
  identifiers:
    - doi:10.5281/zenodo.22870219
  additional-platforms:
    - linux-aarch64
    - osx-arm64
