{% set version = "1.0.0" %}

package:
  name: kleboscope-mlst-data
  version: {{ version }}

source:
  url: https://github.com/bbeckley-hub/Kleboscope/releases/download/v{{ version }}-data/kleb_mlst_data-v{{ version }}.tar.gz
  sha256: 069603c1d5cbd09f4307abf0184b861ed5b5583b1e499b3291cfd3381a888113

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage('kleboscope-mlst-data', max_pin="x") }}

requirements:
  run:
    - python

test:
  commands:
    - test -f $SP_DIR/kleboscope/modules/kleb_mlst_module/db/scheme_species_map.tab

about:
  home: https://github.com/bbeckley-hub/Kleboscope
  license: MIT
  summary: 'MLST typing database for Kleboscope (K. pneumoniae)'
