--- Makefile	2012-11-03 17:11:06.000000000 +0000
+++ Makefile.new	2016-03-01 00:03:57.700408266 +0000
@@ -17,11 +17,11 @@
 export UTIL_DIR	= src/utils
 export CXX		= g++
 ifeq ($(DEBUG),1)
-export CXXFLAGS = -Wall -O0 -g -fno-inline -fkeep-inline-functions -D_FILE_OFFSET_BITS=64 -fPIC -DDEBUG -D_DEBUG
+export CXXFLAGS = -Wall -O0 -g -fno-inline -fkeep-inline-functions -D_FILE_OFFSET_BITS=64 -fPIC -DDEBUG -D_DEBUG -I${PREFIX}/include
 else
-export CXXFLAGS = -Wall -O2 -D_FILE_OFFSET_BITS=64 -fPIC
+export CXXFLAGS = -Wall -O2 -D_FILE_OFFSET_BITS=64 -fPIC -I${PREFIX}/include
 endif
-export LIBS		= -lz
+export LIBS		= -L${PREFIX}/lib -lz
 export BT_ROOT  = src/utils/BamTools/
 
 
