package:
  name: blastdbbuilder-gui
  version: "1.0.12"

source:
  url: https://pypi.io/packages/source/b/blastdbbuilder-gui/blastdbbuilder_gui-1.0.12.tar.gz
  sha256: d82a1b77ba075e3ba6638f4fbe7cf86c60eb4a9aa08652b09bb8ed890a0ca991

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=64
    - wheel
  run:
    - python >=3.9
    - blastdbbuilder >=1.0.5
    - customtkinter

test:
  imports:
    - blastdbbuilder_gui

about:
  home: https://github.com/asadprodhan/blastdbbuilder
  license: GPL-3.0-only
  summary: Graphical user interface for building customised BLASTn databases using blastdbbuilder

extra:
  recipe-maintainers:
    - asadprodhan
