***************
*** 1,4 ****
  PACKAGE_VERSION="0.1.11"
  CC=			gcc
  CFLAGS=		-g -Wall -O3 #-m64 #-arch ppc
  DFLAGS=		-D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -DPACKAGE_VERSION=\\\"${PACKAGE_VERSION}\\\"
--- 1,5 ----
  PACKAGE_VERSION="0.1.11"
+ LIBS = -lz
  CC=			gcc
  CFLAGS=		-g -Wall -O3 #-m64 #-arch ppc
  DFLAGS=		-D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -DPACKAGE_VERSION=\\\"${PACKAGE_VERSION}\\\"
***************
*** 11,19 ****
  					samtools/bam_sort.o samtools/sam_header.o samtools/bam_reheader.o samtools/kprobaln.o samtools/bam_cat.o
  
  PROG=		dwgsim dwgsim_eval
- INCLUDES=	-I.
- SUBDIRS=	samtools . 
- CLEAN_SUBDIRS=	samtools src
  LIBPATH=
  
  .SUFFIXES:.c .o
--- 12,20 ----
  					samtools/bam_sort.o samtools/sam_header.o samtools/bam_reheader.o samtools/kprobaln.o samtools/bam_cat.o
  
  PROG=		dwgsim dwgsim_eval
+ INCLUDES ="${PREFIX}/include"
+ SUBDIRS=	 . 
+ CLEAN_SUBDIRS=	 src
  LIBPATH=
  
  .SUFFIXES:.c .o
