{% set name = "sracha" %}
{% set version = "0.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/rnabioco/sracha-rs/archive/v{{ version }}.tar.gz
  sha256: 1b6664887202d64775136b04a2bee3f257853b42eeb0f5b2660076268e3ae01f

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('sracha', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - sracha --help

about:
  home: https://github.com/rnabioco/sracha-rs
  license: MIT
  license_file: LICENSE
  summary: Fast parallel SRA downloader and streaming FASTQ converter.
  dev_url: https://github.com/rnabioco/sracha-rs
  doc_url: https://github.com/rnabioco/sracha-rs#readme

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  skip-lints:
    - compiler_needs_stdlib_c
  recipe-maintainers:
    - jayhesselberth
