{% set version = "0.2.5" %}

package:
  name: r-canek
  version: '{{ version }}'

source:
  url: https://cran.r-project.org/src/contrib/Canek_{{ version }}.tar.gz
  sha256: 5e7f5e030baa324f82a494e155d28ce8d18f760c3103e4d2f9d3d8ff306c3fc7

build:
  number: 0
  noarch: generic
  run_exports:
    - '{{ pin_subpackage("r-canek", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-fnn
    - bioconductor-bluster
    - r-fpc
    - r-igraph
    - r-irlba
    - r-matrixstats
    - r-numbers
  run:
    - r-base
    - r-fnn
    - bioconductor-bluster
    - r-fpc
    - r-igraph
    - r-irlba
    - r-matrixstats
    - r-numbers

test:
  commands:
    - $R -e "library('Canek')"

about:
  home: https://martinloza.github.io/Canek/
  license: MIT
  license_file: LICENSE
  summary: 'Batch Correction of Single Cell Transcriptome Data'
  description: 'Non-linear/linear hybrid method for batch-effect correction that uses Mutual Nearest Neighbors (MNNs) to identify similar cells between datasets. Reference: Loza M. et al. (NAR Genomics and Bioinformatics, 2020) <doi:10.1093/nargab/lqac022>.'

extra:
  recipe-maintainers:
    - MartinLoza
