{% set version = "0.1.2" %}

package:
  name: neffy-cli
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("neffy-cli", max_pin="x.x") }}

source:
  url: https://github.com/Maryam-Haghani/NEFFy/archive/v{{ version }}.tar.gz
  sha256: 5a61acaae900aa4940b2e49c045a2b1667a8d596592ea83e3d83d31d9a91562e

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make

test:
  commands:
    - converter --help
    - neff --help

about:
  home: https://maryam-haghani.github.io/NEFFy
  license: GPL-3.0-only
  license_file: LICENSE.txt
  doc_url: https://maryam-haghani.github.io/NEFFy
  dev_url: https://github.com/Maryam-Haghani/NEFFy
  summary: NEFF calculator and MSA file converter

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
