{% set name = "alpharaw" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/MannLabs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c0875c47851257d7e3b9d6a14e9c70803e57ca11c016e12b4b0cde1e5b2cfe4a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  entry_points:
    - alpharaw = alpharaw.cli:run
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - click
    - pythonnet
    - h5py
    - numba
    - pandas
    - numpy
    - pyteomics
    - lxml
    - owlready2
    - alphabase >=1.5.0

test:
  imports:
    - alpharaw
  commands:
    - alpharaw --help

about:
  home: "https://github.com/MannLabs/alpharaw"
  summary: "An open-source Python package to unify raw MS data access and storage."
  description: |
    AlphaRaw provides unified access to raw mass spectrometry data from
    various instrument vendors, converting them to a standardized HDF5
    format for downstream analysis in the AlphaPept ecosystem.
  license: "Apache-2.0"
  license_family: APACHE
  license_file: "LICENSE.txt"
  dev_url: "https://github.com/MannLabs/alpharaw"

extra:
  recipe-maintainers:
    - jonasscheid
