package:
  name: molemap
  version: "1.4.3.1"

source:
  url: https://github.com/kehrlab/molemap/archive/refs/tags/v.1.4.3.1.tar.gz
  sha256: 6326d8b7559bf12664a349c840a51cee2309c05da34f50cc88f1de1618094bff

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('molemap', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx] 
    - make
    - libzlib
    - zlib-ng
    - zlib
  host:
    - zlib

test:
  commands:
    - molemap index -h

about:
  home: "https://github.com/kehrlab/molemap"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Ultra fast molecule mapping for linked- and long-read data."
  dev_url: "https://github.com/kehrlab/molemap"
