{% set name = "tidehunter" %}
{% set version = "1.5.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/yangao07/TideHunter/releases/download/v{{ version }}/TideHunter-v{{ version }}.tar.gz
  sha256: 14e697b3414a070afecf79b76496ae5e54dd829223c71876ca06f5b45ee31f3c

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('tidehunter', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - zlib

test:
  commands:
    - TideHunter --version | grep {{ version }}

about:
  home: https://github.com/yangao07/TideHunter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TideHunter: efficient and sensitive tandem repeat detection from noisy long reads using seed-and-chain'
  dev_url: https://github.com/yangao07/TideHunter
