{% set version = "26.04.5" %}
{% set sha256 = "2d88b16b8465ea99e83ae9df9cadfc9f5d06c1aea6e8376468eec65662cb3d9f" %}

package:
  name: nextflow
  version: {{ version }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('nextflow', max_pin="x.x") }}

source:
  url: https://github.com/nextflow-io/nextflow/releases/download/v{{ version }}/nextflow
  sha256: {{ sha256 }}

requirements:
  host:
    - openjdk >=17,<=24
    - coreutils          # [not win]
    - uutils-coreutils   # [win]
    - curl
  run:
    - openjdk >=17,<=24
    - coreutils          # [not win]
    - uutils-coreutils   # [win]
    - curl

test:
  commands:
    - nextflow help

about:
  home: "https://github.com/nextflow-io/nextflow"
  license: "Apache-2.0"
  summary: "A DSL for data-driven computational pipelines http://nextflow.io"

extra:
  recipe-maintainers:
    - pditommaso
    - bentsherman
    - ewels
    - mjsteinbaugh
