#!/bin/bash
mkdir build
cd build
## See INSTALL of gromacs distro
cmake .. \
  -DSHARED_LIBS_DEFAULT=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  -DGMX_PREFER_STATIC_LIBS=YES \
  -DGMX_BUILD_OWN_FFTW=OFF \
  -DGMX_DEFAULT_SUFFIX=ON \
  -DREGRESSIONTEST_DOWNLOAD=ON \
  -DGMX_MPI=OFF \
  -DGMX_GPU=ON \
  -DGMX_SIMD=SSE2 \
  -DGMX_USE_OPENCL=ON \
  -DCMAKE_PREFIX_PATH=$PREFIX \
  -DGMX_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_INSTALL_PREFIX=$PREFIX
make -j 8
make check
make install
