diff --git a/Makefile b/Makefile
index 2174509..f7b8646 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-CFLAGS=		-g -O3 -Wall -fno-strict-aliasing
+CFLAGS += -g -O3 -Wall -fno-strict-aliasing
 CPPFLAGS=
 INCLUDES=
 OBJS=
