diff --git a/Makefile b/Makefile
index 1cb880c..1c2283f 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-CFLAGS=		-O3 -Wall -fno-strict-aliasing
+CFLAGS +=		-O3 -Wall -fno-strict-aliasing
 CPPFLAGS=
 INCLUDES=
 OBJS=
