--- a/Makefile
+++ b/Makefile
@@ -12,7 +12,12 @@
 INCLUDE = include
 BINDIR := $(BUILD)/.o
 
-LDFLAGS := -pthread
+ifeq ($(origin LDFLAGS), undefined)
+    LDFLAGS := -pthread
+else
+    LDFLAGS := $(LDFLAGS) -pthread
+endif
+
 LIBS = -lz
 
 OBJS := main input reads
@@ -27,7 +32,7 @@
 all: head validate regenerate
 
 $(BINDIR)%: $(SOURCE)/%.cpp $(INCLUDE)/%.h | $(BINDIR)
-	$(CXX) $(CXXFLAGS) $(LDFLAGS) -c $(SOURCE)/$(notdir $@).cpp -o $@
+	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -c $(SOURCE)/$(notdir $@).cpp -o $@
 
 .PHONY: gfalibs
 gfalibs:
