diff --git a/Makefile b/Makefile
index 7ec8f12..d81d842 100644
--- a/Makefile
+++ b/Makefile
@@ -12,7 +12,11 @@ SOURCE = src
 INCLUDE = include
 BINDIR := $(BUILD)/.o
 
-LDFLAGS += -pthread
+ifeq ($(origin LDFLAGS), undefined)
+	LDFLAGS := -pthread
+else
+	LDFLAGS := $(LDFLAGS) -pthread
+endif
 LIBS = -lz -lcrypto -lhts
 
 OBJS := main input reads
@@ -27,7 +31,7 @@ head: $(BINS) gfalibs | $(BUILD)
 all: head validate regenerate
 
 $(BINDIR)%: $(SOURCE)/%.cpp $(INCLUDE)/%.h | $(BINDIR)
-	$(CXX) $(CXXFLAGS) -c $(SOURCE)/$(notdir $@).cpp -o $@
+	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -c $(SOURCE)/$(notdir $@).cpp -o $@
 
 .PHONY: gfalibs
 gfalibs:
