{% set name = "scfair" %}
{% set version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85cd6f9d2ae139dc08a5c31be54e2634afc839ea6f813a27080fede9ac2f02e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage('scfair', max_pin="x.x") }}

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61
  run:
    - python >=3.10
    - anndata >=0.10
    - numpy >=1.24
    - pandas >=2.0
    - scanpy >=1.10
    - scipy >=1.10
    - scikit-learn >=1.2
    - python-igraph >=0.10
    - scikit-misc >=0.3

test:
  imports:
    - scfair
    - scfair.pp

about:
  home: https://github.com/leelieber2025/scFair
  dev_url: https://github.com/leelieber2025/scFair
  doc_url: https://scfair.readthedocs.io
  summary: Fair highly variable gene selection for single-cell RNA-seq
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leelieber2025
