{% set name = "cryptkeeper" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptkeeper-{{ version }}.tar.gz
  sha256: 6ac7b12d935f4e4250d58dbfa31cd0db296e74c81b399c421bee3ee2ae4b75e7

build:
  entry_points:
    - cryptkeeper = cryptkeeper.cryptkeeper:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  number: 0
  run_exports:
     - {{ pin_subpackage("cryptkeeper", max_pin="x") }}

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - ostir
    - rhotermpredict
    - promotercalculator
    - bokeh
    - biopython
    - pandas

test:
  imports:
    - cryptkeeper
  commands:
    - cryptkeeper --help

about:
  home: https://github.com/barricklab/cryptkeeper
  summary: "A negative design tool for predicting and visualizing undesired gene expression"
  license: "GPL-3.0-only"
  license_file: LICENSE
  license_family: GPL3
  dev_url: https://github.com/barricklab/cryptkeeper

extra:
  recipe-maintainers:
    - croots
    - jeffreybarrick
