diff --git a/Makefile b/Makefile
index 05ff66a..9c03866 100644
--- a/Makefile
+++ b/Makefile
@@ -66,7 +66,7 @@ CXXFLAGS    ?= -Wall -Wextra -pedantic -mtune=native
 
 # These flags are required for the build to work.
 FLAGS        = -std=c++14 -Iunicycler/include -fPIC
-LDFLAGS      = -shared -lz
+LDFLAGS      += -shared -lz
 
 
 # Platform-specific stuff (for Seqan)
