{% set name = "scxmatch" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bionetslab/{{ name }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f6d0af58233a73d2b1ccbdee1263ffe27804f7e1a36d8db6594f06af1beb327

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - python >=3.9
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - anndata >=0.10.9
    - scanpy >=1.10.3,<2
    - scipy >=1.13.1,<2
    - graph-tool >=2.92,<3


test:
  imports:
    - scxmatch


about:
  summary: Python implementation for single-cell cross match test, an efficient implementation of Rosenbaum's test.
  license: MIT
  license_file: LICENSE
  home: https://github.com/bionetslab/scxmatch

extra:
  recipe-maintainers:
    - annmoel
