diff --git a/opt/dev/alfred/Makefile b/Makefile
index aaa52e5f7..644ae81f4 100644
--- a/opt/dev/alfred/Makefile
+++ b/Makefile
@@ -1,66 +1,20 @@
 DEBUG ?= 0
 STATIC ?= 0
 
-# Submodules
-PWD = $(shell pwd)
-EBROOTHTSLIB ?= ${PWD}/src/htslib/
+CXXFLAGS += -isystem ${PREFIX} -isystem ${BOOST_ROOT} -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive
+LDFLAGS += -L${PREFIX}/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time
+LDFLAGS += -lhts -lz -llzma -lbz2
+CXXFLAGS += -O3 -fno-tree-vectorize -DNDEBUG
 
-# Install dir
-prefix = ${PWD}
-exec_prefix = $(prefix)
-bindir ?= $(exec_prefix)/bin
-
-# Flags
-CXX=g++
-CXXFLAGS = ${CMDCXXFLAGS}
-CXXFLAGS += -isystem ${EBROOTHTSLIB} -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive
-LDFLAGS = ${CMDLDFLAGS}
-LDFLAGS += -L${EBROOTHTSLIB} -L${EBROOTHTSLIB}/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time 
-
-# Additional flags for release/debug
-ifeq (${STATIC}, 1)
-	LDFLAGS += -static -static-libgcc -pthread -lhts -lz -llzma -lbz2
-else
-	LDFLAGS += -lhts -lz -llzma -lbz2 -Wl,-rpath,${EBROOTHTSLIB}
-endif
-ifeq (${DEBUG}, 1)
-	CXXFLAGS += -g -O0 -fno-inline -DDEBUG
-else ifeq (${DEBUG}, 2)
-	CXXFLAGS += -g -O0 -fno-inline -DPROFILE
-	LDFLAGS += -lprofiler -ltcmalloc
-else
-	CXXFLAGS += -O3 -fno-tree-vectorize -DNDEBUG
-endif
-ifeq (${EBROOTHTSLIB}, ${PWD}/src/htslib/)
-	SUBMODULES += .htslib
-endif
-
-
-# External sources
-HTSLIBSOURCES = $(wildcard src/htslib/*.c) $(wildcard src/htslib/*.h)
 SOURCES = $(wildcard src/*.h) $(wildcard src/*.cpp)
 
 # Targets
-BUILT_PROGRAMS = src/alfred
-TARGETS = ${SUBMODULES} ${BUILT_PROGRAMS}
+TARGETS = src/alfred
 
 all:   	$(TARGETS)
 
-.htslib: $(HTSLIBSOURCES)
-	if [ -r src/htslib/Makefile ]; then cd src/htslib && make && make lib-static && cd ../../ && touch .htslib; fi
-
-src/alfred: ${SUBMODULES} $(SOURCES)
+src/alfred: $(SOURCES)
 	$(CXX) $(CXXFLAGS) $@.cpp -o $@ $(LDFLAGS)
 
-install: ${BUILT_PROGRAMS}
-	mkdir -p ${bindir}
-	install -p ${BUILT_PROGRAMS} ${bindir}
-
 clean:
-	if [ -r src/htslib/Makefile ]; then cd src/htslib && make clean; fi
-	rm -f $(TARGETS) $(TARGETS:=.o) ${SUBMODULES}
-
-distclean: clean
-	rm -f ${BUILT_PROGRAMS}
-
-.PHONY: clean distclean install all
+	rm -f $(TARGETS) $(TARGETS:=.o)
