diff --git a/Makefile b/Makefile
index d4dccd2..4d05d49 100644
--- a/Makefile
+++ b/Makefile
@@ -3,6 +3,7 @@ STATIC ?= 0
 
 # Submodules
 PWD = $(shell pwd)
+SDSL_ROOT ?= ${PWD}/src/sdslLite/
 EBROOTHTSLIB ?= ${PWD}/src/htslib/
 JLIB ?= ${PWD}/src/jlib/
 
@@ -13,10 +14,8 @@ bindir ?= $(exec_prefix)/bin
 
 # Flags
 CXX=g++
-CXXFLAGS = ${CMDCXXFLAGS}
-CXXFLAGS += -std=c++11 -isystem ${JLIB} -isystem ${EBROOTHTSLIB} -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing
-LDFLAGS = ${CMDLDFLAGS}
-LDFLAGS += -L${EBROOTHTSLIB} -L${EBROOTHTSLIB}/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time -L${EBROOTHTSLIB} -L${EBROOTHTSLIB}/lib -lpthread
+CXXFLAGS += -std=c++11 -isystem ${JLIB} -isystem ${EBROOTHTSLIB} -isystem ${SDSL_ROOT}/include -pedantic -W -Wall -fvisibility=hidden
+LDFLAGS += -L${SDSL_ROOT}/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time -lsdsl -ldivsufsort -ldivsufsort64 -ldl -L${EBROOTHTSLIB} -L${EBROOTHTSLIB}/lib -lpthread
 
 # Additional flags for release/debug
 ifeq (${STATIC}, 1)
