{% set version = "0.6.2" %}
{% set sha256 = "0d7a0f9d7965f8dbef339ea3e4f71755c4d6eff2c2a1a5351fc8b6f152f2deb2" %}

package:
  name: alfred
  version: '{{ version }}'

source:
  url: https://github.com/tobiasrausch/alfred/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('alfred', max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - zlib
    - bzip2
    - boost-cpp
    - xz
    - htslib
  run:
    - boost-cpp
    - htslib

test:
  commands:
    - alfred --help

about:
  home: https://github.com/tobiasrausch/alfred
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: BAM alignment statistics, feature counting and feature annotation
  dev_url: "https://github.com/tobiasrausch/alfred"
  doc_url: "https://github.com/tobiasrausch/alfred/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1093/bioinformatics/bty1007
    - biotools:alfred
