{% set name = "fungar" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/resgen-br/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c38976bc3290e451445b4fcee6ba19de2f90b065e2412263f87922e2dc66873f

build:
  number: 0
  noarch: generic
  script:
    - install -m 755 FUNGAR.sh "$PREFIX/bin/fungar"

requirements:
  run:
    - bash
    - python >=3.8
    - pandas
    - diamond

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/resgen-br/{{ name }}
  license: MIT
  license_file: LICENSE
  summary: Pipeline for detecting antifungal resistance genes and mutations from metagenomic sequencing reads
  description: |
    FUNGAR is a command-line pipeline for detecting antifungal resistance
    genes and associated amino acid mutations from metagenomic sequencing data.
    It uses DIAMOND for protein alignment and Python-based mutation parsing.

extra:
  skip-lints:
    - missing_run_exports
  identifiers:
    - biotools:fungar
