--- Makefile	2002-04-13 06:12:04.000000000 +1000
+++ Makefile.new	2017-01-30 11:04:57.000000000 +1000
@@ -122,1 +122,1 @@
-	$(PERLDIR)/$(PERLBIN) checkversion.pl
+	#$(PERLDIR)/$(PERLBIN) checkversion.pl
 	sed 's#/tmp#$(TEMPDIR)#g' tRNAscan-SE.src | \
 	sed 's#bindir = ""#bindir =\"$(BINDIR)/"#g' | \
 	sed 's#/usr/local/lib/tRNAscanSE#$(LIBDIR)#g' | \
