--- mapdamage/seqtk/Makefile
+++ mapdamage/seqtk/Makefile
@@ -2,7 +2,8 @@
 CFLAGS=-g -Wall -O2 -Wno-unused-function
 
 seqtk:seqtk.c khash.h kseq.h
-		$(CC) $(CFLAGS) seqtk.c -o $@ -lz -lm
+	# $(CC) $(CFLAGS) seqtk.c -o $@ -lz -lm
+	touch seqtk
 
 clean:
 		rm -fr gmon.out *.o ext/*.o a.out seqtk *~ *.a *.dSYM session*
