{% set name = "pseudoscope" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bbeckley-hub/pseudoscope/archive/v{{ version }}.tar.gz
  sha256: 2cebd30f9dccebc8919b35f2fc6caf560eb216c04c081e9d3549606a767c3345

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv"
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - pandas >=1.5.0
    - biopython >=1.85
    - psutil >=5.9.0
    - requests >=2.28.0
    - tqdm >=4.64.0
    - click >=8.0.0
    - pasty
    - beautifulsoup4 >=4.11.0
    - lxml >=4.9.0
    - matplotlib-base >=3.5.0
    - seaborn >=0.12.0
    - scipy >=1.10.1
    - scikit-learn >=1.0.0
    - networkx >=2.8
    - plotly >=5.10.0
    - abricate >=1.2.0
    - perl
    - any2fasta
    - blast >=2.13.0
    - perl-moo
    - perl-list-moreutils
    - perl-json
    - perl-lwp-protocol-https
    - perl-path-tiny
    - perl-data-dumper
    - perl-getopt-long
    - perl-file-which

test:
  commands:
    - pseudoscope --help

about:
  home: https://github.com/bbeckley-hub/pseudoscope
  license: MIT
  license_file: LICENSE
  summary: 'Pseudoscope: Comprehensive P. aeruginosa genomic typing pipeline with parallel execution'
  description: |
    Pseudoscope is a complete, automated genomic analysis pipeline for P. aeruginosa,
    featuring parallel execution for rapid processing of bacterial genomes.
  doc_url: https://github.com/bbeckley-hub/pseudoscope
  dev_url: https://github.com/bbeckley-hub/pseudoscope

extra:
  recipe-maintainers:
    - bbeckley-hub
