diff -Nau Makefile.orig Makefile
--- Makefile.orig	1969-12-31 19:00:00.000000000 -0500
+++ Makefile	2020-12-21 09:34:14.912844244 -0500
@@ -0,0 +1,5 @@
+all:
+	cc -O3 -o pulchra pulchra.c pulchra_data.c -lm
+install: all
+	mkdir ${PREFIX}/bin
+	cp pulchra ${PREFIX}/bin/
