diff --git a/Makefile b/Makefile
index e821782..257a0d2 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 #
-SHELL=/bin/sh
+SHELL=/bin/bash
 MAKE=make
 MAKEFILE=Makefile
 
@@ -35,7 +35,7 @@ compile:
 		echo "------------------------------------------------------------"; \
 		echo "**** Making $$libdir ****"; \
 		echo "------------------------------------------------------------"; \
-		(cd $$libdir && $(MAKE) -f $(MAKEFILE) "OPT=-O" install) || exit 1; \
+		(cd $$libdir && $(MAKE) -f $(MAKEFILE) "OPT=-O -fdata-sections -ffunction-sections" install) || exit 1; \
 	done
 #
 debug:
@@ -48,7 +48,7 @@ debug:
 		(cd $$libdir && $(MAKE) -f $(MAKEFILE)  "OPT=-g" install) || exit 1; \
 	done
 #
-clean:  
+clean:
 	@for libdir in $(LIBDIRS); do \
 		echo cleaning $$libdir; \
 		(cd $$libdir && $(MAKE) -f $(MAKEFILE) clean) || exit 1; \
