diff --git a/Makefile b/Makefile
index e821782..6dfa854 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,8 @@
 #
-SHELL=/bin/sh
+SHELL=/bin/bash
 MAKE=make
 MAKEFILE=Makefile
+LDFLAGS+=-Wl,--gc-sections -Wl,--as-needed

 LIBDIRS = common-v4.5 \
           numeric-util-v1.0 \
@@ -35,7 +36,7 @@ compile:
 		echo "------------------------------------------------------------"; \
 		echo "**** Making $$libdir ****"; \
 		echo "------------------------------------------------------------"; \
-		(cd $$libdir && $(MAKE) -f $(MAKEFILE) "OPT=-O" install) || exit 1; \
+		(cd $$libdir && $(MAKE) -f $(MAKEFILE) "LDFLAGS=$(LDFLAGS)" "OPT=-Os -pipe -fdata-sections -ffunction-sections" install) || exit 1; \
 	done
 #
 debug:
@@ -48,7 +49,7 @@ debug:
 		(cd $$libdir && $(MAKE) -f $(MAKEFILE)  "OPT=-g" install) || exit 1; \
 	done
 #
-clean:
+clean:
 	@for libdir in $(LIBDIRS); do \
 		echo cleaning $$libdir; \
 		(cd $$libdir && $(MAKE) -f $(MAKEFILE) clean) || exit 1; \
