#!/bin/bash

BINARY_HOME=$PREFIX/bin
PACKAGE_HOME=$PREFIX/share
PACKAGE_FULL_NAME=${PKG_NAME}${PKG_VERSION}

mkdir -p $BINARY_HOME $PACKAGE_HOME
cp -aR ${PKG_NAME}* $PACKAGE_HOME/$PACKAGE_FULL_NAME
cd $PACKAGE_HOME
chmod +x $PACKAGE_FULL_NAME
cd $BINARY_HOME
ln -s "$PACKAGE_HOME/$PACKAGE_FULL_NAME" uclust
