{% set name = "abritamr" %}
{% set version = "1.3.0" %}
{% set sha256 = "bd50ff72f8ca4d2a6e08c14058d6c98ec85931233fe85683e21abe402fb1a353" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/abritamr-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - abritamr = abritamr.abritamr:main
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps --no-cache-dir -vvv
  run_exports:
    - {{ pin_subpackage('abritamr', max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - libcurl
  run:
    - python >=3.9
    - pandas
    - xlsxwriter
    - ncbi-amrfinderplus >=4.0.0
    - parallel

test:
  imports:
    - {{ name }}
  commands:
    - {{ name }} --version
    - {{ name }} --help
    - {{ name }} run --help
    - {{ name }} report --help
    - {{ name }} update_db --help
  requires:
    - nose
    - pytest

about:
  home: "https://github.com/MDU-PHL/{{ name }}"
  license: "GPL-3.0-only"
  license_family: GPL3
  licence_file: LICENSE
  summary: "Idenify bacterial AMR genes and SNPs in genome assemblies"

extra:
  recipe-maintainers:
    - kristyhoran
  identifiers:
    - biotools:{{ name }}
