#!/bin/bash

mkdir -p build
cd build
<<<<<<< HEAD
cmake -DOVERRIDE_COMMIT_VERSION=96ebb63 -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_EXE_LINKER_FLAGS=-L${PREFIX}/lib ..
=======
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_EXE_LINKER_FLAGS=-L${PREFIX}/lib ..
>>>>>>> 5ff60766dab08889a01bc1bc55cbe74c056f4db5
make VERBOSE=1 -j 8 maCMD

mkdir -p $PREFIX/bin
mkdir -p $PREFIX/lib
cp maCMD $PREFIX/bin
cp libMA.so $PREFIX/lib/

