*** Makefile	2018-11-08 13:50:57.000000000 +0300
--- Makefile	2018-11-11 08:01:50.000000000 +0300
*************** CPPFLAGS = -DNDEBUG -D_FORTIFY_SOURCE=2 
*** 230,236 ****
  CXX = /opt/conda/conda-bld/demuxlet_1541674026162/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++
  CXXCPP = /opt/conda/conda-bld/demuxlet_1541674026162/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++ -E
  CXXDEPMODE = depmode=gcc3
! CXXFLAGS = -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/opt/conda/conda-bld/demuxlet_1541674026162/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
  CYGPATH_W = echo
  DEFS = -DHAVE_CONFIG_H
  DEPDIR = .deps
--- 230,236 ----
  CXX = /opt/conda/conda-bld/demuxlet_1541674026162/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++
  CXXCPP = /opt/conda/conda-bld/demuxlet_1541674026162/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++ -E
  CXXDEPMODE = depmode=gcc3
! CXXFLAGS = -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/opt/conda/conda-bld/demuxlet_1541674026162/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -Wl,--no-as-needed -ldl
  CYGPATH_W = echo
  DEFS = -DHAVE_CONFIG_H
  DEPDIR = .deps
