{% set name = "metaamrplus" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/migshaw03/MetaAMRplus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5ae9181e0eb5b64e929e4980bbef47c7aec7e2c81ae8bfda1d5a3e072b4f89ec

build:
  number: 1
  noarch: generic
  run_exports:
    - {{ pin_subpackage("metaamrplus", max_pin="x") }}

requirements:
  build:
    - coreutils

  host:
    - python >=3.8

  run:
    - python >=3.8
    - coreutils
    - gawk
    - blast >=2.14
    - prodigal

test:
  commands:
    - metaamrplus --help

about:
  home: https://github.com/migshaw03/MetaAMRplus
  license: MIT
  summary: "MetaAMRplus: AMR + metal resistance + colocalisation analysis"
  description: "MetaAMRplus is a command-line tool for detecting antimicrobial resistance genes, metal/biocide resistance genes, and their genomic colocalisation."

extra:
  recipe-maintainers:
    - migshaw03