diff --git a/Makefile b/Makefile
index 587afde..73094c0 100644
--- a/Makefile
+++ b/Makefile
@@ -57,7 +57,7 @@ endif


 # CXXFLAGS can be overridden by the user.
-CXXFLAGS    ?= -Wall -Wextra -pedantic -mtune=native
+CXXFLAGS    ?= -Wall -Wextra -pedantic -mtune=generic


 # These flags are required for the build to work.
