diff --git a/Makefile b/Makefile
index 05ff66a..9c03866 100644
--- a/Makefile
+++ b/Makefile
@@ -66,7 +66,7 @@ CXXFLAGS    ?= -Wall -Wextra -pedantic -mtune=native
 
 # These flags are required for the build to work.
 FLAGS        = -std=c++14 -Iunicycler/include -fPIC
-LDFLAGS      = -shared -lz
+LDFLAGS      += -shared -lz
 
 
 # Platform-specific stuff (for Seqan)
@@ -106,7 +106,7 @@
 
 
 $(TARGET): $(OBJECTS)
-	$(CXX) $(FLAGS) $(CXXFLAGS) -Wl,$(SONAME),$(TARGET) -o $(TARGET) $(OBJECTS) $(LDFLAGS)
+	$(CXX) $(CXXFLAGS) $(FLAGS) -Wl,$(SONAME),$(TARGET) -o $(TARGET) $(OBJECTS) $(LDFLAGS)
 
 clean:
 	$(RM) $(OBJECTS)
@@ -115,4 +115,4 @@
 	$(RM) $(TARGET)
 
 %.o: %.cpp $(HEADERS)
-	$(CXX) $(FLAGS) $(CXXFLAGS) -c -o $@ $<
+	$(CXX) $(CXXFLAGS) $(FLAGS) -c -o $@ $<
