--- src/Makefile	2016-09-28 11:36:12.000000000 +0200
+++ src/Makefile	2016-09-28 12:00:12.000000000 +0200
@@ -16,7 +16,7 @@
 #LDFLAGS = -lpthread -L/usr/lib -lm /usr/lib64/libexpat.a -static-libstdc++
 #LDFLAGS = -lpthread -L/usr/lib -lm /usr/lib64/libexpat.a
-LDFLAGS = -lpthread -L/usr/lib -lm -lexpat
+LDFLAGS = -lpthread -L{PREFIX}/lib/ -lm -lexpat
 SRCS := $(wildcard *.cpp)
 OBJS := $(patsubst %.cpp,%.o,$(wildcard *.cpp))
 DEPS := $(patsubst %.o,%.d,$(OBJS))
