{% set name = "synthbar" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

source:
  url: https://github.com/jamorrison/synthbar/archive/refs/tags/v{{ version }}.zip
  sha256: ab037d858c5670ea913c6237abe8a87cd090ec36e222c51f39b566a9cfd72a21
  patches:
    - 0000-Makefile.patch

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - zlib

test:
  commands:
    - synthbar -h

about:
  home: "https://github.com/jamorrison/synthbar"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Add synthetic cell barcodes to FASTQ reads."
  dev_url: "https://github.com/jamorrison/synthbar"
  doc_url: "https://github.com/jamorrison/synthbar"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1101/2025.05.30.657070
