{% set name = "eggs" %}
{% set version = "1.0.4" %}
package:
  name: eggs
  version: {{ version }}

source:
  url: https://github.com/TQ-Smith/EGGS/archive/refs/tags/EGGS-v{{ version }}.tar.gz
  sha256: daf5d384a176649178f3b2ff79ca97e754e585c205271b8e819861fcdb89615d

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - eggs -h

about:
  home: https://github.com/TQ-Smith/EGGS
  summary: Empirical Genotype Generalizer for Samples 
  description: |
    EGGS is a tool to manipulate genotypes. It can split ms-replicates to 
    multiple VCF files and convert EIGENSTRAT/ANCESTRYMAP files to VCF.
    EGGS is able to introduce various sorts of error, such as sequencing error,
    deamination, and missing genotypes into simulated replicates. EGGS is
    written in C with no dependencies.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/TQ-Smith/EGGS/wiki
  dev_url: https://github.com/TQ-Smith/EGGS

extra:
  recipe-maintainers:
    - TQ-Smith
