{% set version = "0.8.0" %}
{% set name = "salti" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sam-sims/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 1751aa62859d687d4cac2faf6c2b7e891c26c4c0d199e37630356e4dfa1d32ca

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('salti', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl

test:
  commands:
    - salti --version

about:
  home: https://github.com/Sam-Sims/salti
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A modern multiple sequence alignment browser - built for the terminal. 

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - sam-sims
    