diff --git a/Makefile b/Makefile
index 590ec3d..94bef12 100644
--- a/Makefile
+++ b/Makefile
@@ -14,18 +14,17 @@ bindir ?= $(exec_prefix)/bin
 
 # Flags
 CXX=g++
-OPENCVCXXFLAGS=$(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --cflags opencv4)
-CXXFLAGS += -isystem ${EBROOTHTSLIB} ${OPENCVCXXFLAGS} -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive
+CXXFLAGS += -isystem ${EBROOTHTSLIB} -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive
 LDFLAGS += -L${EBROOTHTSLIB} -L${EBROOTHTSLIB}/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time
 
 # Flags for static compile
 ifeq (${STATIC}, 1)
-	OPENCVFLAGS=$(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --libs --static opencv4)
-	LDFLAGS += ${OPENCVFLAGS} -static -static-libgcc -pthread -lhts -lz -llzma -lbz2
+	OPENCVSTATIC += --static
+	LDFLAGS += -static -static-libgcc -pthread -lhts -lz -llzma -lbz2
 	LDOCV += -D BUILD_SHARED_LIBS=OFF -DOPENCV_GENERATE_PKGCONFIG=ON -D BUILD_ZLIB=ON -D BUILD_PNG=ON -D WITH_OPENEXR=OFF -D WITH_JPEG=OFF -D WITH_JASPER=OFF -D WITH_TIFF=OFF -D WITH_WEBP=OFF -D WITH_OPENCL=OFF -D WITH_GTK=OFF -D WITH_FFMPEG=OFF -D WITH_1394=OFF -D WITH_IPP=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_apps=OFF 
 else
-	OPENCVFLAGS=$(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --libs opencv4)
-	LDFLAGS += ${OPENCVFLAGS} -pthread -lhts -lz -llzma -lbz2 -Wl,-rpath,${EBROOTHTSLIB} -Wl,-rpath,${OPENCV}/lib/
+	OPENCVSTATIC += ""
+	LDFLAGS += -pthread -lhts -lz -llzma -lbz2 -Wl,-rpath,${EBROOTHTSLIB} -Wl,-rpath,${OPENCV}/lib/ -Wl,-rpath,${OPENCV}/lib64/
 	LDOCV += -D BUILD_SHARED_LIBS=ON -DOPENCV_GENERATE_PKGCONFIG=ON -D BUILD_ZLIB=ON -D BUILD_PNG=ON -D WITH_OPENEXR=OFF -D WITH_JPEG=OFF -D WITH_JASPER=OFF -D WITH_TIFF=OFF -D WITH_WEBP=OFF -D WITH_OPENCL=OFF -D WITH_GTK=ON -D WITH_FFMPEG=OFF -D WITH_1394=OFF -D WITH_IPP=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_apps=OFF 
 endif
 
@@ -64,7 +63,7 @@ all:   	$(TARGETS)
 	if [ -f src/opencv/CMakeLists.txt ]; then cd src/opencv/ && mkdir build && cd build/ &&  cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=${PWD}/src/ocv ${LDOCV} .. &&  make -j 4 && make install && cd ../ && rm -rf build/ && cd ../../ && touch .opencv; fi
 
 src/wally: ${SUBMODULES} $(SOURCES)
-	$(CXX) $(CXXFLAGS) $@.cpp -o $@ $(LDFLAGS)
+	$(CXX) $(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PWD}/src/ocv/lib64/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --cflags opencv4) $(CXXFLAGS) $@.cpp -o $@ $(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PWD}/src/ocv/lib64/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --libs ${OPENCVSTATIC} opencv4) $(LDFLAGS)
 
 install: ${BUILT_PROGRAMS}
 	mkdir -p ${bindir}
