diff --git a/Makefile b/Makefile
index 590ec3d..deb2ed3 100644
--- a/Makefile
+++ b/Makefile
@@ -14,17 +14,17 @@ bindir ?= $(exec_prefix)/bin
 
 # Flags
 CXX=g++
-OPENCVCXXFLAGS=$(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --cflags opencv4)
+OPENCVCXXFLAGS=$(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PWD}/src/ocv/lib64/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --cflags opencv4)
 CXXFLAGS += -isystem ${EBROOTHTSLIB} ${OPENCVCXXFLAGS} -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing -fpermissive
 LDFLAGS += -L${EBROOTHTSLIB} -L${EBROOTHTSLIB}/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time
 
 # Flags for static compile
 ifeq (${STATIC}, 1)
-	OPENCVFLAGS=$(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --libs --static opencv4)
+	OPENCVFLAGS=$(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PWD}/src/ocv/lib64/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --libs --static opencv4)
 	LDFLAGS += ${OPENCVFLAGS} -static -static-libgcc -pthread -lhts -lz -llzma -lbz2
 	LDOCV += -D BUILD_SHARED_LIBS=OFF -DOPENCV_GENERATE_PKGCONFIG=ON -D BUILD_ZLIB=ON -D BUILD_PNG=ON -D WITH_OPENEXR=OFF -D WITH_JPEG=OFF -D WITH_JASPER=OFF -D WITH_TIFF=OFF -D WITH_WEBP=OFF -D WITH_OPENCL=OFF -D WITH_GTK=OFF -D WITH_FFMPEG=OFF -D WITH_1394=OFF -D WITH_IPP=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_apps=OFF 
 else
-	OPENCVFLAGS=$(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --libs opencv4)
+	OPENCVFLAGS=$(shell export PKG_CONFIG_PATH=${PWD}/src/ocv/lib/pkgconfig/:${PWD}/src/ocv/lib64/pkgconfig/:${PKG_CONFIG_PATH} && pkg-config --libs opencv4)
 	LDFLAGS += ${OPENCVFLAGS} -pthread -lhts -lz -llzma -lbz2 -Wl,-rpath,${EBROOTHTSLIB} -Wl,-rpath,${OPENCV}/lib/
 	LDOCV += -D BUILD_SHARED_LIBS=ON -DOPENCV_GENERATE_PKGCONFIG=ON -D BUILD_ZLIB=ON -D BUILD_PNG=ON -D WITH_OPENEXR=OFF -D WITH_JPEG=OFF -D WITH_JASPER=OFF -D WITH_TIFF=OFF -D WITH_WEBP=OFF -D WITH_OPENCL=OFF -D WITH_GTK=ON -D WITH_FFMPEG=OFF -D WITH_1394=OFF -D WITH_IPP=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_apps=OFF 
 endif
