{% set name = "kleborate" %}
{% set version = "3.3.0b1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kleborate-{{ version }}.tar.gz"
  sha256: 42f2e3db3723a973e61b621387970c571344fc85101cc89231ce111ef620dceb

build:
  number: 0
  noarch: python
  entry_points:
    - kleborate = kleborate.__main__:main
  script: "{{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir"

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - numpy >=1.26.0
  run:
    - python >=3.11
    - biopython ==1.81
    - numpy >=1.26.0
    - kaptive
    - beautifulsoup4
    - numba
    - minimap2
    - mash
    - ezclermont
    - ectyper
    - mist_typing
    - shigapass
    - ncbi-stxtyper
    - ncbi-amrfinderplus

test:
  imports:
    - kleborate
  commands:
    - kleborate --help

about:
  home: "https://kleborate.readthedocs.io/"
  dev_url: "https://github.com/klebgenomics/Kleborate"
  summary: "Kleborate: a tool for typing and screening pathogen genome assemblies"
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE
  doc_url: "https://kleborate.readthedocs.io/"

extra:
  recipe-maintainers:
    - marymaranga