BASE_DIR="{$PREFIX}/share/cfcna-biomarkersearch"
mkdir -p "{$BASE_DIR}/jars"
mkdir -p "{$BASE_DIR}/libs"
mkdir -p "{$BASE_DIR}/scripts"
mkdir -p "{$BASE_DIR}/raw_data"
mkdir -p "{$BASE_DIR}/config"
mkdir -p "{$BASE_DIR}/input"
mkdir -p "{$BASE_DIR}/genome/index"
mkdir -p "{$BASE_DIR}/python"
cp metadata/jars/jcna-biomrkrs-final_11.jar "{$BASE_DIR}/jars/mod2to6.jar"
cp metadata/jars/libs/zstd-jni-1.5.7-4-linux_amd64.jar "{$BASE_DIR}/libs/zstd-linux_amd64.jar"
cp metadata/scripts/run_pipeline_module2to6.sh "{$BASE_DIR}/scripts/"
cp metadata/scripts/reads_preprocessing.sh "{$BASE_DIR}/scripts/"
cp -r metadata/data/sample_data/*fastq.gz "{$BASE_DIR}/raw_data/"
cp metadata/config/log4j2.xml "{$BASE_DIR}/config/"
cp metadata/data/others/NexteraXT-Trans-Prefix.fa "{$BASE_DIR}/config/adapterfile.fa"
cp metadata/data/others/genome-test.csv "{$BASE_DIR}/input/human/genome.csv"
cp metadata/data/others/params-test.csv "{$BASE_DIR}/input/human/params.csv"
wget -P "{$BASE_DIR}/genome" https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr22.fa.gz
gunzip "{$BASE_DIR}/genome/chr22.fa.gz"
bowtie2-build "{$BASE_DIR}/genome/chr22.fa" "{$BASE_DIR}/genome/index"
cp -r metadata/python/* "{$BASE_DIR}/python"
