{% set name = "fdedup" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RaphaelRibes/FastDedup/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 12f2c2f6c0d5a85bdc61c62d6f9da7c29931e437c37f41324434f14e8f4884f1

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - zlib
    - bzip2
    - xz
    - zstd
  run:

test:
  commands:
    - fdedup --help

about:
  home: https://github.com/RaphaelRibes/FastDedup
  license: MIT
  license_file:
    - Licence
    - THIRDPARTY.yml
  summary: "A fast and memory-efficient FASTX PCR deduplication tool"
  dev_url: https://github.com/RaphaelRibes/FastDedup

extra:
  recipe-maintainers:
    - RaphaelRibes
  additional-platforms:
    - linux-aarch64
    - osx-arm64
