#!/bin/bash

ALLELES_FLAG=false
HELP_FLAG=false

for i in "$@"
do
  if [ "$i" = "--alleles" ]
  then
    ALLELES_FLAG=true
  elif [ "$i" = "-h" ] || [ "$i" = "--help" ]
  then
    HELP_FLAG=true
  fi
done

if [ "$ALLELES_FLAG" = true ] || [ "$HELP_FLAG" = true ]
then
  python parse_mykrobe_predict.py $@
else
  python parse_mykrobe_predict.py --alleles alleles.txt $@
fi
