#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

ALLELES_FLAG=false
HELP_FLAG=false

for i in "$@"
do
  if [ "$i" = "--alleles" ]
  then
    ALLELES_FLAG=true
  elif [ "$i" = "-h" ] || [ "$i" = "--help" ]
  then
    HELP_FLAG=true
  fi
done

if [ "$ALLELES_FLAG" = true ] || [ "$HELP_FLAG" = true ]
then
  python $SCRIPT_DIR/parse_mykrobe_predict.py $@
else
  python $SCRIPT_DIR/parse_mykrobe_predict.py --alleles $SCRIPT_DIR/alleles.txt $@
fi
