{% set version = "0.45.1" %}
{% set sha256 = "c98986c752fbe7252febd2fed0c88fd5fabeca80062111d329799841cf910e8a" %}
{% set name = "mehari" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/varfish-org/mehari/archive/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - cargo-bundle-licenses
    - pkg-config
  host:
    - clangdev
    - llvmlite
    - openssl
    - protobuf
    - libprotobuf
    - zlib
    - sqlite
  run:
    - sqlite

test:
  commands:
    - mehari -h

about:
  home: "https://github.com/varfish-org/mehari"
  license: MIT
  license_family: MIT
  license_file: "LICENSE.txt"
  summary: "VEP-like tool for sequence ontology and HGVS annotation of VCF files written in Rust."
  dev_url: "https://github.com/varfish-org/mehari"
  doc_url: "https://github.com/varfish-org/mehari/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
  identifiers:
    - doi:10.5281/zenodo.10603122
  skip-lints:
    - compiler_needs_stdlib_c
