diff -Naur Rbwa/src/Makefile Rbwa-new/src/Makefile
--- src/Makefile	2026-02-22 12:50:52.023502922 +0100
+++ src/Makefile	2026-02-22 12:51:01.282891554 +0100
@@ -7,7 +7,7 @@
 # 0 commented out non-portable -Wno-unused-function flag
 
 
-CC=			gcc
+CC ?=			gcc
 #CC=			clang --analyze
 #CFLAGS=		-g -Wall -Wno-unused-function -O2
 CFLAGS=		-g -Wall -O2
@@ -42,10 +42,10 @@
 
 
 bwa:libbwa.a $(AOBJS) main.o
-		$(CC) $(CFLAGS) $(DFLAGS) $(AOBJS) main.o -o $@ -L. -lbwa $(LIBS)
+		$(CC) $(CFLAGS) $(LDFLAGS) $(AOBJS) main.o -o $@ -L. -lbwa $(LIBS)
 
 bwamem-lite:libbwa.a example.o
-		$(CC) $(CFLAGS) $(DFLAGS) example.o -o $@ -L. -lbwa $(LIBS)
+		$(CC) $(CFLAGS) $(LDFLAGS) example.o -o $@ -L. -lbwa $(LIBS)
 
 libbwa.a:$(LOBJS)
 		$(AR) -csru $@ $(LOBJS)
