{% set name = "kmcp" %}
{% set version = "0.9.5" %}

package:
  name: {{name}}
  version: {{ version }}

source:
  - url: https://github.com/shenwei356/kmcp/releases/download/v{{ version }}/kmcp_darwin_amd64.tar.gz  # [osx and x86_64]
    md5: bf5662dbaace6d63fca5b6973cac144d  # [osx and x86_64]
  - url: https://github.com/shenwei356/kmcp/releases/download/v{{ version }}/kmcp_linux_amd64.tar.gz  # [linux and x86_64]
    md5: af9615b92f8ddf4810297e45762fe8c3  # [linux and x86_64]
  - url: https://github.com/shenwei356/kmcp/releases/download/v{{ version }}/kmcp_linux_arm64.tar.gz  # [linux and aarch64]
    md5: 03ac274a035fbab39f1bd02498bcbb8e  # [linux and aarch64]
  - url: https://github.com/shenwei356/kmcp/releases/download/v{{ version }}/kmcp_darwin_arm64.tar.gz  # [osx and arm64]
    md5: b7963db7e9de5e4e3591b1bb256ec1c2  # [osx and arm64]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('kmcp', max_pin='x') }}

test:
  commands:
    - kmcp version --help

about:
  home: https://github.com/shenwei356/kmcp
  summary: accurate metagenomic profiling of both prokaryotic and viral populations by pseudo-mapping
  license: MIT

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64

  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
