--- Makefile
+++ Makefile
@@ -1,5 +1,5 @@
 #modied from htslib makefile
-FLAGS=-O3 -D__WITH_POOL__
+FLAGS=-O3 -D__WITH_POOL__ $(LDFLAGS) $(INC)
 
 CFLAGS += $(FLAGS)
 CXXFLAGS += $(FLAGS)
@@ -21,7 +21,7 @@
 $(info HTSSRC not defined, assuming systemwide installation -lhts)
 endif
 
-PACKAGE_VERSION  = 0.902
+PACKAGE_VERSION  = 0.910
 
 ifneq "$(wildcard .git)" ""
 PACKAGE_VERSION := $(shell git describe --always --dirty)
