--- Makefile
+++ Makefile
@@ -21,7 +21,7 @@
 $(info HTSSRC not defined, assuming systemwide installation -lhts)
 endif
 
-PACKAGE_VERSION  = 0.902
+PACKAGE_VERSION  = 0.910
 
 ifneq "$(wildcard .git)" ""
 PACKAGE_VERSION := $(shell git describe --always --dirty)
