{% set version = "1.1.4" %} 
{% set name = "tracs" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gtonkinhill/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 23217e536de86fe08c1d0593556025436742ec36a04743f551f4b5483fdc5b85

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  skip: true # [py<312]
  run_exports:
    - {{ pin_subpackage('tracs', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - boost-cpp
    - zlib
    - libgomp # [linux]
    - llvm-openmp # [osx]
  run:
    - python
    - numpy
    - pandas
    - sourmash
    - joblib
    - ncbi-genome-download
    - pyfastx
    - tqdm
    - scipy
    - plotly
    - samtools
    - htsbox
    - minimap2
    - matplotlib-base

test:
  imports:
  - tracs
  commands:
  - tracs --help
  - tracs --version
  - tracs align --help 
  - tracs combine --help 
  - tracs distance --help 
  - tracs threshold --help 
  - tracs cluster --help
  - tracs build-db --help
  - tracs pipe --help

about:
  home: https://github.com/gtonkinhill/tracs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Tracs - Fast pairwise transmission inference from single genome and/or metagenomic data'
  doc_url: https://github.com/gtonkinhill/tracs/tree/main/docs

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
