FROM quay.io/bioconda/base-glibc-busybox-bash:latest

SHELL ["/bin/bash", "-c"]

RUN echo "umask 022" >> /etc/profile
RUN echo "umask 022" >> /root/.bashrc
#ENV ENV /etc/profile
#ENV BASH_ENV /etc/profile

# replace /bin/sh with a wrapper to /bin/bash
RUN unlink /bin/sh
COPY .circleci/docker/custom-bin-sh.sh /bin/sh
RUN chmod +x /bin/sh
