--- Makefile.org	2021-08-27 21:10:36.161486256 -0500
+++ Makefile	2021-08-27 21:12:13.995234557 -0500
@@ -109,7 +109,7 @@
 pgo-static: static debug-strip
 
 install:
-	install -m 0755 bin/sambamba $(prefix)/bin
+	install -m 0755 $(OUT) $(prefix)/bin/sambamba
 
 clean: clean-d
 	rm lz4/lib/*.[oa]
