--- a/Makefile
+++ b/Makefile
@@ -13,7 +13,7 @@
 #
 #   make LIBRARY_PATH=~/opt/ldc2-1.7.0-linux-x86_64/lib debug

-D_COMPILER=ldc2
+D_COMPILER=gdc
 DFLAGS      = -wi -I. -IBioD -IundeaD/src -g

 DLIBS       = $(LIBRARY_PATH)/libphobos2-ldc.a $(LIBRARY_PATH)/libdruntime-ldc.a
@@ -55,7 +55,7 @@ ldc-version-info:
 utils/ldc_version_info_.o: ldc-version-info
        $(D_COMPILER) $(DFLAGS) -c utils/ldc_version_info_.d -od=$(dir $@)

-build-setup: htslib-static lz4-static ldc-version-info
+build-setup: htslib-static lz4-static
        mkdir -p build/

 default debug release static: $(OUT)
