{% set name="python-nextflow" %}
{% set repo="nextflow.py" %}
{% set version="0.13.1" %}


package:
  name: {{ name }}
  version: {{ version }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vvv .
  run_exports:
    - {{ pin_subpackage('python-nextflow', max_pin="x") }}

source:
  url: https://github.com/goodwright/{{ repo }}/archive/v{{ version }}.tar.gz
  sha256: 368e48a41b04193cdcff999862fc4a0cf1420224a1e18e632b655a96f2e34254

requirements:
  host:
    - python >=3.6,<=3.10
    - pip
  run:
    - python >=3.6,<=3.10
    - nextflow

test:
  imports:
    - nextflow

about:
  home: https://github.com/goodwright/{{ repo }}/
  license: 'MIT'
  license_file: LICENSE
  summary: 'Python module to run Nextflow pipelines'

extra:
  recipe-maintainers:
    - telatin
