{% set version = "1.1.0" %}

package:
  name: constrain
  version: {{ version }}

source:
  url: https://github.com/acg-team/ConSTRain/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 166830fdc8acee7e1c79566688ed58353c3918a9b0e6262e647bae8a11cfd4e0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('constrain', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - clangdev <22 # based on https://github.com/rust-bio/rust-htslib/issues/508

  

test:
  commands:
    - ConSTRain --help

about:
  home: https://github.com/acg-team/ConSTRain
  license: GPL-3.0-only
  license_file: LICENSE
  summary: "A short tandem repeat variant caller that incorporates copy number information"

extra:
  identifiers:
    - doi:10.1038/s42003-025-08837-8