{% set name = "tricord" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fg-labs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 774bc830fd2a3baad4dca084a9a1a359329d3bd1ef40a003275c90eb5c0fb447

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("tricord", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - clangdev

test:
  commands:
    - tricorder --help

about:
  home: https://github.com/fg-labs/tricord
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Run a command and report its process tree's CPU, memory, and I/O usage
  dev_url: https://github.com/fg-labs/tricord
  doc_url: https://github.com/fg-labs/tricord/blob/v{{ version }}/README.md

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - nh13
