--- Makefile    2015-06-15 10:32:06.000000000 +0000
+++ Makefile.new        2016-01-26 22:51:56.619087809 +0000
@@ -60,7 +60,7 @@
       	rm -f dazz.db.tar.gz

 install:
-       cp $(ALL) ~/bin
+       cp $(ALL) ${PREFIX}/bin

 package:
       	make clean
