--- /dev/null	2016-11-21 10:09:24.584591364 +0100
+++ makefile	2016-12-02 14:11:41.139119777 +0100
@@ -0,0 +1,35 @@
+# Config
+DEBUG     := 0
+BUILDDIR  := build
+SOURCEDIR := src
+# End config
+
+CXX       := g++
+CXXFLAGS  := -MMD -Wall -Wextra -ansi -pedantic -std=c++11
+LDFLAGS   := -lpthread -lboost_system
+INC       := -I.
+SOURCES   := $(shell find $(SOURCEDIR) -name '*.cpp')
+OBJECTS   := $(SOURCES:%.cpp=$(BUILDDIR)/%.o)
+EXECUTABLE:= MetaProb
+
+ifneq ($(DEBUG),0)
+	CXXFLAGS += -g -O0
+else
+	CXXFLAGS += -O3
+endif
+
+
+all: $(EXECUTABLE)
+
+$(EXECUTABLE): $(OBJECTS)
+	$(CXX) -o $@ $^ $(LDFLAGS)
+
+$(BUILDDIR)/%.o: %.cpp
+	mkdir -p $(dir $@)
+	$(CXX) $(CXXFLAGS) $(INC) -o $@ -c $<
+
+clean:
+	rm -r $(BUILDDIR) $(EXECUTABLE)
+
+DEPS    := $(OBJECTS:.o=.d)
+-include $(DEPS)
