{% set name = "panoptes-ui" %}
{% set version = "1.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: e5ab20752a659bc73f34d698617a36af5ff88d5c7085780f08aeb11579305765

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}
  entry_points:
    - panoptes=panoptes:main
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  host:
    - flask >=1.1.1
    - humanfriendly >=4.18
    - marshmallow >=3.0.1
    - pip
    - python >=3.11
    - setuptools
    - sqlalchemy >=1.3.7
  run:
    - flask >=1.1.1
    - humanfriendly >=4.18
    - marshmallow >=3.0.1
    - python >=3.11
    - sqlalchemy >=1.3.7

test:
  imports:
    - panoptes
    - panoptes.routes
    - panoptes.server_utilities
    - panoptes.static
    - panoptes.static.src
    - panoptes.tests
  commands:
    - panoptes --help

about:
  home: "https://github.com/panoptes-organization/panoptes"
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "panoptes: monitor computational workflows in real time"

extra:
  recipe-maintainers:
    - fgypas
