export C_INCLUDE_PATH="$BUILD_PREFIX/include":$C_INCLUDE_PATH
export INCLUDE_PATH="$BUILD_PREFIX/include":$INCLUDE_PATH
export CPLUS_INCLUDE_PATH="$BUILD_PREFIX/include":$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH="$BUILD_PREFIX/lib":$LD_LIBRARY_PATH
export CFLAGS=" -L$BUILD_PREFIX/lib "$CFLAGS
export CPPFLAGS=" -L$BUILD_PREFIX/lib "$CPPFLAGS
export CXXFLAGS=" -L$BUILD_PREFIX/lib "$CXXFLAGS
export LD_FLAGS=" -L$BUILD_PREFIX/lib "$LD_FLAGS
echo "include $BUILD_PREFIX/include"
echo "lib $BUILD_PREFIX/lib"
make condainstall PREFIX=$PREFIX CC=$CC CXX=$CXX

