{% set name = "chopper" %}
{% set version = "0.13.0" %}

package:
  name: {{name}}
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('chopper', max_pin="x.x") }}

source:
  url: https://github.com/wdecoster/chopper/archive/v{{ version }}.tar.gz
  sha256: f5df330e68e76ceb62f33338be7f7c21bd876e2ad84baa9e50ecbcfdfbd9d232

requirements:
  build:
    - {{ compiler('rust') }}
    - autoconf
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - pkg-config
    - cmake
    - zlib
    - clang
  host:
    - zlib
    - clang
  run:
    - zlib
    - clang

test:
  commands:
    - chopper --help

about:
  home: https://github.com/wdecoster/chopper
  license: MIT
  license_file: LICENSE
  summary: A rust command line for filtering and trimming long reads.
  dev_url: https://github.com/wdecoster/chopper
  doc_url: https://github.com/wdecoster/chopper#readme
  notes: |
    includes native support for Apple Silicon (M1/M2/M3) processors

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
