{% set name = "lodestar" %}
{% set version = "1.0.0" %}

package:
  name: lodestar
  version: {{ version }}

source:
  url: https://github.com/TQ-Smith/LODESTAR/archive/refs/tags/LODESTAR-v{{ version }}.tar.gz
  sha256: 72979c12184954744a2afff947f00f071570008e6317ca4b262dc8063f05d076

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - libgfortran
    - make
  host:
    - libgfortran
    - zlib

test:
  commands:
    - lodestar

about:
  home: https://github.com/TQ-Smith/LODESTAR
  summary: LOcal DEcomposition and Similarity to All Regions 
  description: |
    LODESTAR is a tool to discover associations between local patterns of relatedness
    and the genome-wide pattern or a set of user supplied coordinates. The relatedness
    between samples is calculated in blocks along the genome and projected into 
    lower-dimensional space using cMDS. Procrustes analysis is used to compare these
    local plots to the genome-wide plot or a user supplied plot. If the user supplied
    points represent latitude/longitude, then LODESTAR can find the regions that
    structurally reflect geography. LODESTAR is written in C and multithreaded.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/TQ-Smith/LODESTAR/wiki
  dev_url: https://github.com/TQ-Smith/LODESTAR

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - TQ-Smith
  skip-lints:
    - compiler_needs_stdlib_c
