{% set version = "0.8.4" %}
{% set github = "https://github.com/acidgenomics/r-cellosaurus" %}

package:
  name: r-cellosaurus
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: dfd91fb4b506eb49d1a9498a19c9fbc3311bdbaa9aa7659e2eacb3b966f58742

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('r-cellosaurus', max_pin="x.x") }}

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.48.0
    - bioconductor-iranges >=2.36.0
    - bioconductor-s4vectors >=0.40.0
    - r-acidbase >=0.7.3
    - r-acidcli >=0.3.0
    - r-acidgenerics >=0.7.6
    - r-acidplyr >=0.5.3
    - r-goalie >=0.7.7
    - r-pipette >=0.15.2
    - r-syntactic >=0.7.1
  run:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.48.0
    - bioconductor-iranges >=2.36.0
    - bioconductor-s4vectors >=0.40.0
    - r-acidbase >=0.7.3
    - r-acidcli >=0.3.0
    - r-acidgenerics >=0.7.6
    - r-acidplyr >=0.5.3
    - r-goalie >=0.7.7
    - r-pipette >=0.15.2
    - r-syntactic >=0.7.1

test:
  commands:
    - $R -e "library('Cellosaurus')"

about:
  home: https://r.acidgenomics.com/packages/cellosaurus/
  dev_url: "{{ github }}"
  license: Apache-2.0
  license_file: LICENSE.md
  license_family: APACHE
  summary: Cellosaurus identifier mapping toolkit.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
