{% set version = "0.3.0" %}

package:
  name: seq-hasher
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("seq-hasher", max_pin="x") }}

source:
  url: https://github.com/apcamargo/seq-hasher/archive/v{{ version }}.tar.gz
  sha256: 00cd961654215b8f6948637f2519c426d09314075198313bf64de084d0849b66

requirements:
  build:
    - {{ compiler('rust') }} 
    - cargo-bundle-licenses
  host:
  run:

test:
  commands:
    - seq-hasher --help

about:
  home: https://github.com/apcamargo/seq-hasher
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml 

  summary: >
    Compute hash digests for DNA sequences in a FASTA file, with support for
    circular permutations

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
