diff --git a/Makefile b/Makefile
index afa36f5..53357a4 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
-CC=gcc
-CPP=g++
+#CC=gcc
+#CPP=g++
 OPTIMISER = -O3
-CPPFLAGS = $(OPTIMISER) -std=c++14 -Wno-all -fmessage-length=0 -msse2 -mfpmath=sse
+CXXFLAGS = $(OPTIMISER) -std=c++14 -Wno-all -fmessage-length=0 -msse2 -mfpmath=sse
 CFLAGS = $(OPTIMISER) -std=c99 -Wno-all
 #CFLAGS = -g 
 
@@ -11,8 +11,8 @@ OBJS = utils.o hmm.o matrices.o
 HDR = utils.h hmm.h matrices.h
 INC = -I/usr/local/include
 # CPP code
-CPPOBJS = Cluster.o Tree.o Random.o Divvier.o bionj.o Sequence.o
-CPPHDR = Cluster.h Tree.h Random.h Divvier.h Sequence.h
+CXXOBJS = Cluster.o Tree.o Random.o Divvier.o bionj.o Sequence.o
+CXXHDR = Cluster.h Tree.h Random.h Divvier.h Sequence.h
 
 all : fastZorro
 
@@ -26,29 +26,29 @@ hmm.o : hmm.c hmm.h
 matrices.o : matrices.c matrices.h
 	$(CC) $(CFLAGS) $(INC) -c matrices.c
 
-fastZorro : $(CPPOBJS) $(OBJS) $(HDR)
-	$(CPP) $(CPPFLAGS) $(INC) $(LIB) -o divvier $(OBJS) $(CPPOBJS)
+fastZorro : $(CXXOBJS) $(OBJS) $(HDR)
+	$(CXX) $(CXXFLAGS) $(INC) $(LIB) -o divvier $(OBJS) $(CXXOBJS)
 
 #Cluster
 Cluster.o : Cluster.cpp Cluster.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Cluster.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Cluster.cpp
 
 Tree.o : Tree.cpp Tree.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Tree.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Tree.cpp
 
 Random.o : Random.cpp Random.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Random.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Random.cpp
 
 Sequence.o : Sequence.cpp Sequence.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Sequence.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Sequence.cpp
 
 #bionj
 bionj.o : bionj.cxx
-	$(CPP) $(CPPFLAGS) $(INC) -c bionj.cxx
+	$(CXX) $(CXXFLAGS) $(INC) -c bionj.cxx
 
 # Divvier
 Divvier.o : Divvier.cpp Divvier.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Divvier.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Divvier.cpp
 
 clean:
 	rm -f $(OBJS) $(CPPOBJS)
