diff --git a/Makefile b/Makefile
index afa36f5..7df5f24 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
-CC=gcc
-CPP=g++
+#CC=gcc
+#CPP=g++
 OPTIMISER = -O3
 CPPFLAGS = $(OPTIMISER) -std=c++14 -Wno-all -fmessage-length=0 -msse2 -mfpmath=sse
 CFLAGS = $(OPTIMISER) -std=c99 -Wno-all
