diff --git a/Makefile b/Makefile
index afa36f5..048c84f 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
-CC=gcc
-CPP=g++
+#CC=gcc
+#CPP=g++
 OPTIMISER = -O3
-CPPFLAGS = $(OPTIMISER) -std=c++14 -Wno-all -fmessage-length=0 -msse2 -mfpmath=sse
+CXXFLAGS = $(OPTIMISER) -std=c++14 -Wno-all -fmessage-length=0 -msse2 -mfpmath=sse
 CFLAGS = $(OPTIMISER) -std=c99 -Wno-all
 #CFLAGS = -g 
 
@@ -31,24 +31,24 @@ fastZorro : $(CPPOBJS) $(OBJS) $(HDR)
 
 #Cluster
 Cluster.o : Cluster.cpp Cluster.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Cluster.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Cluster.cpp
 
 Tree.o : Tree.cpp Tree.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Tree.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Tree.cpp
 
 Random.o : Random.cpp Random.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Random.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Random.cpp
 
 Sequence.o : Sequence.cpp Sequence.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Sequence.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Sequence.cpp
 
 #bionj
 bionj.o : bionj.cxx
-	$(CPP) $(CPPFLAGS) $(INC) -c bionj.cxx
+	$(CXX) $(CXXFLAGS) $(INC) -c bionj.cxx
 
 # Divvier
 Divvier.o : Divvier.cpp Divvier.h
-	$(CPP) $(CPPFLAGS) $(INC) -c Divvier.cpp
+	$(CXX) $(CXXFLAGS) $(INC) -c Divvier.cpp
 
 clean:
 	rm -f $(OBJS) $(CPPOBJS)
