{% set name = "bird_tool_utils_python" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/bird_tool_utils/bird_tool_utils-{{ version }}.tar.gz
  sha256: dba87e70ec89c939b322924438934abcb87d8d4ed4e1ec238c5e9c0dfc1d7acc

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - python >=3.7
    - argparse-manpage-birdtools >=1.7.0

test:
  imports:
    - bird_tool_utils

about:
  home: "https://github.com/wwood/bird_tool_utils-python"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: "LICENCE.txt"
  summary: "Python utilities used as part of the bird suite of bioinformatic tools."
  dev_url: "https://github.com/wwood/bird_tool_utils-python"
