{% set name = "metatracer" %}
{% set version = "0.1.1" %}
{% set sha256 = "d72e04d0b193fac14bd78b9e49bae59bacc3c8d742e85750a13be34de32ee159" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FofanovLab/metatracer/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"


requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=64
    - wheel
  run:
    - python >=3.9,<3.14
    - mtsv-tools >=2.1.0
    - click >=8.1
    - biopython >=1.80
    - pysam >=0.21 # not compatible with python 3.14
    - intervaltree >=3.1
    - ete3 >=3.1
    - tqdm >=4.64
    - htslib

test:
  commands:
    - metatracer --help
  imports:
    - metatracer


about:
  home: "https://github.com/FofanovLab/MetaTracer"
  summary: "MetaTracer metatranscriptomic analysis pipeline"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tfursten
  skip-lints:
    - should_be_noarch_generic # mtsv-tools dependency not available on macOS so not truly noarch.
