--- src/Makefile	2019-10-28 20:04:52.127542051 +0100
+++ src/Makefile	2019-10-28 20:05:18.020385181 +0100
@@ -21,6 +21,6 @@
 	$(foreach p, $(PROGS), cp -p $(p) ../tools/sketching)
 
 % : %.cpp $(HEADERS)
-	g++ $(CFLAGS) -o $@ $< $(LDFLAGS)
+	$(CXX) $(CFLAGS) -o $@ $< $(LDFLAGS)
 
 
