{% set name = "zipstrain" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d77ffedcafa69b981e3e8867a18939c6b2d2e8d6e66bcb93f801442fd864808e  

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-cache-dir --no-build-isolation -vvv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.12
    - poetry-core   
    - pip
  run:
    - python >=3.12
    - samtools 
    - click
    - polars
    - plotly
    - numpy
    - python-duckdb
    - seaborn-base
    - scipy
    - pyarrow
    - intervaltree
    - aiofiles
    - pydantic
    - rich
    - psutil

test:
  imports:
    - zipstrain
  commands:
    - zipstrain --help
    - samtools --version

about:
  home: "https://github.com/OlmLab/ZipStrain"
  summary: "Fast strain-level metagenomics."
  license: MIT
  license_family: MIT
  dev_url: "https://github.com/OlmLab/ZipStrain"
