--- Makefile.old	2022-08-17 13:50:38.240085326 -0500
+++ Makefile	2022-08-17 13:51:57.631421617 -0500
@@ -1,12 +1,12 @@
 EXECUTABLE := fxtract
 util := util
 OBJECTS := main.o fileManager.o fx.o util.o kseq.o
-PREFIX := /usr/local/bin
+PREFIX := ${PREFIX}
 
 LIBZ := 1
 
-PCRE_PATH := -lpcre
-LIBZ_PATH := -lz
+PCRE_PATH := -L${PREFIX}/lib -lpcre
+LIBZ_PATH := -L${PREFIX}/lib -lz
 
 LIBS :=
 
