{% set name = "ccfind" %}
{% set version = "1.4.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/yosuken/ccfind/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3c0ae032d8eb024e3c3c88aa32f50e4e14ffab02e71ece06487b3d6dc221ef89

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  run:
    - ruby >=2.0
    - blast >=2.6
    - fasta3
    - prodigal
    - parallel

test:
  commands:
    - ccfind --version

about:
  home: https://github.com/yosuken/ccfind
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Circular Complete genome FINDer"
  description: |
    ccfind is a general tool to detect circular complete genomes
    with clues of terminal redundancy. It was originally designed
    for identification of complete virus genomes from metagenome assembly.

extra:
  recipe-maintainers:
    - yosuken
