
{% set name = "mags-visualization" %}
{% set version = "0.0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/usegalaxy-eu/MAGs-visualization/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7726b87784a6b5c70b3bb04f2ee17f23d6f1613e209a6cff80000e1f1eea1420

build:
  noarch: python
  number: 0
  script:
    - python -m pip install . --no-deps -vv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.9,<3.13
    - pandas
    - numpy
    - matplotlib-base
    - seaborn
    - plotly
    - networkx
    - python-kaleido

test:
  imports:
      - mags_visualization
      - mags_visualization.sanky_taxa
  commands:
    - mags-visualization --help

about:
  home: https://github.com/usegalaxy-eu/MAGs-visualization
  summary: "Visualization toolkit for MAG quality, taxonomy, clustering, abundance patterns and functional annotation."
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alexandrah1704
