{% set name = "mitorsaw" %}
{% set version = "0.2.13" %}
{% set sha256 = "ba1143cc968265defa8682d20a4be371f2f19811da832bc204e8e2e789cdfc83" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PacificBiosciences/mitorsaw/releases/download/v{{ version }}/mitorsaw-v{{ version }}-x86_64-unknown-linux-gnu.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage('mitorsaw', max_pin="x.x") }}

test:
  commands:
    - mitorsaw --version

about:
  home: https://github.com/PacificBiosciences/mitorsaw
  license: Pacific Biosciences Software License Agreement
  summary: A tool for mitochondrial analysis for HiFi sequencing data

extra:
  recipe-maintainers:
    - holtjma
    - ctsa
  skip-lints:
    - should_use_compilers
    - should_be_noarch_generic
