{% set name = "perl-mozilla-ca" %}
{% set version = "20260813" %}
{% set sha256 = "81f0bd9665eacbb6feef13b0fa16fbb30162c09292542b1206434e569196dd9b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/L/LW/LWP/Mozilla-CA-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin=None) }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-test
  run:
    - perl

test:
  imports:
    - Mozilla::CA

about:
  home: "https://metacpan.org/pod/Mozilla::CA"
  license: Unknown
  summary: "Mozilla's CA cert bundle in PEM format."
  doc_url: "https://metacpan.org/pod/Mozilla::CA"
