#!/bin/bash

mkdir build
cd build

cmake \
    -D CMAKE_INSTALL_PREFIX=${PREFIX} \
    -D CMAKE_INSTALL_RPATH:STRING=${PREFIX}/lib \
    -D CMAKE_CXX_STANDARD=98 \
    -D BUILD_SHARED_LIBS=ON \
    -D CMAKE_BUILD_TYPE=Release \
    -D BUILD_TESTING:BOOL=OFF \
    -D BUILD_DOCUMENTATION:BOOL=OFF \
    -D BUILD_EXAMPLES:BOOL=OFF \
    -D BUILD_CONTRIB:BOOL=OFF \
    -D BUILD_CORE_IMAGING:BOOL=OFF \
    -D BUILD_CORE_SERIALISATION:BOOL=OFF \
    -D BUILD_CORE_GEOMETRY:BOOL=OFF \
        ..

make -j4
make install
