#!/bin/bash
mv DESCRIPTION DESCRIPTION.old
grep -v '^Priority: ' DESCRIPTION.old > DESCRIPTION
echo -e "CC=$CC
FC=$FC
CXX=$CXX
CXXFLAGS=$CXXFLAGS
CXX98=$CXX
CXX11=$CXX
CXX14=$CXX" > src/Makevars
$R CMD INSTALL --build .
