{% set name = "perl-www-robotrules" %}
{% set version = "6.03" %}
{% set sha256 = "8522b532935a11bfa688c2e113bac66729df4851be50c2c26d4b06f45fade472" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/WWW-RobotRules-6.03.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-uri

  run:
    - perl
    - perl-uri

test:
  imports:
    - WWW::RobotRules

about:
  home: http://metacpan.org/pod/WWW::RobotRules
  license: perl_5
  summary: 'database of robots.txt-derived permissions'
