{% set name = "orthofisher" %}
{% set version = "1.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/orthofisher-{{ version }}.tar.gz
  sha256: 6ab53c09cc8b60aabe7102290a22cca4f0fd5d9e7c49cd301f5ee3bb2566edf3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  entry_points:
    - orthofisher = orthofisher.orthofisher:main
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - biopython >=1.81
    - numpy >=1.24.0
    - tqdm >=4.66.1

test:
  imports:
    - orthofisher
  commands:
    - orthofisher --help

about:
  home: "https://github.com/JLSteenwyk/orthofisher"
  summary: "Orthofisher is a broadly applicable tool for automated gene identification and retrieval."
  license: MIT
  license_family: MIT
  license_file: "LICENSE.md"
  doc_url: "https://jlsteenwyk.com/orthofisher"
  dev_url: "https://github.com/JLSteenwyk/orthofisher"

extra:
  identifiers:
    - doi:10.1093/g3journal/jkab250
