{% set name = "gxfkit" %}
{% set version = "0.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/benngaihk/gxfkit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b60a0c96f4d70abea6a0a77f26e2fe8092aa4ab913936bb502f2561689c27020

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - gxfkit version
    - gxfkit gff2gtf --help

about:
  home: https://github.com/benngaihk/gxfkit
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fast Rust reimplementation of AGAT GFF/GTF operations

extra:
  recipe-maintainers:
    - benngaihk
