{% set name = "fastpmr" %}
{% set version = "0.2.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ehuangc/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: "7cccc6e0126a21c891c710a9d7c2911257ee3581fd9d8fd6447600d7d449dd79"

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - make
    - cargo-bundle-licenses
    - pkg-config

test:
  commands:
    - fastpmr --help

about:
  home: "https://github.com/ehuangc/fastpmr"
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "Calculate pairwise mismatch rates (PMRs) between ancient DNA sequences."
  dev_url: "https://github.com/ehuangc/fastpmr"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - ehuangc
  skip-lints:
    - compiler_needs_stdlib_c
