#!/bin/bash
mkdir build
cd build
cmake .. -DSHARED_LIBS_DEFAULT=OFF -DBUILD_SHARED_LIBS=OFF \
         -DGMX_PREFER_STATIC_LIBS=YES -DGMX_BUILD_OWN_FFTW=ON \
         -DGMX_DEFAULT_SUFFIX=ON -DGMX_GPU=OFF \
         -DREGRESSIONTEST_DOWNLOAD=ON \
         -DGMX_MPI=OFF \
         -DGMX_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_PREFIX=$PREFIX
make -j 8
make check
make install