{% set name = "distree" %}
{% set version = "1.0.1" %}
{% set sha256 = "a2b7f7d67cf230d4493f89442f674bbc0f721fbe5b9a87c1331b0d9f4aaab9fd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: "https://github.com/PathoGenOmics-Lab/{{ name }}/archive/v{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  number: 0
  script: 
    - "cargo install --no-track --verbose --root \"${PREFIX}\" --path ."
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  run_exports:
    - pin_subpackage(name, max_pin="x.x")

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}

test:
  commands:
    - distree --version

about:
  home: "https://github.com/PathoGenOmics-Lab/distree"
  license: "GPL-3.0-only"
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  license_family: GPL3
  summary: "A tool to calculate distances between phylogenetic trees."
