#!/usr/bin/env bash
# Build file is copied from VarScan
# https://github.com/bioconda/bioconda-recipes/blob/master/recipes/varscan/build.sh
# This file was automatically generated by the sbt-bioconda plugin.

outdir=$PREFIX/share/$PKG_NAME
mkdir -p $outdir
mkdir -p $PREFIX/bin
cp SampleConfig-assembly-0.3.jar $outdir/SampleConfig-assembly-0.3.jar
cp $RECIPE_DIR/biopet-sampleconfig.py $outdir/biopet-sampleconfig
ln -s $outdir/biopet-sampleconfig $PREFIX/bin

