{% set name = "diff-biophys" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diff_biophys-{{ version }}.tar.gz
  sha256: a4b011f454e19d3d0b5532c914e90ce6266c748c275a97ddf9224b6fe6f7267c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
  run:
    - python >=3.10
    - jax
    - jaxlib
    - numpy
    - biotite

test:
  imports:
    - diff_biophys

about:
  home: https://github.com/elkins/diff-biophys
  summary: "Differentiable biophysical modeling in JAX"
  license: MIT
  license_file: LICENSE
