--- Makefile	2014-12-01 02:45:02.000000000 +0000
+++ Makefile.new	2015-12-09 18:33:01.142958592 +0000
@@ -9,7 +9,7 @@
 NOBAMWAR= -std=c++0x -Wno-unknown-pragmas
 Z = -lz
 M = -lm
-BOOST_PATH = 
+BOOST_PATH = -I${PREFIX}/include -L${PREFIX}/lib
 STATIC =
 
 all:peakranger  
