{% set name = "perl-archive-extract" %}
{% set version = "0.90" %}
{% set sha256 = "f3381aa46b577af2bf31855a554754efbb0d2ebe491dd203f4c1cf5b480af17c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Archive-Extract-0.90.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-ipc-cmd
    - perl-extutils-makemaker
    - perl-locale-maketext-simple
    - perl-file-path
    - perl-params-check >=0.07
    - perl-module-load-conditional

  run:
    - perl
    - perl-locale-maketext-simple
    - perl-file-path
    - perl-params-check >=0.07
    - perl-ipc-cmd
    - perl-module-load-conditional

test:
  imports:
    - Archive::Extract

about:
  home: http://metacpan.org/pod/Archive::Extract
  license: perl_5
  summary: 'Generic archive extracting mechanism'
