{% set version = "20240303" %}
{% set name = "tmalign" %}
{% set sha256 = "6eadb92b7b562beeb81e25b12e7524a44eef93c6bb33e209bfdb7f4dc63c0fc6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pylelab/USalign/archive/61b50fbe09235deb70bcec42000b723c4def49ca.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin=None) }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - "TMalign > /dev/null"
    - "TMscore > /dev/null"

about:
  summary: "TM-align sequence-order independent protein structure alignment."
  home: "https://github.com/pylelab/USalign"
  license: "BSD-like"
  license_family: BSD
  dev_url: "https://github.com/pylelab/USalign"
  doc_url: "https://aideepmed.com/TM-align"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1093/nar/gki524
    - doi:10.1002/prot.20264
    - biotools:tm-score
