{% set name = "LCA" %}
{% set version = "0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hildebra/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 643f7a8aa7d833ca6aca72b9141a594d542a23f303b877bc8c226dc3a752a9d4

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - zlib

test:
  commands:
    - "LCA -h"

about:
  home: "https://github.com/hildebra/LCA"
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE
  summary: "LCA - Lowest Common Ancestor calculation tool."
  dev_url: "https://github.com/hildebra/LCA"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  skip-lints:
    - compiler_needs_stdlib_c
