--- Makefile.bak	2018-02-27 10:26:19.000000000 -0800
+++ Makefile	2018-02-27 10:26:31.000000000 -0800
@@ -1,5 +1,5 @@
 CC=			gcc
-CFLAGS=		-g -Wall -O2
+CFLAGS=		-g -Wall -Ofast -march=haswell
 AR=			ar
 DFLAGS=		-DHAVE_PTHREAD
 LOBJS=		utils.o kstring.o ksw.o bwt.o bntseq.o bwa.o bwamem.o bwamem_pair.o
