{% set version = '0.1.9' %}

package:
  name: r-seqmagick
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/seqmagick_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/seqmagick/seqmagick_{{ version }}.tar.gz
  sha256: 7195b8f34355e8e15da99d9e8f5d23cbcdb2eb05722260b991a3d7490143eae7


build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]
  run_exports:
    - {{ pin_subpackage('r-seqmagick', max_pin="x.x") }}

requirements:
  host:
    - r-base
    - bioconductor-biostrings
    - r-magrittr
    - r-yulab.utils >0.1.6
  run:
    - r-base
    - bioconductor-biostrings
    - r-magrittr
    - r-yulab.utils >0.1.6


test:
  commands:
    - $R -e "library('seqmagick')"           # [not win]
    - "\"%R%\" -e \"library('seqmagick')\""  # [win]

about:
  home: https://github.com/YuLab-SMU/seqmagick
  license: Artistic-2.0
  summary: Tools for reading and writing biological sequences in multiple formats, including
    'FASTA', 'PHYLIP', 'CLUSTAL', 'STOCKHOLM', 'MEGA' and 'GenBank'. Supports interleaved
    and sequential layouts where applicable, converts between formats, and manipulates
    sequence sets (e.g., filtering by patterns and computing consensus sequences from
    alignments). Also includes functions to download nucleotide records from NCBI by
    accession.
  license_family: OTHER
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0'

