{% set version = "1.2.0" %}
{% set sha256 = "dd0202e7e8c274fffe952e54131386535c065cc2f56764104cd53e5751527e2d" %}

package:
  name: r-linxreport
  version: '{{ version }}'

source:
  url: https://github.com/umccr/linxreport/archive/refs/tags/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage("r-linxreport", max_pin="x.x") }}

requirements:
  host:
    - r-base >=4
    - r-assertthat
    - r-details
    - r-dplyr
    - r-dt
    - r-fs
    - r-gtools
    - r-optparse
    - r-readr
    - r-rlang
    - r-rmarkdown
    - r-sessioninfo
    - r-stringr
  run:
    - r-base >=4
    - r-assertthat
    - r-details
    - r-dplyr
    - r-dt
    - r-fs
    - r-gtools
    - r-optparse
    - r-readr
    - r-rlang
    - r-rmarkdown
    - r-sessioninfo
    - r-stringr

test:
  commands:
    - $R -e "library('linxreport')"

about:
  home: https://github.com/umccr/linxreport
  license: MIT + file LICENSE
  license_family: MIT
  summary: LINX Result Reporter
