diff --git a/makefile b/makefile
index 503c1c8..b74a1f1 100644
--- a/makefile
+++ b/makefile
@@ -1,30 +1,17 @@
-CC=g++
-
-FLAGS=-O2 -fopenmp
-CFLAGS=-O2 -fopenmp
-
-#FLAGS=-g -fopenmp
-#CFLAGS=-g -fopenmp
-
-#SAMTOOLS_ROOT=/gscuser/kye/software/samtools-0.1.18/
-FLAGS+=-I${SAMTOOLS_ROOT}
-LFLAGS=-lm -L${SAMTOOLS_ROOT} -lbam -lz -lpthread
-SOURCE = cmds scan distribution refseq polyscan param utilities homo window bamreader sample chi somatic
-OBJS= $(patsubst %,%.o,$(SOURCE))
-
-all: check-samtools msisensor
-
-%.o:%.cpp
-	$(CC) $(FLAGS) -c $< -o $@
-
-check-samtools:
-    ifndef SAMTOOLS_ROOT
-        $(error SAMTOOLS_ROOT is undefined)
-    endif
-
-msisensor: $(OBJS)
-	$(CC) $^ $(CFLAGS) $(LFLAGS) -o $@ 
-clean:
-	rm -f *.o msisensor
-
-
+CC=g++
+FLAGS=-O2 -fopenmp
+LFLAGS=-lm -lbam -lz -lpthread
+
+SOURCE = cmds scan distribution refseq polyscan param utilities homo window bamreader sample chi somatic
+OBJS= $(patsubst %,%.o,$(SOURCE))
+
+all: msisensor
+
+%.o:%.cpp
+	$(CC) $(FLAGS) $(CPPFLAGS)  -c $< -o $@
+
+msisensor: $(OBJS)
+	$(CC) $^ $(LIBS) $(FLAGS) $(LFLAGS) -o $@
+
+clean:
+	rm -f *.o msisensor
