diff -rNu arbsrc_17491.orig/Makefile arbsrc_17491/Makefile
--- arbsrc_17491.orig/Makefile	2018-10-17 04:22:41.000000000 -0600
+++ arbsrc_17491/Makefile	2019-02-13 22:22:45.585597907 -0700
@@ -759,9 +759,9 @@
 #---------------------- system dependent commands
 
 ifeq ($(DARWIN),1)
- TIME:=gtime
+ TIME:=time
 else
- TIME:=/usr/bin/time
+ TIME:=time
 endif
 
 #---------------------- SSE vectorizer
