{% set name = "strdust" %}
{% set version = "0.19.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/wdecoster/STRdust/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7b020b7f79279bd79af5f806b6efa9ef082a543acb6995017a674878d5d16b0e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - clangdev <22 
    - make
    - cmake
    - autoconf
    - automake
    - libtool
    - pkg-config
    - cargo-bundle-licenses
  host:
    - zlib
    - htslib

test:
  commands:
    - STRdust --help

about:
  home: "https://github.com/wdecoster/STRdust"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Tandem repeat genotyper for long reads."
  dev_url: "https://github.com/wdecoster/STRdust"
  doc_url: "https://github.com/wdecoster/STRdust/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - osx-arm64
    - linux-aarch64
  identifiers:
    - doi:10.1101/gr.279265.124
  skip-lints:
    - compiler_needs_stdlib_c
