{% set version = "0.0.1" %}

package:
  name: peekseq
  version: {{ version }}

source:
  url: https://github.com/BirolLab/peekseq/releases/download/v{{ version }}/peekseq-{{ version }}.tar.gz
  sha256: 7e3b66f3844dd8fec86db08493cf5b2e8e4ed3e60910fe31c485aed9f81757ad

build:
  noarch: generic
  number: 1
  run_exports: 
    - {{ pin_subpackage("peekseq", max_pin="x") }}

requirements:
  run:
    - perl

test:
  commands:
    - peekseq.pl |grep -A4 "Usage"

about:
  summary: De novo protein-coding potential calculator using a k-mer approach
  home: https://github.com/BirolLab/peekseq
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://github.com/BirolLab/peekseq

