{% set version = "0.1.1" %}
{% set github = "https://github.com/acidgenomics/py-syntactic" %}

package:
  name: syntactic
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/a/acidgenomics-syntactic/acidgenomics_syntactic-{{ version }}.tar.gz"
  sha256: fed1ac2fe4bf1f2b73147799aba8ef6ca81462fc6160f01e01ad3ea42e3fcd35

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
  run_exports:
    - {{ pin_subpackage('syntactic', max_pin="x.x") }}

requirements:
  host:
    - python >=3.12
    - pip
    - uv-build >=0.11,<1
  run:
    - python >=3.12

test:
  imports:
    - syntactic

about:
  home: https://python.acidgenomics.com/syntactic/
  dev_url: "{{ github }}"
  license: Apache-2.0
  license_file: LICENSE
  summary: Make syntactically valid names out of strings.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
