{% set name = "CIRI-AS" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://sourceforge.net/projects/ciri/files/CIRI-AS/CIRI_AS_v{{ version }}.pl/download
    sha256: c8d8ab3f436198ed7c74382d5a48a2317ac5dcdde0762cc96dcb06948f0cc15d



build:
  number: 1
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  host:
    - perl >=5.12

  run:
    - perl >=5.12
    - bwa

test:
  commands:
    - CIRI_AS.pl -H 2>&1 | grep -q "CIRI-AS"

about:
  home: "https://github.com/bioinfo-biols/CIRI-cookbook"
  summary: "CIRI-AS is a detection tool for circRNA internal components and alternative splicing events."
  license: GPL-2.0-only
  license_url: https://sourceforge.net/projects/ciri/files/CIRI-AS/LICENSE.txt/download
  dev_url: "https://github.com/bioinfo-biols/CIRI-cookbook/blob/master/source/CIRI-AS.md"
  doc_url: "https://ciri-cookbook.readthedocs.io/en/latest/CIRI-AS.html"

extra:
  recipe-maintainers:
    - razmia02