--- gffcompare-0.12.6/Makefile	2021-07-23 16:23:13.000000000 +0200
+++ gffcompare-0.12.6-new/Makefile	2022-12-12 13:58:32.047285380 +0100
@@ -5,7 +5,6 @@
 BASEFLAGS  = -Wall -Wextra -std=c++11 ${INCDIRS} -D_REENTRANT -fno-exceptions -fno-rtti
 
 CXX   := $(if $(CXX),$(CXX),g++)
-LINKER  := $(if $(LINKER),$(LINKER),g++)
 
 GCCV8 := $(shell expr `${CXX} -dumpversion | cut -f1 -d.` \>= 8)
 ifeq "$(GCCV8)" "1"
