diff -ruN gffcompare-0.11.2/Makefile gffcompare-0.11.2-new/Makefile
--- gffcompare-0.11.2/Makefile	2019-04-06 00:45:00.000000000 +0200
+++ gffcompare-0.11.2-new/Makefile	2019-04-15 09:54:07.863839042 +0200
@@ -50,8 +50,6 @@
 
 # C/C++ linker
 
-LINKER    := g++
-
 OBJS = ${GCLIB}/GFastaIndex.o ${GCLIB}/GFaSeqGet.o ${GCLIB}/gff.o \
  ${GCLIB}/gdna.o ${GCLIB}/codons.o ${GCLIB}/GBase.o \
  ${GCLIB}/GStr.o ${GCLIB}/GArgs.o
