{% set name = "planemo" %}
{% set version = "0.75.47" %}
{% set sha256 = "5c896c8c53f6e9a386a5095a086985ee1c76b558e64a8bc327dae9bfab873aa8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/planemo-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir --use-pep517 -vvv
  entry_points:
    - planemo = planemo.cli:planemo
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - allure-python-commons
    - backports
    - backports.strenum
    - bioblend >=1.6.0
    - click !=8.0.2
    - cryptography
    - cwltool >=1.0.20191225192155
    - ephemeris >=0.10.3
    - galaxy-job-config-init >=0.1.4
    - galaxy-tool-util >=25.1,<26.2
    - galaxy-tool-util-models >=25.1,<26.1
    - galaxy-util >=24.1,<26.2
    - glob2
    - gxformat2 >=0.25.0
    - h5py
    - jinja2
    - lxml
    - oyaml
    - packaging
    - pathvalidate
    - pydantic >=2
    - pyyaml
    - ruamel.yaml
    - virtualenv
    - stdlib-list  # [py < 310]
    - tabulate

test:
  imports:
    - planemo
    - planemo.commands
    - planemo.database
    - planemo.galaxy
    - planemo.galaxy.test
    - planemo.linters
    - planemo.reports
    - planemo.shed
    - planemo.shed2tap
    - planemo.test
    - planemo.training
    - planemo.xml
  commands:
    - planemo --help

about:
  home: "https://github.com/galaxyproject/planemo"
  summary: "Command-line utilities to assist in building tools for the Galaxy project (https://galaxyproject.org)."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: "https://planemo.readthedocs.io/en/latest"
  dev_url: "https://github.com/galaxyproject/planemo"
