{% set version = "1.0.0" %}

package:
  name: cutesv-trio
  version: {{ version }}

source:
  url: https://github.com/XLeeHIT/cuteSV-Trio/archive/refs/tags/v1.0.0.tar.gz
  sha256: a91f1fca365d24ebfaf7184c223895fc19720047c05220fee852e38435c79680

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --no-cache-dir -vvv .
  run_exports:
    - {{ pin_subpackage("cutesv-trio", max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - biopython
    - cigar
    - numpy
    - pysam >=0.15.0
    - python >=3
    - pyvcf
    - scikit-learn
    - scipy

test:
  commands:
    - cuteSVTrio -h

about:
  home: 'https://github.com/XLeeHIT/cuteSV-Trio'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "cuteSV-Trio: Haplotype-Resolved and De Novo Structural Variant Detection from Low-Coverage Long-Read Family Trios data"
  dev_url: 'https://github.com/XLeeHIT/cuteSV-Trio'

extra:
  recipe-maintainers:
    - XLeeHIT
