      mkdir -p $PREFIX/bin
      ls $PREFIX/bin/
     cp script/ArcSV $PREFIX/bin/
     cp script/BKinCheck.pl $PREFIX/bin/
     cp script/BKinCheck_len.pl $PREFIX/bin/
     cp script/bed2pos $PREFIX/bin/
     cp script/build_env_setup.sh $PREFIX/bin/
     cp script/conda_build.sh $PREFIX/bin/
     cp script/createClip.sh $PREFIX/bin/
     cp script/extractBK_bam.sh $PREFIX/bin/
     cp script/extractSoftclipped $PREFIX/bin/
     cp script/fastqToBKS.pl $PREFIX/bin/
     cp script/filter_PopSpec_AF.sh $PREFIX/bin/
     cp script/find_record.sh $PREFIX/bin/
     cp script/format_header.txt $PREFIX/bin/
     cp script/gen_pop_bed.sh $PREFIX/bin/
     cp script/generateBKSinArc.sh $PREFIX/bin/
     cp script/generateBKSinArc_each.sh $PREFIX/bin/
     cp script/generateBKSinBam.pl $PREFIX/bin/
     cp script/generateBKSinBam.sh $PREFIX/bin/
     cp script/generateBKSinBam_each.sh $PREFIX/bin/
     cp script/getSoftclippedAndNearbySeq.py $PREFIX/bin/
     cp script/getfastq.sh $PREFIX/bin/
     cp script/pos2bed $PREFIX/bin/
     cp script/transDeepMEI2BK.sh $PREFIX/bin/
     chmod +x $PREFIX/bin/*
