{% set name = "locityper" %}
{% set version = "1.4.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/tprodanov/locityper/archive/refs/tags/v{{ version }}.tar.gz
  sha256: db0b5db3ea405afa0f389e2f1a5cdd8f0758434a1619d3cae1cf28afe27868e7
  #patches:
    #- 0001-rust-htslib.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - clangdev
  host:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - htslib =1.19
  run:
    - python
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - samtools >=1.19
    - kmer-jellyfish >=1.0
    - minimap2 >=2.26
    - strobealign >=0.17
    - pysam

test:
  commands:
    - locityper version

about:
  summary: "Targeted genotyper for complex polymorphic loci from short and long read WGS."
  home: "https://github.com/tprodanov/locityper"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://github.com/tprodanov/locityper"
  doc_url: "https://locityper.vercel.app"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
