{% set version = "1.23.1" %}

package:
  name: samtools
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("samtools", max_pin="x") }}

source:
  url: https://github.com/samtools/samtools/releases/download/{{ version }}/samtools-{{ version }}.tar.bz2
  sha256: 32266198a4bc6a6df395d8526688c9697d9c8e472f888c749fdde2e08ea88dd2

requirements:
  build:
    - make
    - {{ compiler('c') }} 
  host:
    - htslib
    - ncurses
    - zlib

about:
  home: https://github.com/samtools/samtools
  license: MIT
  license_file: LICENSE
  summary: Tools for dealing with SAM, BAM and CRAM files

test:
  commands:
    - samtools --help
    # test if https protocol works, if it doesn't samtools will fail with "Protocol not supported"
    - samtools view https://example.com
    - samtools view https://example.com 2>&1 | grep -q 'fail to read the header'

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - biotools:samtools
    - usegalaxy-eu:samtools_flagstat
