{% set name = "demultiplex" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/demultiplex-{{ version }}.tar.gz
  sha256: 905e70a3674aab01c63f6e130ce8b4c9dca54cc0868b932587d4a1045d945990

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
    - hatchling
    - setuptools <82
  run:
    - python >=3.6
    - setuptools <82
    - biopython >=1.72
    - dict-trie >=1.0.1
    - fastools >=1.1.0
    - jit-open >=1.0.1
    - tssv >=1.1.0
    - poetry

test:
  imports:
    - demultiplex
  commands:
    - demultiplex --help

about:
  home: "https://github.com/jfjlaros/demultiplex"
  doc_url: "https://demultiplex.readthedocs.io/en/latest/index.html"
  summary: "Demultiplex any number of FASTA or a FASTQ files based on a list of barcodes."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://github.com/jfjlaros/demultiplex"

extra:
  recipe-maintainers:
    - acaprez
