diff --git a/Makefile b/Makefile2
index 0ffbe01..447f22d 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,4 +1,4 @@
-CXX = g++
+#CXX = g++
 KRAKEN2_SKIP_FOPENMP ?= -fopenmp
 CXXFLAGS = $(KRAKEN2_SKIP_FOPENMP) -Wall -std=c++11 -O3
 CXXFLAGS += -DLINEAR_PROBING
