diff --git a/src/Makefile b/src/Makefile
index e6cb205..5408b0a 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,7 +1,7 @@
-CXX ?= g++
+CXX ?= $(CXX)
 KRAKEN2_SKIP_FOPENMP ?= -fopenmp
-CXXFLAGS = $(KRAKEN2_SKIP_FOPENMP) -Wall -std=c++11 -O3
-CXXFLAGS += -DLINEAR_PROBING
+CXXFLAGS = $(KRAKEN2_SKIP_FOPENMP) -g -Wall -std=c++14 -O3
+CXXFLAGS += -DLINEAR_PROBING $(LDFLAGS)
 
 .PHONY: all clean install
 
