{% set name = "kraken2" %}
{% set version = "2.17.2" %}
{% set sha256 = "84ff95cd6d8a4c9e93ab6bf1d9b3892099baaefb0277bcf2edc3eb4948566035" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DerrickWood/kraken2/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-src-Makefile.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
  host:
    - perl
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - gperftools
    - wget
    - tar
    - rsync
    - zlib
  run:
    - python
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - gperftools
    - blast
    - perl
    - wget
    - tar
    - rsync

test:
  commands:
    - kraken2 --version | grep -F "{{ version }}"
    - kraken2-build --version | grep -F "{{ version }}"
    - kraken2-inspect --version | grep -F "{{ version }}"
    - k2 --version | grep -F "{{ version }}"
    - k2 --help

about:
  home: "https://ccb.jhu.edu/software/kraken2"
  dev_url: "https://github.com/DerrickWood/kraken2"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Kraken2 is a system for assigning taxonomic labels to short DNA sequences, usually obtained through metagenomic studies."
  doc_url: "https://github.com/DerrickWood/kraken2/blob/{{ version }}/docs/MANUAL.markdown"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - biotools:kraken2
    - usegalaxy-eu:kraken2
    - doi:10.1186/gb-2014-15-3-r46
    - doi:10.1186/s13059-019-1891-0
