{% set version = "0.8.6" %}

package:
  name: spatialproteomics
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/spatialproteomics/spatialproteomics-{{ version }}.tar.gz
  sha256: af8bb5bf89ce2b18b59674226403db4852d4392e61ffed67b222658fed8e6214

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage('spatialproteomics', max_pin="x") }}

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0,<81.0
    - wheel
    - pip
  run:
    - python >=3.10
    - cffi >=1.15.0
    - xarray >=2024.0.0
    - scikit-image >=0.25
    - matplotlib-base >=3.8.0
    - tqdm >=4.64.0
    - scikit-learn >=1.4.2
    - zarr
    - numpy >=1.23
    - opencv >=4.11.0
    - pyyaml >=6.0

test:
  imports:
    - spatialproteomics
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/spatialproteomics/
  summary: Spatialproteomics is an interoperable toolbox for analyzing highly multiplexed fluorescence image data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vsuppiyar