{% set version = "5.0.2" %}
{% set beta_suffix = "" %}
{% set sha256 = "5ccb7db55920d65c123789166653de020c674d5604030a6be053e3c08a74c306" %}

package:
  name: hmftools-orange
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/orange-v{{ version }}/orange_v{{ version }}{{ beta_suffix }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('hmftools-orange', max_pin="x") }}

requirements:
  run:
    - zlib
    - openjdk >=8,<=21

test:
  commands:
    - 'orange -version | grep Orange'

about:
  home: https://github.com/hartwigmedical/hmftools/blob/master/orange/README.md
  license:  "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: ORANGE summarizes the key outputs from all algorithms in the Hartwig suite.
