{% set name = "sketchlib" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bacpop/sketchlib.rust/archive/v{{ version }}.tar.gz
  sha256: 45c26f9b6ab1732cfc2f137d89e7d787dff7f4d3a3cbe7fafe4f00092d8df21a

build:
  number: 0
  script: "cargo install --no-track --locked --verbose --root \"${PREFIX}\" --path ."
  run_exports:
    - {{ pin_subpackage("sketchlib", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}

test:
  commands:
    - sketchlib -V

about:
   home: https://github.com/bacpop/sketchlib.rust
   license: Apache-2.0
   license_family: APACHE
   license_file: LICENSE
   summary:  Fast sequence distance estimates

extra:
  additional-platforms:
    - linux-aarch64
