package:
  name: drmutascan
  version: "1.0.0"

source:
  git: https://github.com/luhan125/Drmutascan.git
  git_rev: v1.0.0
  sha256: "a4373f76f8f6a13d2ee71cfa05304aa6bc53457732288fb51164bbaf4696e9c0"   # 请确保使用正确的哈希值

build:
  number: 0             # 1. 修改这里：构建号必须从0开始
  noarch: generic
  run_exports:          # 2. 添加这里：这是 Bioconda 强制要求的
    - {{ pin_subpackage("drmutascan", max_pin="x") }}
  script: |
    mkdir -p $PREFIX/bin
    cp -r $SRC_DIR/scripts/* $PREFIX/bin/
    chmod +x $PREFIX/bin/*.sh

requirements:
  host: []
  run:
    - python >=3.8
    - blast
    - samtools >=1.13
    - bedtools
    - last
    - biopython
    - pandas
    - numpy
    - openjdk

test:
  commands:
    - find_mutation_in_fasta_1.0.sh --help || test $? -eq 1
    - DRMutaScan --help || test $? -eq 1

about:
  home: https://github.com/luhan125/Drmutascan
  license: MIT
  summary: "DRMutaScan - Drug Resistance Mutation Scanner for assembled pathogen genomes"
