{% set name = "chainc" %}
{% set version = "0.0.1" %}

package:
 name: {{ name }}
 version: {{ version }}

source:
 url: https://github.com/hillerlab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
 sha256: c99e383dcfb8d793947c5c03943ff84fc56f96907b1313f06e2f8f4217e72e17

build:
 number: 0

requirements:
  build:
    - {{ compiler("rust") }}
    - cargo-bundle-licenses

test:
 commands:
   - chainc --help
   - chainc --version

about:
 home: "https://github.com/hillerlab/chainc"
 license: "GPL-3.0-only"
 license_family: "GPL"
 license_file:
   - LICENSE
   - THIRDPARTY.yml
 summary: "Remove chain-breaking alignments using chain/net files"
 dev_url: "https://github.com/hillerlab/chainc"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - alejandrogzi
