{% set version = "1.0" %}

package:
  name: proact
  version: {{ version }}

source:
  url: https://github.com/mujiezhang/ProAct/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3e9f93914df2570f6e4a6d95d7fc089553c7194a92689b55b5c24bab264346ff

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - pandas
    - biopython
    - pysam
    - bwa
    - samtools
    - bbmap
    - hmmer
    - prodigal

test:
  commands:
    - proact -h

about:
  home: https://github.com/mujiezhang/ProAct
  summary: "Provirus Activity Detector - Assessing provirus activity based on host sequencing data"
  description: |
    ProAct exploits the principle that a provirus in lysogeny shares the same copy 
    number as its host, resulting in a Provirus-to-Host coverage ratio (PtoH) of 1, 
    whereas transition toward lysis drives self-replication and elevates PtoH above 1.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://github.com/mujiezhang/ProAct#readme
  dev_url: https://github.com/mujiezhang/ProAct

extra:
  recipe-maintainers:
    - mujiezhang
