{% set name = "phylogenize" %}
{% set version = "2.0.0" %}
{% set sha256 = "328a03c661e908ff49b55f98eeaa29540edf83193995ff698db9456a09f42220" %}

package:
  name: phylogenize
  version: {{ version }}

source:
  url: https://github.com/pbradleylab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - r-base>=4.5
    - vsearch
    - r-stringi
    - r-stringr
    - r-tidyverse
    - r-ragg
    - repermulize =1.1.1
    - r-phangorn
    - r-pryr
    - r-svglite
    - r-functional
    - r-settings
    - r-gtools
    - r-furrr
    - r-scales
    - r-phytools
    - r-testthat
    - r-ggiraph
    - r-tidymodels
    - r-extradistr
    - r-plotly
    - r-castor
    - r-ashr
    - r-seqinr
    - r-kableExtra
    - r-phylolm
    - r-pbapply
    - r-purrr
    - r-tibble
    - r-dplyr
    - r-future
    - r-mass
    - r-ape
    - r-phylolm
    - r-dt
    - bioconductor-ggtree
    - bioconductor-biomformat
    - bioconductor-qvalue
    - bioconductor-ancombc =2.12.0
    - bioconductor-clusterprofiler
  run:
    - r-base>=4.5
    - vsearch
    - repermulize =1.1.1
    - r-stringi
    - r-stringr
    - r-tidyverse
    - r-ragg
    - r-phangorn
    - r-pryr
    - r-svglite
    - r-functional
    - r-settings
    - r-gtools
    - r-furrr
    - r-scales
    - r-phytools
    - r-testthat
    - r-ggiraph
    - r-tidymodels
    - r-extradistr
    - r-plotly
    - r-castor
    - r-ashr
    - r-seqinr
    - r-kableExtra
    - r-phylolm
    - r-pbapply
    - r-purrr
    - r-tibble
    - r-dplyr
    - r-future
    - r-mass
    - r-ape
    - r-phylolm
    - r-dt
    - bioconductor-ggtree
    - bioconductor-biomformat
    - bioconductor-qvalue
    - bioconductor-ancombc =2.12.0
    - bioconductor-clusterprofiler

test:
  commands:
    - '$R -e "library(phylogenize)"'

about:
  home: "https://github.com/pbradleylab/phylogenize"
  dev_url: "https://github.com/pbradleylab/phylogenize"
  license: MIT
  license_family: MIT
  summary: "Phylogenize is a tool that allows users to link microbial genes to environments, accounting for phylogeny."
  doc_url: "http://phylogenize.org"

extra:
  recipe-maintainers:
    - kekananen
  indentifiers:
    - doi:10.1093/bioinformatics/btz722
