diff --git a/Makefile b/Makefile
index 4c85808..98fb847 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-CC=gcc
+CC?=gcc
 CFLAGS=-g -Wall -O3 -march=native -flto -Wno-unused-function
 
 all:fastqtk
