diff --git a/Makefile b/Makefile
index 4c85808..61ba554 100644
--- a/Makefile
+++ b/Makefile
@@ -1,10 +1,10 @@
-CC=gcc
+CC?=gcc
 CFLAGS=-g -Wall -O3 -march=native -flto -Wno-unused-function
 
 all:fastqtk
 
 fastqtk:fastqtk.c
-		$(CC) $(CFLAGS) fastqtk.c -o $@ -lz -lm
+		$(CC) $(CFLAGS) fastqtk.c -o $@ -L$(PREFIX)/lib -lz -lm
 
 clean:
 		rm -fr *.o ext/*.o a.out fastqtk *~ *.a *.dSYM session*
