{% set name = "longcallr" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/huangnengCSU/longcallR/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a9dc7355770a9f1adc92a281b1e38504ab0c773700c4e23b05e90172c380bf03
build:
  number: 0
  run_exports:
    - {{ pin_subpackage('longcallr', max_pin="x") }}

requirements:
  build:
    - libtapi         # [osx]
    - {{ compiler('rust') }}
  host:
    - libtapi         # [osx]

test:
  commands:
    - longcallR --help
    - longcallR --version
    - longcallR ase --help
    - longcallR asj --help

about:
  home: https://github.com/huangnengCSU/longcallR
  license: MIT
  summary: "A Rust tool for SNP calling, haplotype phasing, and allele-specific analysis with long RNA-seq reads."

extra:
  recipe-maintainers:
    - huangnengCSU
