package:
  name: mostar
  version: "1.0.0"

source:
  url: https://pypi.io/packages/source/m/mostar/mostar-1.0.0.tar.gz
  sha256: f40666e093c1ecee49b3b03100a6aa350c1c108759221b11eee74418c071d520

build:
  number: 0
  skip: True  # [py<311]
  run_exports:
    - {{ pin_subpackage("mostar", max_pin="x") }}

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools >=61

  run:
    - python >=3.11
    # Core Assembly & Polishing
    - flye
    - medaka
    - filtlong
    - polypolish

    # Pre-processing & Alignment
    - fastp
    - bwa
    - samtools
    - bcftools
    - minimap2
    - circlator

    # Annotation & Profiling
    - bakta
    - ncbi-amrfinderplus
    - blast
    - kraken2

    # ICE & Conjugation Detection
    - macsyfinder

    # Plasticity & Mobile Elements
    - genomad

    # Python libraries
    - matplotlib-base
    - numpy
    - pandas
    - biopython
    - osfclient

    # Utilities
    - wget
    - curl

test:
  commands:
    - mostar --help

about:
  home: https://github.com/nermze/MOSTAR
  license: MIT
  summary: "Modular ONT-Short-read Taxonomic Assembly and Resistome-Evolution pipeline"

extra:
  recipe-maintainers:
    - nermze
