{% set name = "falco" %}
{% set version = "2.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/smithlabcode/falco/releases/download/v{{ version }}/{{ name }}-{{ version }}-Source.tar.gz
  sha256: efa42486923c0ae754d2b4fa1313b6e88dbc65bebde00af828e970a31af362ff

build:
  number: 0
  # requires clang >=22
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - clangdev >=22  # [osx]
  host:
    - zlib
    - htslib
    - isa-l  # [not arm64]
  run:
    - htslib
    - isa-l  # [not arm64]

test:
  commands:
    - falco --help
    - falco --version

about:
  home: "https://github.com/smithlabcode/falco"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "falco is a drop-in C++ implementation of FastQC to assess the quality of sequence reads."
  doc_url: "https://falco.readthedocs.io"
  dev_url: "https://github.com/smithlabcode/falco"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - andrewdavidsmith
    - guilhermesena1
  identifiers:
    - biotools:falco
    - usegalaxy-eu:falco
    - doi:10.12688/f1000research.21142.2
