{% set version = "2.0.1" %}

package:
  name: falco
  version: {{ version }}

source:
  url: https://github.com/smithlabcode/falco/releases/download/v{{ version }}/falco-{{ version }}-Source.tar.gz
  sha256: efa42486923c0ae754d2b4fa1313b6e88dbc65bebde00af828e970a31af362ff

build:
  number: 0
  skip: True
  run_exports:
    - {{ pin_subpackage('falco', max_pin="x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.30
    - make
  host:
    - zlib
    - libdeflate
    - htslib >=1.18
  run:

test:
  commands:
    - falco --help
    - falco --version

about:
  home: "https://github.com/smithlabcode/falco"
  license: "MIT"
  license_family: MIT
  license_file: LICENSE
  summary: "falco is a drop-in C++ implementation of FastQC to assess the quality of sequence reads."
  doc_url: "https://falco.readthedocs.io"
  dev_url: "https://github.com/smithlabcode/falco"

extra:
  additional-platforms:
    - linux-aarch64
  recipe-maintainers:
    - andrewdavidsmith
    - guilhermesena1
  identifiers:
    - biotools:falco
    - usegalaxy-eu:falco
    - doi:10.12688/f1000research.21142.2
