{% set name = "opsin" %}
{% set version = "2.9.0" %}
{% set sha256 = "c2e29326c281f87b59a05d934d8589adac6e9d17b95b984931b3e739111b360f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/dan2097/opsin/releases/download/{{ version }}/{{ name }}-cli-{{ version }}-jar-with-dependencies.jar
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - opsin --help
    - opsin -Xms512m -Xmx1g --help

about:
  home: "https://github.com/dan2097/opsin"
  license: MIT
  license_family: MIT
  license_file: "LICENSE.txt"
  summary: "OPSIN is a Java(8+) library for IUPAC name-to-structure conversion offering high recall and precision on organic chemical nomenclature."
  dev_url: "https://github.com/dan2097/opsin"
  doc_url: "https://www.ebi.ac.uk/opsin"

extra:
  notes: |
    Opsin is a Java program that comes with a custom wrapper shell script.
    This shell wrapper is called "opsin" and is on $PATH by default. By default
    "-Xms512m -Xmx4g" is set in the wrapper. If you want to overwrite it you can
    specify these values directly after your binaries. If you have _JAVA_OPTIONS
    set globally this will take precedence.
    For example run opsin with "opsin -Xms512m -Xmx4g --help"
  identifiers:
    - usegalaxy-eu:ctb_opsin
