diff -ruN CONCOCT-1.0.0_mod/c-concoct/Makefile CONCOCT-1.0.0/c-concoct/Makefile
--- CONCOCT-1.0.0_mod/c-concoct/Makefile	2025-10-09 11:41:03.660939204 +0200
+++ CONCOCT-1.0.0/c-concoct/Makefile	2025-10-09 12:39:09.599931032 +0200
@@ -1,4 +1,3 @@
-CC     = gcc
 CFLAGS = -std=c99 -g -I/usr/local/include/
 EFLAGS =  
 EFILE  = test_vbgmmfit
