{% set name = "conga" %}
{% set version = "1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/asylvz/CONGA/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9535c62a1be8d8936aa5124c840084d83d638a9ac249fabcd1dbcd901252d7c4

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - zlib
    - bzip2
    - xz
    - libcurl
    - htslib
  run:
    - htslib

test:
  commands:
    - conga --version

about:
  home: "https://github.com/asylvz/CONGA"
  summary: "Copy number variation genotyping in ancient genomes and low-coverage sequencing data"
  license: "MIT"
  license_file: "LICENSE"
  doc_url: "https://github.com/asylvz/CONGA"
  dev_url: "https://github.com/asylvz/CONGA"

extra:
  identifiers:
    - doi:10.1371/journal.pcbi.1010788
  recipe-maintainers:
    - asylvz
