{% set name = "perl-archive-tar" %}
{% set version = "3.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Archive-Tar-3.12.tar.gz
  sha256: 0114ef39b65f49f8968283ab47719d7e88f98d7360fe3649be331c7f53d5832c

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('perl-archive-tar', max_pin="x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-pathtools
    - perl-io-compress
    - perl-io-zlib
    - perl-test-harness
    - perl-test-simple
    - perl-module-build
  run:
    - perl
    - perl-pathtools
    - perl-io-compress
    - perl-io-zlib

test:
  # Perl 'use' tests
  imports:
    - Archive::Tar
    - Archive::Tar::Constant
    - Archive::Tar::File

about:
  home: "https://metacpan.org/pod/Archive::Tar"
  license: "Perl_5"
  summary: "Manipulates TAR archives."
  doc_url: "https://metacpan.org/pod/Archive::Tar"
