diff --git a/Makefile b/Makefile
index b660557..8891160 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,6 @@
-CC=			gcc
 CFLAGS=		-g -Wall -O2
 AR=			ar
-DFLAGS=		-DHAVE_PTHREAD
+DFLAGS=		-DHAVE_PTHREAD $(LDFLAGS)
 LOBJS=		utils.o kstring.o ksw.o bwt.o bntseq.o bwa.o bwamem.o bwamem_pair.o
 AOBJS=		QSufSort.o bwt_gen.o bwase.o bwaseqio.o bwtgap.o bwtaln.o bamlite.o \
 			is.o bwtindex.o bwape.o kopen.o pemerge.o \
