{% set name = "diaTracer" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# This URL was generated building of this bioconda package.
# Users must generate their own download URL by agreeing to the terms at https://msfragger.arsci.com/diatracer/LICENSE-ACADEMIC.pdf.
source:
  url: https://msfragger-upgrader.nesvilab.org/diatracer/download.php?token=0000000&download={{ version }}%24zip
  sha256: 1ba66e78674d1d8ff2ec8dee551b9da43844515fc314916ccaf7a1a0f5170b8a

build:
  skip: True # [not linux64]
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - python =3.11
    - unzip
  run:
    - openjdk >=11
    - msfragger >=4.4

test:
  commands:
    - which diatracer

about:
  home: https://diatracer.nesvilab.org/
  license: Academic License
  summary: A diaPASEF spectrum-centric analysis tool
  license_file:
    - licenses/LICENSE-ACADEMIC.pdf
  description: |
    diaTracer is a computational tool that enables spectrum-centric analysis of Bruker’s diaPASEF data-independent acquisition proteomics data,
    facilitating direct (“spectral-library free”) peptide identification and quantification

    diaTracer is available freely for academic research and educational purposes only, in accordance with the terms at https://msfragger.arsci.com/diatracer/LICENSE-ACADEMIC.pdf.

extra:
  recipe-maintainers:
    - reid-wagner
  notes: |
    The "diatracer" command runs the diaTracer java program.
  identifiers:
    - doi:10.1038/s41467-024-55448-8
  skip-lints:
    - should_be_noarch_generic
