{% set version = "0.1.1" %}
{% set github = "https://github.com/acidgenomics/py-acidbase" %}

package:
  name: acidbase
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: e90877e4bf582a66b4a00e0ee6e2aa623e13c4196e8ad794eb02316beff8d4db

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
  run_exports:
    - {{ pin_subpackage('acidbase', max_pin="x.x") }}

requirements:
  host:
    - python >=3.12
    - pip
    - uv-build >=0.11,<1
  run:
    - python >=3.12
    - numpy
    - packaging
    - pandas
    - psutil
    - scipy

test:
  imports:
    - acidbase

about:
  home: https://python.acidgenomics.com/acidbase/
  dev_url: "{{ github }}"
  license: Apache-2.0
  license_file: LICENSE
  summary: Base functions for Acid Genomics packages.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
