{% set version = "0.1.0" %}

package:
  name: readzor
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/readzor/readzor-{{ version }}.tar.gz
  sha256: 154ef92397de318f49cb4cfc884fb623c6319484d3110ec0fce5e196110e0fa4

build:
  entry_points:
    - readzor = readzor.readzor:main
    - Readzor = readzor.readzor:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=77.0.3
    - pip
  run:
    - python
    - numpy ==2.5.2
    - isal ==1.8.0

test:
  imports:
    - readzor
  commands:
    - pip check
    - readzor --help
    - Readzor --help
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/Readzor/
  summary: A Python3 program for fully automatic trimming and quality control of short read sequences.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - abjanssen
