{% set version = "0.1.1" %}

package:
  name: biofastq-a
  version: {{ version }}

source:
  url: https://github.com/DilaDeniz/BioFastq-a/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 433c8fc8ca37e720c9489c6a74389a902ae3d66fa71de040cb11360e0c2345f9

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('biofastq-a', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}

test:
  commands:
    - biofastq-a --version

about:
  home: https://github.com/DilaDeniz/BioFastq-a
  license: MIT
  license_file: LICENSE
  summary: High-performance FASTQ/FASTA quality analysis tool written in Rust

extra:
  recipe-maintainers:
    - DilaDeniz
