#!/bin/bash

# Wrapper script for command-line FragPipe. Enforces that user agrees to academic license.

license_agreement_text='
Please accept the academic license.

MSFragger is available freely for academic research and educational purposes only.

By passing the --accept_license argument, you verify that you have read the ACADEMIC license for MSFragger software:

    http://msfragger-upgrader.nesvilab.org/upgrader/MSFragger-LICENSE.pdf

This license provides with non-exclusive, non-transferable right to use MSFragger solely for academic research, non-commercial or educational purposes. I agree to be subject to the terms and conditions of this license. I understand that to use MSFragger for other purposes requires a commercial license from the University of Michigan Office of Tech Transfer.'

license_accepted=False

for arg in "$@"; do
    shift
    if [[ "$arg" == '--accept_license' ]]; then
        license_accepted=True
        continue
    fi
    set -- "$@" "$arg"
done

if [[ $license_accepted == "False" ]]; then
    echo "$license_agreement_text"
    exit 1
fi

sh fragpipe "$@"
