--- Makefile	2018-11-02 13:21:46.000000000 -0500
+++ Makefile.new	2019-03-15 16:39:08.000000000 -0500
@@ -150,7 +150,7 @@
 ${BAM}/libbam.a:
 	cd ${BAM} && make lib
 stringtie: ${BAM}/libbam.a $(OBJS) stringtie.o
-	${LINKER} ${LDFLAGS} -o $@ ${filter-out %.a %.so, $^} ${LIBS}
+	${LINKER} ${LDFLAGS} -o $@ $^
 	@echo
 	${DBG_WARN}

