{% set version = "1.2.0" %}

package:
  name: hapfold
  version: {{ version }}

source:
  url: https://github.com/LuoGroup2023/HapFold/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1447de36ccc75f1b089f707702fba26c16a65bc8a4995dafcaa79b1982d12810
build:
  number: 0
  skip: True # [osx]
  run_exports:
    - {{ pin_subpackage('hapfold', max_pin="x.x") }}
requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - zlib
  run:
    - zlib
test:
  commands:
    - HapFold 2>&1 | grep 'Usage'

about:
  home: https://github.com/LuoGroup2023/HapFold
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Efficient and Accurate Chromosome-Scale Haplotype Reconstruction.'
  dev_url: https://github.com/LuoGroup2023/HapFold
  doc_url: https://github.com/LuoGroup2023/HapFold

