
{% set name = "multi-omics-classification" %}
{% set version = "0.1.7" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/usegalaxy-eu/MultiOmicsClassification/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5047c5e2924bb75929a9486339d204227f70a00d1ab0cc1ea87e1499a16b298d



  

build:
  noarch: python
  number: 0
  script:
    - python -m pip install . --no-deps -vv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python 
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - pandas
    - scikit-learn
    - matplotlib-base
    - seaborn
    - imbalanced-learn
    - lightgbm
    - xgboost
    - pip
    - tabpfn

test:
  imports:
    - multiclasspredict
    
  commands:
    - multiclasspredict --help

about:
  home: https://github.com/usegalaxy-eu/MultiOmicsClassification
  summary: "A Machine Learning Framework for Benchmarking, Feature Selection, and Hyperparameter Optimization of machine learning Models for Multiomics Data in Galaxy"
  license: MIT
 

extra:
  recipe-maintainers:
    - renu-pal
