{% set version = "2.4.0" %}

package:
  name: nemo
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/nemo2/files/Nemo/{{ version }}/Nemo-{{ version }}-src.tgz
  sha256: 4633d1b62186f672dd27761487e984016cdf98354f5cf78fa9e1a462191ef6b9

build:
  number: 0
  # Undefined symbols for architecture x86_64: "vtable for TTQuanti_diallelic_bitstring_no_pleio", referenced from:
  # TProtoQuanti::hatch() in ttquanti.o
  # NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  skip: True  # [osx and x86_64]
  run_exports:
    - {{ pin_subpackage('nemo', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - mpich-mpicxx
    - sed
    - gsl
    - openblas
  run:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - mpich-mpicxx
    - gsl
    - openblas

test:
  commands:
    - nemo | grep "{{ version }}"

about:
  home: "https://nemo2.sourceforge.io"
  summary: "Individual-based forward-time genetics simulation software."
  license: "GPL-2.0-or-later"
  license_family: GPL
  license_file: COPYING
  doc_url: "https://nemo2.sourceforge.io"
  dev_url: "https://sourceforge.net/projects/nemo2"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1093/bioinformatics/btl415
