{% set name = "dupblaster" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fulcrumgenomics/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3c6bb7ec48bc1a8645ac022777cfb8c0cb251016de89a01e716d9cd1b273cd15

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("dupblaster", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - dupblaster --help

about:
  home: https://github.com/fulcrumgenomics/dupblaster
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fast duplicate marking for query-grouped SAM/BAM files, inspired by samblaster and Picard MarkDuplicates
  dev_url: https://github.com/fulcrumgenomics/dupblaster
  doc_url: https://github.com/fulcrumgenomics/dupblaster/blob/main/README.md

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - tfenne
