{% set name = "gecode" %}
{% set version = "6.3.0" %}
{% set sha256hash = "e3b5d9051bbc669ac39344adaa208ccb0b340213f4e03dec12c7bfb96ab8673d" %}

package:
  name: {{name}}
  version: {{ version }}

source:
  url: https://github.com/Gecode/gecode/archive/release-{{ version }}.tar.gz
  sha256: {{ sha256hash }}

build:
  skip: True  # [osx]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin = "x") }}


requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - perl
    - mpfr
    - gmp
  run:
    - mpfr
    - gmp

test:
  commands:
    - fzn-gecode --help >& /dev/null
    - magic-sequence --help >& /dev/null

about:
  home: http://www.gecode.org/
  license: MIT
  license_file: LICENSE
  summary: Generic constraint development environment
extra:
  additional-platforms:
    - linux-aarch64
