{% set version = "2.2.3" %}

package:
  name: pygoslin
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pygoslin/pygoslin-{{ version }}.tar.gz
  sha256: 7c182d5a372f5217cbaa80cd8be5952c4ecd36e63d8ff3c465f851a53fd5928e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage("pygoslin", max_pin="x.x") }}


requirements:
  host:
    - python >=3.5
    - setuptools >=42
    - wheel
    - cython
    - pytest-runner
    - pip
  run:
    - python >=3.5

test:
  imports:
    - pygoslin
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/lifs-tools/pygoslin
  summary: Python implementation for Goslin
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hechth
