diff --git a/Makefile b/Makefile
index ad06b39..8213cbd 100644
--- a/Makefile
+++ b/Makefile
@@ -39,7 +39,7 @@ ARCH_FLAGS=   -msse4.1
 MEM_FLAGS=     -DSAIS=1
 CPPFLAGS=      -DENABLE_PREFETCH -DV17=1 $(MEM_FLAGS) 
 INCLUDES=   -Isrc -Iext/safestringlib/include
-LIBS=          -lpthread -lm -lz -L. -lbwa  -Lext/safestringlib -lsafestring
+LIBS=          -lpthread -lm -lz -L. -lbwa  -Lext/safestringlib -lsafestring $(LDFLAGS) $(CFLAGS)
 OBJS=          src/fastmap.o src/bwtindex.o src/utils.o src/kthread.o \
                        src/kstring.o src/ksw.o src/bntseq.o src/bwamem.o src/profiling.o src/bandedSWA.o \
                        src/FMI_search.o src/read_index_ele.o src/bwamem_pair.o src/kswv.o src/bwa.o \

