--- Source_code_including_submodules/bwa-mem2-2.1/Makefile	2020-10-16 17:24:18.085319255 +0100
+++ Source_code_including_submodules/bwa-mem2-2.1/Makefile	2020-10-16 17:24:26.977342749 +0100
@@ -43,7 +43,7 @@ ARCH_FLAGS=   -msse -msse2 -msse3 -mssse3 -msse4.1
 MEM_FLAGS=	-DSAIS=1
 CPPFLAGS+=	-DENABLE_PREFETCH -DV17=1 -DMATE_SORT=0 $(MEM_FLAGS)
 INCLUDES=   -Isrc -Iext/safestringlib/include
-LIBS=		-lpthread -lm -lz -L. -lbwa -Lext/safestringlib -lsafestring $(STATIC_GCC)
+LIBS+=	    -lpthread -lm -lz -L. -lbwa -Lext/safestringlib -lsafestring $(STATIC_GCC)
 OBJS=		src/fastmap.o src/bwtindex.o src/utils.o src/memcpy_bwamem.o src/kthread.o \
				    src/kstring.o src/ksw.o src/bntseq.o src/bwamem.o src/profiling.o src/bandedSWA.o \
				    src/FMI_search.o src/read_index_ele.o src/bwamem_pair.o src/kswv.o src/bwa.o \
@@ -120,7 +120,10 @@ $(EXE):$(BWA_LIB) $(SAFE_STR_LIB) src/main.o
 $(BWA_LIB):$(OBJS)
	   ar rcs $(BWA_LIB) $(OBJS)

-$(SAFE_STR_LIB):
+correction4intel:
+	  @sed -i -e '/^extern/s/\(errno_t\) memset_s/\1 memset8_s/'  ext/safestringlib/include/safe_mem_lib.h
+
+$(SAFE_STR_LIB): correction4intel
	   cd ext/safestringlib/ && $(MAKE) clean && $(MAKE) CC=$(CC) directories libsafestring.a

 clean:


