--- Makefile	2016-07-04 15:35:17.535363271 +0400
+++ Makefile	2016-07-04 15:35:32.985363666 +0400
@@ -116,7 +116,7 @@
 CCDEPMODE = depmode=gcc3
 CFLAGS = -g -O2
 CPP = /anaconda/envs/_build/bin/gcc -E
-CPPFLAGS = 
+#CPPFLAGS = 
 CXX = /anaconda/envs/_build/bin/g++
 CXXCPP = /anaconda/envs/_build/bin/g++ -E
 CXXDEPMODE = depmode=gcc3
