diff --git a/Makefile b/Makefile
index 4cded91..c9701d0 100644
--- a/Makefile
+++ b/Makefile
@@ -17,9 +17,9 @@ OBJS=		utils.o bwt.o bwtio.o jigsawaln.o bwtgap.o is.o \
 
 
 PROG=		olego olegoindex #bwtsw #jigsawse
-INCLUDES=	-I./cz	
+INCLUDES=	-I./cz	-I$(PREFIX)/include
 
-LIBS=		-lm -lz -lpthread -Lbwt_gen -lbwtgen
+LIBS=		-L$(PREFIX)/lib -lm -lz -lpthread -Lbwt_gen -lbwtgen
 LIBS2=		./cz/czlib.a 
 
 SUBDIRS=	. bwt_gen cz
