{% set version = "0.1.4.2" %}

package:
  name: simplesam
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simplesam/simplesam-{{ version }}.tar.gz
  sha256: e71fc4559dfa0343aee5e82973615273aa01cda8ccf58d904f53d210f3bbaf15

build:
  noarch: python
  number: 0
  script: "python -m pip install . --no-deps --ignore-installed -vv"
  run_exports:
    - {{ pin_subpackage("simplesam", max_pin="x.x") }}

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - python
    - six
    - setuptools  # uses pkg_resources

test:
  imports:
    - simplesam

about:
  home: http://mattshirley.com
  license: MIT
  summary: 'Simple pure Python SAM parser and objects for working with SAM records'
  dev_url: https://github.com/mdshw5/simplesam
  doc_url: http://simplesam.readthedocs.io/en/latest/

extra:
  skip-lints:
    - uses_setuptools
