{% set name = "verifybamid2" %}
{% set version = "2.0.2" %}
{% set sha256 = "bccd0d9c8f0bb80986ab73b22656c82919635453a50420001a0d7376f487820c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Griffan/VerifyBamID/archive/refs/tags/V{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - ninja
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - autoconf
    - automake
    - libtool
    - pkg-config
  host:
    - zlib
    - bzip2
    - htslib
    - xz
    - curl
    - openssl
  run:
    - htslib

test:
  commands:
    - verifybamid2 2>&1 | grep "VerifyBamID2"
    - verifybamid2 -h 2>&1 | grep "VerifyBamID2"

about:
  home: "https://github.com/Griffan/VerifyBamID"
  dev_url: "https://github.com/Griffan/VerifyBamID"
  license: MIT
  license_family: MIT
  summary: "A robust tool for DNA contamination estimation from sequence reads using ancestry-agnostic method."
  doc_url: "https://griffan.github.io/VerifyBamID"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - biotools:verifybamid
    - doi:10.1101/gr.246934.118
