{% set version = "0.1.4" %}

package:
  name: catnip-seq
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/catnip-seq/catnip_seq-{{ version }}.tar.gz
  sha256: 1ebc5da2fb59996246c4ce40bb1281bbd386b82018d5be00b3d8a557c8f2dc16

build:
  entry_points:
    - catnip = catnip.catnip_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >=3.9
    - pysam
    - pandas
    - numpy
    - cd-hit
    - bowtie2
    - samtools

test:
  imports:
    - catnip
  commands:
    - pip check
    - catnip --help
  requires:
    - pip
    - python

about:
  home: https://github.com/CIBIO-BU/catnip
  summary: Explore nucleotide divergence and sequence resolution across user-defined categories.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  skip-lints:
    - missing_run_exports
  recipe-maintainers:
    - camilababo
