{% set version = "0.9.5" %}


package:
  name: "nf-test"
  version: {{ version }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage("nf-test", max_pin="x.x") }}

source:
  url: https://github.com/askimed/nf-test/releases/download/v{{version}}/nf-test-{{version}}.tar.gz
  sha256: b7679eb90cdc9642bfa89e9634db02ce6e699de53ad35ef0e2f4847634fc1641

requirements:
  host:
    - openjdk >=17,<26
    - coreutils
    - curl
  run:
    - openjdk >=17,<26
    - coreutils
    - curl

test:
  commands:
    - nf-test version

about:
  home: 'https://code.askimed.com/nf-test/'
  license: "MIT"
  summary: "nf-test is a simple test framework for Nextflow pipelines."
