{% set name = "oxo-flow-cli" %}
{% set version = "0.4.2" %}
{% set sha256 = "dfabf82e3d7fac5df4712bb92f305b5d05a624ce9b35f3b7befe63b5d1f3085b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Traitome/oxo-flow/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('oxo-flow-cli', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - oxo-flow --help

about:
  home: "https://github.com/Traitome/oxo-flow"
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "CLI for the oxo-flow bioinformatics pipeline engine"
  description: |
    oxo-flow-cli is the command-line interface for oxo-flow, 
    a bioinformatics pipeline engine.
  dev_url: "https://github.com/Traitome/oxo-flow"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - ShixiangWang
