--- Makefile	2025-03-18 09:56:07
+++ Makefile	2025-03-18 09:56:32
@@ -101,7 +101,7 @@
 # includes a C++ header and exposed functions will need to be declared with
 # extern "C".
 %.o: %.c
-	$(CXX) -c $(CFLAGS) $< -o $@
+	$(CC) -c $(CFLAGS) $< -o $@
 
 %.o: %.cc
 	$(CXX) -x c++ -c $(CXXFLAGS) $< -o $@
