{% set version = "0.5.8" %}
{% set github = "https://github.com/acidgenomics/r-acidplyr" %}

package:
  name: r-acidplyr
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 0bb0bef28e3b59564edc06c9d7cfdc987f712f539c0c9c8202c3074f6f8c0084

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('r-acidplyr', max_pin="x.x") }}

requirements:
  host:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.46.0
    - bioconductor-iranges >=2.34.0
    - bioconductor-s4vectors >=0.38.0
    - r-acidgenerics >=0.7.6
    - r-goalie >=0.7.8
  run:
    # Depends:
    - r-base
    # Imports:
    - bioconductor-biocgenerics >=0.46.0
    - bioconductor-iranges >=2.34.0
    - bioconductor-s4vectors >=0.38.0
    - r-acidgenerics >=0.7.6
    - r-goalie >=0.7.8

test:
  commands:
    - $R -e "library('AcidPlyr')"

about:
  home: https://r.acidgenomics.com/packages/acidplyr/
  dev_url: "{{ github }}"
  license: Apache-2.0
  license_file: LICENSE.md
  license_family: APACHE
  summary: A grammar of S4 class data manipulation.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
