{% set name = "falcon2" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cobilab/FALCON2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0acc05478cb4210b147b7dbebdf981a3c992b8dbe7eebf8d0161742b039296d4

build:
  number: 0
  run_exports:
  - {{ pin_subpackage("falcon2", max_pin="x") }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - falcon2 --help

about:
  home: https://github.com/cobilab/FALCON2
  summary: "FALCON2 genomic compression tool"
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LuiisLaranjeira
    - pratas
