{% set name = "hicberg" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/koszullab/hicberg/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 3a283cb3d3cfebeda0295f2031419da10611f8dad4eccc1205f08dc1a74fbfee

build:
  number: 0
  noarch: python
  entry_points:
    - hicberg=hicberg.__main__:cli
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  run_exports:
    - {{ pin_subpackage('hicberg', max_pin="x") }}

requirements:
  host:
    - python >=3.10,<3.11
    - pip          # pour installer
    - setuptools   # pour builder

  run:
    - python >=3.10,<3.11
    - bioframe     # importé dans le code
    - biopython    # importé dans le code
    - bowtie2      # outil utilisé
    - click        # importé dans le code
    - cooler       # importé dans le code
    - hicstuff     # importé dans le code
    - matplotlib-base
    - numpy
    - pandas
    - pysam
    - samtools     # outil utilisé
    - scipy

test:
  imports:
    - hicberg
  commands:
    - hicberg --help

about:
  home: "https://github.com/koszullab/hicberg"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Statistical profiling based tool for contact data (Hi-C, ChIA-PET, Capture-C, etc.) and genomics data reconstruction"
  dev_url: "https://github.com/koszullab/hicberg"

extra:
  maintainers:
    - axelcournac
