{% set name = "SICER2" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tmx1228/SICER2.1.0/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 92dff55eb88d983ebac3c224fb43e280091e52223911278f91c820284f0c0cf9

build:
  number: 0
  skip: True  # [py > 310]
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps --no-cache-dir --use-pep517 -vvv
  run_exports:
    - {{ pin_compatible(name|lower, max_pin="x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - scipy >=1
  run:
    - numpy
    - python
    - scipy >=1

test:
  imports:
    - sicer

about:
  home: "https://github.com/zanglab/SICER2"
  dev_url: "https://github.com/zanglab/SICER2"
  license: MIT
  license_family: MIT
  summary: "Redesigned and improved ChIP-seq broad peak calling tool SICER."

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - mjsteinbaugh
