--- Makefile	2017-01-08 16:41:37.959684475 +0400
+++ Makefile	2017-01-08 16:41:09.128061848 +0400
@@ -16,8 +16,8 @@
 
 $(SAMTOOLS)/libbam.a : $(SAMTOOLS)/$(HTSLIB)/libhts.a
 
-$(SAMTOOLS)/$(HTSLIB)/libhts.a : 
-	cd $(SAMTOOLS) ; ${MAKE} all
+#$(SAMTOOLS)/$(HTSLIB)/libhts.a : 
+#	cd $(SAMTOOLS) ; ${MAKE} all
 
 Transcript.h : utils.h
 
