{% set version = "3.2.1" %}

package:
  name: "python-intervaltree"
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/intervaltree/intervaltree-{{ version }}.tar.gz
  sha256: f3f7e8baeb7dd75b9f7a6d33cf3ec10025984a8e66e3016d537e52130c73cfe2

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage("python-intervaltree", max_pin="x") }}

requirements:
  host:
    - python >=3.5
    - hatchling
    - uv-dynamic-versioning
    - pip
  run:
    - python >=3.5
    - python-sortedcontainers

test:
  imports:
    - intervaltree

about:
  home: "https://github.com/chaimleib/intervaltree"
  dev_url: "https://github.com/chaimleib/intervaltree"
  license: "Apache-2.0"
  license_family: APACHE
  license_file: "LICENSE.txt"
  summary: "Faster than intervaltree_bio; editable interval tree data structure"
  doc_url: "https://github.com/chaimleib/intervaltree/blob/{{ version }}/README.md"
