{% set version = "1.0.3" %}

package:
  name: novae
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/novae/novae-{{ version }}.tar.gz
  sha256: f0a1cf997868391964e8325b820a52b31d394d8be87c22b0f648f38589fe2422

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - hatchling
    - pip
  run:
    - python >=3.11
    - scanpy >=1.9.8
    - lightning >=2.2.1
    - pytorch >=2.2.1
    - pytorch_geometric >=2.5.2
    - huggingface_hub >=0.32.0
    - safetensors >=0.4.3
    - pandas >=2.0.0
    - igraph >=0.11.8
    - fast-array-utils >=1.3.1

test:
  imports:
    - novae
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://mics-lab.github.io/novae/
  summary: Graph-based foundation model for spatial transcriptomics data
  doc_url: https://mics-lab.github.io/novae/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - quentinblampey
