{% set name = "mifaser" %}
{% set version = "1.60" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 24a2db0c5b733d63ae9266857132aee8912e8fe0c8c1e11ae86727f53b386de3

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage("myrecipe", max_pin="x") }}
  entry_points:
    - mifaser=mifaser.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - diamond >=0.9.36
    - sra-tools

test:
  imports:
    - mifaser
    - mifaser.alignment
    - mifaser.annotation
    - mifaser.translate
  commands:
    - mifaser --help

about:
  home: "https://bitbucket.org/bromberglab/mifaser"
  license: NPOSL-3.0
  license_family: OTHER
  license_file:
  summary: "a python package for super-fast and accurate annotation of molecular functionality using read data without prior assembly or gene finding"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - nickp60
