--- makefile	2019-02-01 05:47:49.000000000 -0600
+++ makefile.new	2019-07-27 13:22:41.732819600 -0500
@@ -24,7 +24,7 @@
 all: $(EXEC)
 
 scripts/CARNAC_to_fasta: scripts/CARNAC_to_fasta.cpp
-	$(CC) -o $@ -c $^ $(CFLAGS_SIMPLE)
+	$(CC) -o $@ $^ $(LDFLAGS)
 
 CARNAC-LR: main.o clustering_cliqueness.o preprocessing.o
 	$(CC) -o $@ $^ $(LDFLAGS)
