diff --git a/Makefile b/Makefile
index 065406d..de6ead2 100644
--- a/Makefile
+++ b/Makefile
@@ -1,13 +1,13 @@
 ROPE_PREFIX=./ropebwt2
-HTS_PREFIX=./htslib
+HTS_PREFIX=${PREFIX}/include/htslib
 ABPOA_PREFIX=./abPOA
 RF_PREFIX=./rapidfuzz-cpp
-INTTREE_PREFIX=./interval-tree
+INTTREE_PREFIX=./interval-tree/include/interval-tree
 PARASAIL_PREFIX=./parasail
-LIBDEFLATE_PREFIX=./libdeflate
+LIBDEFLATE_PREFIX=
 CXX=g++
-CXXFLAGS=-std=c++14 -Wall -Wno-comment -Wno-unused-function -Wno-narrowing -g -O0 -I$(ROPE_PREFIX) -I$(RF_PREFIX) -I$(HTS_PREFIX) -I$(ABPOA_PREFIX)/include -I$(PARASAIL_PREFIX) -I$(INTTREE_PREFIX) -fopenmp -Wno-sign-compare -Wno-unused-variable
-LIBS=-L$(HTS_PREFIX) -L$(ABPOA_PREFIX)/lib -L$(LIBDEFLATE_PREFIX) -L$(LIBDEFLATE_PREFIX)/lib -ldeflate -L$(PARASAIL_PREFIX)/build -lparasail -lm -lpthread -lz -lhts -labpoa
+CXXFLAGS=-std=c++14 -Wall -Wno-comment -Wno-unused-function -Wno-narrowing -g -O3 -I${PREFIX}/include -I$(ROPE_PREFIX) -I$(RF_PREFIX) -I$(HTS_PREFIX) -I$(ABPOA_PREFIX)/include -I$(PARASAIL_PREFIX) -I$(INTTREE_PREFIX) -fopenmp -Wno-sign-compare -Wno-unused-variable
+LIBS=-L$(HTS_PREFIX) -L${PREFIX}/lib -ldeflate -L$(PARASAIL_PREFIX)/build -lparasail -lm -lpthread -lz -lhts -labpoa
 BIN=$(ROPE_PREFIX)/mrope.o $(ROPE_PREFIX)/rope.o $(ROPE_PREFIX)/rld0.o $(ROPE_PREFIX)/rle.o
 
 HPP = $(wildcard *.hpp)
