{% set name = "phold" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cbec9c68769045f35b7020ed57d393f73c567dbc650a96c089ef8eca61f606b

build:
  number: 0
  noarch: python
  entry_points:
    - phold = phold:main
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv"      
  run_exports:
    - {{ pin_subpackage('phold', max_pin='x') }}

requirements:
  host:
    - python >=3.8,<4
    - pip
    - setuptools
  run:
    - foldseek ==10.941cd33
    - python >=3.8,<4
    - biopython >=1.76
    - alive-progress >=3.0.1
    - datasets >=2.15
    - requests >=2.25
    - pyarrow >=14.0.0
    - loguru >=0.5.3
    - pyyaml >=6.0
    - polars >=1.0
    - click >=8.0.0
    - sentencepiece >=0.1.99
    - protobuf >=6.0
    - transformers >=4.34
    - pyrodigal-gv >=0.3.1
    - pytorch >=2.1.2
    - numpy >=1.24
    - pycirclize >=0.3.1
    - h5py >=3.5
    - pholdlib >=0.1.2
    - tqdm >=4.35.0

test:
  imports:
    - phold
  commands:
    - phold --help

about:
  home: https://github.com/gbouras13/phold
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Phage annotation using protein structures
  doc_url: https://phold.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - gbouras13
