{% set name = "pyfish" %}
{% set version = "1.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c5b1da5e3c17f722c4b98356d0e9bf8b8725dfbfc1ee2d83344781a21b90096

build:
  number: 0
  noarch: python
  entry_points:
    - pyfish = pyfish.main:run
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - setuptools
    - pip
    - python >=3.8
  run:
    - matplotlib-base >=3.0
    - numpy >=1.14
    - pandas >=1.0
    - python >=3.8
    - scipy >=1.0

test:
  imports:
    - pyfish
  commands:
    - pyfish --help

about:
  home: "https://github.com/ICCB-Cologne/PyFish"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Plotting tool for evolutionary population dynamics. Creates a Fish (Muller) plot."
  dev_url: "https://github.com/ICCB-Cologne/PyFish"

extra:
  recipe-maintainers:
    - tlkaufmann
    - xstreck1
  identifiers:
    - doi:10.1093/bioinformatics/btad102
