{% set name = "comet-ms" %}
{% set version = "2026.01.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/UWPR/Comet/releases/download/v{{ version }}/comet.aarch64.linux.exe # [linux and aarch64]
    sha256: b05f24e22cfed69c6b5f3d7bf0370656fa338b7c96d305dc7c04d75760d14506 # [linux and aarch64]
  - url: https://github.com/UWPR/Comet/releases/download/v{{ version }}/comet.aarch64.macos.exe # [osx and arm64]
    sha256: 5308289f8c1b193c59e12e03cfbf0ff3f7cde836b5e42f3ba785d365ee256abb  # [osx and arm64]
  - url: https://github.com/UWPR/Comet/releases/download/v{{ version }}/comet.linux.exe # [linux64]
    sha256: 14be7759e7bfe9076d75830deba97bce2cc688828be8c32794fd2a53e83e475b # [linux64]
  - url: https://github.com/UWPR/Comet/releases/download/v{{ version }}/comet.macos.exe # [osx and x86_64]
    sha256: cfb9fb0ad25d5bc39353c41066566aa2dd66167e38218c9df78399904e48a2b5  # [osx and x86_64]
  - url: https://github.com/UWPR/Comet/releases/download/v{{ version }}/comet.win64.exe # [win64]
    sha256: f8a16784b7ed160a288237d77012743cf90ec76db14d567798511982afe4dd7b  # [win64]

build:
  number: 0

requirements:
  build: []
  run: []

test:
  commands:
    - comet.exe -p && rm comet.params.new # [not win]
    - comet -p && rm comet.params.new # [not win]
    - comet.exe -p && del comet.params.new  # [win]


about:
  home: https://uwpr.github.io/Comet/
  license: Apache-2.0
  summary: 'Comet is a command line tool that does MS/MS database search.'

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
    - osx-x86_64
    - win-64
  identifiers:
    - doi:10.1007/s13361-015-1179-x
    - doi:10.1002/pmic.201200439
