{% set name = "gxf2bed" %}
{% set version = "0.3.3" %}

package:
  name: gxf2bed
  version: {{ version }}

source:
  url: https://github.com/alejandrogzi/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4cef3e553eb3ad116f7d63921bf934333a017582db29a5a98b78923e56b21e39

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gxf2bed', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - {{ stdlib("c") }}
    - pkg-config
    - cargo-bundle-licenses

test:
  commands:
    - gxf2bed --help
    - gxf2bed --version

about:
  home: https://github.com/alejandrogzi/gxf2bed
  license: MIT
  license_family: MIT
  license_file: 
    - LICENSE
    - THIRDPARTY.yml
  summary: "Fastest GTF/GFF-to-BED converter chilling around"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - alejandrogzi
