{% set name = "mofaflex" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mofaflex/mofaflex-{{ version }}.tar.gz
  sha256: 19cb27a94fffc6d6e5fc64bb0c42680e67d756a796f2c315829896e57c9e9e39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.11
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.11
    - anndata >=0.11
    - array-api-compat
    - dtw-python
    - gpytorch
    - h5py
    - mizani
    - mudata >=0.3.2
    - numpy
    - packaging
    - pandas
    - platformdirs
    - plotnine
    - pyro-ppl
    - scikit-learn
    - scipy >=1.8
    - session-info2
    - statsmodels
    - pytorch
    - tqdm

test:
  imports:
    - mofaflex
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/mofaflex/
  summary: "Versatile factor analysis framework for factor models for omics data"
  doc_url: https://mofaflex.readthedocs.io/
  dev_url: https://github.com/bioFAM/mofaflex
  license: BSD-3-Clause
  license_file: LICENSE
