{% set version = "2.2.2.1" %}

package:
  name: poseidon-trident
  version: {{ version }}

# documentation of preprocessing selectors:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors
source:
  - url: https://github.com/poseidon-framework/poseidon-hs/releases/download/v{{ version }}/trident-conda-linux # [linux]
    sha256: ac7816c4f150f4e0a0dd070177e7e50a6be1e41452e754b0dc211685ba187e12 # [linux]
  - url: https://github.com/poseidon-framework/poseidon-hs/releases/download/v{{ version }}/trident-macOS-X64 # [osx and x86_64]
    sha256: 25c4687d6663c24f5939a62c8e30fb26738a5bb64e24e71f25063284b7533f9f # [osx and x86_64]
  - url: https://github.com/poseidon-framework/poseidon-hs/releases/download/v{{ version }}/trident-macOS-ARM64 # [osx and arm64]
    sha256: 92d32977a978f016066215f28db316bbab7c643309aa9f5df396bf63a87f5008 # [osx and arm64]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('poseidon-trident', max_pin=None) }}

requirements:
  build:
    # Precompiled binaries still link against libgcc
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - zlib
    - gmp
  run:
    - ca-certificates
    - gmp

test:
  commands:
     - trident --version

about:
  home: "https://www.poseidon-adna.org/#"
  license: MIT
  license_family: MIT
  summary: "A tool (trident) to work with modular genotype databases formatted using Poseidon."

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.7554/eLife.98317.1
