--- Makefile
+++ Makefile
@@ -12,8 +12,8 @@
 OPTIMIZE ?= yes
 USEREADLINE ?= yes
 USEBOOST ?= yes
-BOOST_LIBRARY_DIR="\"Enter_your_boost_library_path_here\""
-BOOST_INCLUDE_DIR="\"Enter_your_boost_include_path_here\""
+BOOST_LIBRARY_DIR=${PREFIX}/lib
+BOOST_INCLUDE_DIR=${PREFIX}/include
 MOTHUR_FILES="\"Enter_your_default_path_here\""

