--- Makefile.org	2021-07-16 10:32:49.601483436 +0000
+++ Makefile	2021-07-19 14:38:06.132941601 +0000
@@ -20,21 +20,21 @@
 # GSL_INCLUDE_DIR - location of GSL include files
 # MOTHUR_FILES - The MOTHUR_FILES parameter is optional, but allows you to set a default location for mothur to look for input files it can't find. This is often used for reference files you want to store in one location separate from your data.
 
-INSTALL_DIR ?= "\"Enter_your_mothur_install_path_here\""
+INSTALL_DIR ?= "$(PREFIX)/bin"
 
-OPTIMIZE ?= yes
+OPTIMIZE ?= no
 USEREADLINE ?= yes
-USEBOOST ?= no
-USEHDF5 ?= no
-USEGSL ?= no
+USEBOOST ?= yes
+USEHDF5 ?= yes
+USEGSL ?= yes
 LOGFILE_NAME ?= no
 
-BOOST_LIBRARY_DIR ?= "\"Enter_your_boost_library_path_here\""
-BOOST_INCLUDE_DIR ?= "\"Enter_your_boost_include_path_here\""
-HDF5_LIBRARY_DIR ?= "\"Enter_your_HDF5_library_path_here\""
-HDF5_INCLUDE_DIR ?= "\"Enter_your_HDF5_include_path_here\""
-GSL_LIBRARY_DIR ?= "\"Enter_your_GSL_library_path_here\""
-GSL_INCLUDE_DIR ?= "\"Enter_your_GSL_include_path_here\""
+BOOST_LIBRARY_DIR ?= "$(PREFIX)/lib"
+BOOST_INCLUDE_DIR ?= "$(PREFIX)/include/boost"
+HDF5_LIBRARY_DIR ?= "$(PREFIX)/lib"
+HDF5_INCLUDE_DIR ?= "$(PREFIX)/include/hdf5"
+GSL_LIBRARY_DIR ?= "$(PREFIX)/lib"
+GSL_INCLUDE_DIR ?= "$(PREFIX)/include/gsl"
 MOTHUR_FILES="\"Enter_your_default_path_here\""
 MOTHUR_TOOLS="\"Enter_your_mothur_tools_path_here\""
 VERSION = "\"1.45.2\""
