{% set name = "scatac-fragment-tools" %}
{% set version = "0.1.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scatac_fragment_tools-{{ version }}.tar.gz
  sha256: 60fdd64549e3f718c9588b51ada766dce56598ceb0140cdc908efb24d984e4dc

build:
  number: 0
  skip: True  # [py < 310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  entry_points:
    - scatac_fragment_tools = scatac_fragment_tools.cli.main:main
  run_exports: {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - clangdev
  host:
    - python
    - pip
    - maturin >=1.11,<2
  run:
    - python
    - numpy
    - pybigwig
    - pybigtools >=0.2.4
    - polars >=1.32.0
    - pyarrow
    - numba
    - rich-argparse
    - joblib

test:
  imports:
    - scatac_fragment_tools
  commands:
    - scatac_fragment_tools --help

about:
  home: "https://github.com/aertslab/scatac_fragment_tools"
  summary: "Tools for working with scATAC-seq fragment files."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: "https://aertslab.github.io/scatac_fragment_tools"
  dev_url: "https://github.com/aertslab/scatac_fragment_tools"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - nilchia
  skip-lints:
    - compiler_needs_stdlib_c
