--- src/graphconstructor/CMakeLists.txt	2017-05-18 15:47:50.000000000 -0500
+++ src/graphconstructor/CMakeLists.txt.new	2018-10-25 02:12:19.481052545 -0500
@@ -6,6 +6,10 @@
 	list(APPEND "CMAKE_CXX_FLAGS" "-std=c++0x")
 endif()
 
+SET ( CMAKE_CXX_FLAGS "-std=c++0x" CACHE STRING "compile flags" FORCE)
+SET ( TBB_LIB_DIR ${PREFIX}/lib CACHE STRING "tbb lib dir" FORCE)
+SET ( TBB_INCLUDE_DIR ${PREFIX}/include/ CACHE STRING "tbb include dir" FORCE)
+
 add_executable(twopaco ../common/dnachar.cpp constructor.cpp concurrentbitvector.cpp compressedstring.cpp ../common/streamfastaparser.cpp test.cpp vertexenumerator.cpp ../common/spooky/SpookyV2.cpp common.cpp)
 link_directories(${TBB_LIB_DIR})
 include_directories(${twopaco_SOURCE_DIR} ${TBB_INCLUDE_DIR} "../common") 
@@ -13,4 +17,4 @@
 
 set(CPACK_PACKAGE_VERSION_MAJOR "0")
 set(CPACK_PACKAGE_VERSION_MINOR "9")
-set(CPACK_PACKAGE_VERSION_PATCH "2")
\ No newline at end of file
+set(CPACK_PACKAGE_VERSION_PATCH "2")
--- src/graphdump/CMakeLists.txt	2017-05-18 15:47:50.000000000 -0500
+++ src/graphdump/CMakeLists.txt.new	2018-10-25 02:12:51.652054161 -0500
@@ -6,12 +6,15 @@
 	list(APPEND "CMAKE_CXX_FLAGS" "-std=c++0x")
 endif()
 
+SET ( CMAKE_CXX_FLAGS "-std=c++0x" CACHE STRING "compile flags" FORCE)
+SET ( TBB_LIB_DIR ${PREFIX}/lib CACHE STRING "tbb lib dir" FORCE)
+SET ( TBB_INCLUDE_DIR ${PREFIX}/include/ CACHE STRING "tbb include dir" FORCE)
+
 add_executable(graphdump graphdump.cpp ../common/dnachar.cpp ../common/streamfastaparser.cpp)
 link_directories(${TBB_LIB_DIR})
 include_directories(${twopaco_SOURCE_DIR} ${TBB_INCLUDE_DIR} "../common")
 target_link_libraries(graphdump  "tbb")
 
-
 set(CPACK_PACKAGE_VERSION_MAJOR "0")
 set(CPACK_PACKAGE_VERSION_MINOR "9")
-set(CPACK_PACKAGE_VERSION_PATCH "2")
\ No newline at end of file
+set(CPACK_PACKAGE_VERSION_PATCH "2")
