--- src/graphconstructor/CMakeLists.txt
+++ src/graphconstructor/CMakeLists.txt
@@ -5,3 +5 @@
-if(CMAKE_COMPILER_IS_GNUCXX)
-	list(APPEND "CMAKE_CXX_FLAGS" "-std=c++11 -lstdc++")
-endif()
+set(CMAKE_CXX_STANDARD 11)
--- src/graphdump/CMakeLists.txt
+++ src/graphdump/CMakeLists.txt
@@ -5,3 +5 @@
-if(CMAKE_COMPILER_IS_GNUCXX)
-	list(APPEND "CMAKE_CXX_FLAGS" "-std=c++11 -lstdc++")
-endif()
+set(CMAKE_CXX_STANDARD 11)
