#!/bin/bash -e
export OLD_LIBTORCH=${LIBTORCH}
export OLD_LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
export OLD_DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}

export LIBTORCH=${CONDA_PREFIX}/libtorch
export LD_LIBRARY_PATH=${LIBTORCH}/lib:${LD_LIBRARY_PATH}
export DYLD_LIBRARY_PATH=${LIBTORCH}/lib:${DYLD_LIBRARY_PATH}
