#!/bin/bash -e
export OLD_LIBTORCH=${LIBTORCH}
export OLD_LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
export OLD_DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}
export OLD_LIBTORCH_CXX11_ABI=${LIBTORCH_CXX11_ABI}
export OLD_RPATH=${RPATH}

export LIBTORCH=${CONDA_PREFIX}/share/libtorch
export LD_LIBRARY_PATH=${LIBTORCH}/lib:${LD_LIBRARY_PATH}
export RPATH=${LIBTORCH}/lib:${RPATH}
export DYLD_LIBRARY_PATH=${LD_LIBRARY_PATH}
export LIBTORCH_CXX11_ABI=0
