#!/bin/bash -e
export OLD_LIBTORCH=${LIBTORCH}
export OLD_LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
export OLD_DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}
export OLD_LIBTORCH_CXX11_ABI=${LIBTORCH_CXX11_ABI}

ls ${CONDA_PREFIX}

export LIBTORCH=${CONDA_PREFIX}/libtorch
export LD_LIBRARY_PATH=${LIBTORCH}/lib:${CONDA_PREFIX}/x86_64-conda-linux-gnu/lib/:${CONDA_PREFIX}/lib/:${LD_LIBRARY_PATH}
export DYLD_LIBRARY_PATH=${LD_LIBRARY_PATH}
export LIBTORCH_CXX11_ABI=0
