#!/bin/bash -e
export LIBTORCH=${OLD_LIBTORCH}
export LD_LIBRARY_PATH=${OLD_LD_LIBRARY_PATH}
export DYLD_LIBRARY_PATH=${OLD_DYLD_LIBRARY_PATH}
export LIBTORCH_CXX11_ABI=${OLD_LIBTORCH_CXX11_ABI}
export RPATH=${OLD_RPATH}
