{% set name = "transsplice" %}
{% set version = "0.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ARU-life-sciences/transsplice/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2bd26977373b2de8a0c995733fb6078f1aaaa8c4d3157f5ffaae942ab56d60a8

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - transsplice --help

about:
  home: https://github.com/ARU-life-sciences/transsplice
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Reconstruct trans-spliced plant organellar genes from scattered exon hits
  dev_url: https://github.com/ARU-life-sciences/transsplice

extra:
  recipe-maintainers:
    - Euphrasiologist
  additional-platforms:
    - linux-aarch64
    - osx-arm64
