{% set version = "0.3.2" %}

package:
  name: skani
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('skani', max_pin="x") }}

source:
  url: https://github.com/bluenote-1577/skani/archive/v{{ version }}.tar.gz
  sha256: 04f3c93b1816d5612cdcc3aae38b6f5bf91709c33743c631a2b4691fc0affe1c

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - make

test:
  commands:
    - skani --help

about:
  home: https://github.com/bluenote-1577/skani
  license: MIT
  summary: skani is a fast and robust tool for calculating ANI between metagenome assembled genomes and contigs. 
    
extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  skip-lints:
    - compiler_needs_stdlib_c
