{% set name = "simpleaf" %}
{% set version = "0.23.2" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("simpleaf", max_pin="x.x") }}

source:
  url: https://github.com/COMBINE-lab/simpleaf/archive/v{{ version }}.tar.gz
  sha256: 6f3311467d143afb5c0aa3a2e4b70c17fcd65253a468a1dcf78e8ea3e4538c19

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - make
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
  run:
    - alevin-fry >=0.13.0
    - piscem >=0.18.0

test:
  commands:
    - simpleaf --help || test $? -eq 1

about:
  home: "https://github.com/COMBINE-lab/simpleaf"
  license: "BSD-3-Clause"
  license_family: BSD
  license_file: LICENSE
  summary: "A rust framework to make using alevin-fry even simpler."
  dev_url: "https://github.com/COMBINE-lab/simpleaf"
  doc_url: "https://simpleaf.readthedocs.io/en/latest"

extra:
  additional-platforms:
    - osx-arm64
    - linux-aarch64
