--- configure.sh	2015-04-24 13:42:52.000000000 -0500
+++ configure.sh.new	2018-10-27 01:32:32.519958842 -0500
@@ -168,11 +168,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -shared
 CFLAGS_COMPILE    := -O3 -fPIC -pthread -D_REENTRANT -Wall -Wno-char-subscripts -mtune=native -march=native -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CLDFLAGS          := -L/usr/local/lib
+CLDFLAGS          := -L${PREFIX}/lib
 CLIBS             := -pthread -lthr
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -O3 -fPIC -pthread -D_REENTRANT -Wall -Wno-char-subscripts -mtune=native -march=native -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CXXLDFLAGS        := -L/usr/local/lib
+CXXLDFLAGS        := -L${PREFIX}/lib
 CXXLIBS           := -pthread -lthr
 ARFLAGS           := ruvs
 INSTALL/          := $target/
@@ -186,11 +186,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -shared
 CFLAGS_COMPILE    := -g -pthread -D_REENTRANT -fPIC -Wall -Wno-char-subscripts -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs  
-CLDFLAGS          := -L/usr/local/lib
+CLDFLAGS          := -L${PREFIX}/lib
 CLIBS             := -pthread -lthr
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -g -pthread -D_REENTRANT -fPIC -Wall -Wno-char-subscripts -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion
-CXXLDFLAGS        := -L/usr/local/lib
+CXXLDFLAGS        := -L${PREFIX}/lib
 CXXLIBS           := -pthread -lthr
 ARFLAGS           := ruvs
 INSTALL/          := $target/
@@ -204,11 +204,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -shared
 CFLAGS_COMPILE    := -pg -O3 -pthread -D_REENTRANT -fPIC -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions
-CLDFLAGS          := -pg -L/usr/local/lib
+CLDFLAGS          := -pg -L${PREFIX}/lib
 CLIBS             := -pthread -lthr
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -pg -O3 -pthread -D_REENTRANT -fPIC -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions
-CXXLDFLAGS        := -pg -L/usr/local/lib
+CXXLDFLAGS        := -pg -L${PREFIX}/lib
 CXXLIBS           := -pthread -lthr
 ARFLAGS           := ruvs
 INSTALL/          := $target/
@@ -222,11 +222,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -shared
 CFLAGS_COMPILE    := -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CLDFLAGS          := -L/usr/local/lib
+CLDFLAGS          := -L${PREFIX}/lib
 CLIBS             := -pthread -ldl
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CXXLDFLAGS        := -L/usr/local/lib
+CXXLDFLAGS        := -L${PREFIX}/lib
 CXXLIBS           := -pthread -ldl
 ARFLAGS           := ruvs
 INSTALL/          := $target/
@@ -240,11 +240,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -shared
 CFLAGS_COMPILE    := -m64 -fPIC -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CLDFLAGS          := -L/usr/local/lib
+CLDFLAGS          := -L${PREFIX}/lib
 CLIBS             := -pthread -ldl
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -m64 -fPIC -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CXXLDFLAGS        := -L/usr/local/lib
+CXXLDFLAGS        := -L${PREFIX}/lib
 CXXLIBS           := -pthread -ldl
 ARFLAGS           := ruvs
 INSTALL/          := $target/
@@ -258,11 +258,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -shared
 CFLAGS_COMPILE    := -m64 -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -g -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CLDFLAGS          := -L/usr/local/lib
+CLDFLAGS          := -L${PREFIX}/lib
 CLIBS             := -pthread -ldl
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -m64 -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -g -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CXXLDFLAGS        := -L/usr/local/lib
+CXXLDFLAGS        := -L${PREFIX}/lib
 CXXLIBS           := -pthread -ldl
 ARFLAGS           := ruvs
 INSTALL/          := $target/
@@ -276,11 +276,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -shared
 CFLAGS_COMPILE    := -pg -m64 -fPIC -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions
-CLDFLAGS          := -L/usr/local/lib
+CLDFLAGS          := -L${PREFIX}/lib
 CLIBS             := -pthread -ldl
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -pg -m64 -fPIC -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions
-CXXLDFLAGS        := -L/usr/local/lib
+CXXLDFLAGS        := -L${PREFIX}/lib
 CXXLIBS           := -pthread -ldl
 ARFLAGS           := ruvs
 INSTALL/          := $target/
@@ -294,11 +294,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -shared
 CFLAGS_COMPILE    := -m64 -fPIC -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CLDFLAGS          := -L/usr/local/lib
+CLDFLAGS          := -L${PREFIX}/lib
 CLIBS             := -pthread -ldl
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -m64 -fPIC -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CXXLDFLAGS        := -L/usr/local/lib
+CXXLDFLAGS        := -L${PREFIX}/lib
 CXXLIBS           := -pthread -ldl
 ARFLAGS           := ruvs
 INSTALL/          := $target/
