--- configure.sh
+++ configure.sh
@@ -129,11 +129,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -dynamiclib -undefined dynamic_lookup
 CFLAGS_COMPILE    := -Ofast -fPIC -m64 -fmessage-length=0 -D_REENTRANT -D_THREAD_SAFE -Wall -Wno-char-subscripts
-CLDFLAGS          := -m64
+CLDFLAGS          := $LDFLAGS -m64
 CLIBS             := 
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -Ofast -fPIC -m64 -fmessage-length=0 -D_REENTRANT -D_THREAD_SAFE -Wall -Wno-char-subscripts
-CXXLDFLAGS        := -m64
+CXXLDFLAGS        := $LDFLAGS -m64
 CXXLIBS           := 
 LDFLAGS_PYTHON    := -bundle -framework CoreFoundation -framework Python -dynamic
 ARFLAGS           := ruvs
@@ -240,11 +240,11 @@
 CC                := $CC
 SHLIB_FLAGS       := -shared
 CFLAGS_COMPILE    := -m64 -fPIC -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CLDFLAGS          := -L/usr/local/lib
+CLDFLAGS          := $LDFLAGS
 CLIBS             := -pthread -ldl
 CXX               := $CXX
 CXXFLAGS_COMPILE  := -m64 -fPIC -D_REENTRANT -O3 -D_THREAD_SAFE -pthread -fmessage-length=0 -Wall -Wno-char-subscripts -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer
-CXXLDFLAGS        := -L/usr/local/lib
+CXXLDFLAGS        := $LDFLAGS
 CXXLIBS           := -pthread -ldl
 ARFLAGS           := ruvs
 INSTALL/          := $target/
