package:
  name: msstitch
  version: "3.20"

source:
  url: https://files.pythonhosted.org/packages/e0/7d/7b10cc91de39d8e0f74de1505e8b50cbb518b3e75004f734c96d430a923e/msstitch-3.20.tar.gz
  sha256: a6914ab4099538d309ec52c85ac1ec76f27178ccfc46eb4dd26ee777de267dd8

build:
  noarch: python
  number: 0
  entry_points:
    - msstitch=app.msstitch:main
  run_exports:
    - {{ pin_subpackage('msstitch', max_pin="x") }}

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy
    - lxml
    - biopython >=1.69
    ## can be removed if the upstream package includes libgcc at some point

test:
  imports:
    - app
    - app.actions
    - app.actions.lookups
    - app.actions.psmtable
    - app.actions.percolator
    - app.dataformats
    - app.drivers
    - app.lookups
    - app.lookups.sqlite
    - app.readers
    - app.writers

  commands:
    - msstitch --help

about:
  home: https://github.com/lehtiolab/msstitch
  license: MIT
  summary: "MS proteomics post processing utilities."
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/lehtiolab/msstitch
