{% set name = "scHicCorr" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schiccorr-{{ version }}.tar.gz
  sha256: 67080e94ed499bb9465311eb6bc607bf77311ea3a0c08094980121dc803807b0

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage("schiccorr", max_pin="x.x.x") }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - schiccorr = schiccorr.main:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
  run:
    - python >=3.10
    - loguru >=0.7
    - cooler >=0.10
    - numba >=0.62
    - numpy >=2.0
    - pandas >=2.0
    - pyarrow >=21.0

test:
  imports:
    - schiccorr
  commands:
    - schiccorr --help

about:
  home: https://github.com/srinzema/scHicCorr
  license: MIT
  license_file: LICENSE
  summary: "Correlate single-cell Hi-C data."

extra:
  recipe-maintainers:
    - srinzema
