{% set name = "grapetree" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d73dcde3a8bd5152065c428a89ca380b7a7d3affeff8dc4310fcfa8bf50733a

build:
  number: 0
  noarch: python
  entry_points:
    - grapetree = grapetree.cli:main
    - MSTrees.py = grapetree.module.MSTrees:main
  script: {{ PYTHON }} -m pip install . -vvv --no-build-isolation --no-cache-dir --no-deps
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python >=3.10
    - hatchling >=1.26
    - pip
  run:
    - python >=3.10
    - ete3
    - flask
    - networkx
    - numpy
    - pandas
    - psutil
    - requests
    - legacy-cgi  # [py >= 313]
    - unidecode
 
test:
  imports:
    - grapetree
  commands:
    - grapetree --help

about:
  home: "https://github.com/achtman-lab/GrapeTree"
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE 
  summary: "Web interface of GrapeTree, which is a program for phylogenetic analysis."
  dev_url: "https://github.com/achtman-lab/GrapeTree"
  doc_url: "https://enterobase.readthedocs.io/en/latest/grapetree/grapetree-about.html"

extra:
  recipe-maintainers:
    - simonhtausch
  identifiers:
    - doi:10.1101/gr.232397.117
