{% set version = "26.04" %}

package:
  name: cryfa
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('cryfa', max_pin="x") }}

source:
  url: https://github.com/cobilab/cryfa/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0940b5376255603b11ac4c5487c3ca40374585ebec8fb30a4136af3125705630

requirements:
  build:
    - make
    - cmake
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}

test:
  commands:
     - cryfa --version 2>&1 | grep {{ version }}

about:
  home: https://github.com/smortezah/cryfa
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL
  summary: A secure encryption tool for genomic data
