diff --git a/makefile b/makefile
index dbb2e86..faddef2 100644
--- a/makefile
+++ b/makefile
@@ -2,7 +2,7 @@
 CC = g++
 OPTCFLAGS = -O2
 CFLAGS = -Wall -std=c++11 $(OPTCFLAGS)
-LDFLAGS = -pthread -lstdc++ -lm
+LDFLAGS = -pthread -lstdc++ -lm -headerpad_max_install_names
 
 # Directory organisation
 BASEDIR = .
