diff --git a/makefile b/makefile
index dbb2e86..6b9e29d 100644
--- a/makefile
+++ b/makefile
@@ -3,6 +3,10 @@ CC = g++
 OPTCFLAGS = -O2
 CFLAGS = -Wall -std=c++11 $(OPTCFLAGS)
 LDFLAGS = -pthread -lstdc++ -lm
+# Add required linker flag for OSX
+ifeq ($(UNAME), Darwin)
+       LDFLAGS += -headerpad_max_install_names
+endif
 
 # Directory organisation
 BASEDIR = .
