export RETICULATE_PYTHON_ENV=${PREFIX}
export BASILISK_CUSTOM_PYTHON_3_11_9="${PREFIX}/bin/python"
export BASILISK_NO_PYENV=1
echo "RETICULATE_PYTHON_ENV has been set to: ${RETICULATE_PYTHON_ENV}"
echo "BASILISK_CUSTOM_PYTHON_3_11_9 has been set to: ${BASILISK_CUSTOM_PYTHON_3_11_9}"
echo "BASILISK_NO_PYENV has been set to: ${BASILISK_NO_PYENV}"