set -x RETICULATE_PYTHON_ENV ${PREFIX}
set -x BASILISK_CUSTOM_PYTHON_X_Y_Z "${PREFIX}/bin/python"
echo "RETICULATE_PYTHON_ENV has been set to: ${RETICULATE_PYTHON_ENV}"
echo "BASILISK_CUSTOM_PYTHON_X_Y_Z has been set to: ${BASILISK_CUSTOM_PYTHON_X_Y_Z}"