--- Makefile	2016-09-15 19:10:13.000000000 +0000
+++ Makefile.new	2019-06-18 19:09:30.018830448 +0000
@@ -5,16 +5,16 @@
 
 
 ripser: ripser.cpp
-	c++ -std=c++11 ripser.cpp -o ripser -Ofast -D NDEBUG
+	$(CXX) -std=c++11 ripser.cpp -o ripser -Ofast -D NDEBUG
 
 ripser-coeff: ripser.cpp
-	c++ -std=c++11 ripser.cpp -o ripser-coeff -Ofast -D NDEBUG -D USE_COEFFICIENTS
+	$(CXX) -std=c++11 ripser.cpp -o ripser-coeff -Ofast -D NDEBUG -D USE_COEFFICIENTS
 
 ripser-reduction: ripser.cpp
-	c++ -std=c++11 ripser.cpp -o ripser-reduction -Ofast -D NDEBUG -D ASSEMBLE_REDUCTION_MATRIX
+	$(CXX) -std=c++11 ripser.cpp -o ripser-reduction -Ofast -D NDEBUG -D ASSEMBLE_REDUCTION_MATRIX
 
 ripser-debug: ripser.cpp
-	c++ -std=c++11 ripser.cpp -o ripser-debug -g
+	$(CXX) -std=c++11 ripser.cpp -o ripser-debug -g
 
 
 clean:
