{% set name = "holodeck" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fg-labs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 397b9b0107bb607ced30745483bd3a6a84221301518c375837cf31cefbb197b0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("holodeck", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - holodeck --help

about:
  home: https://github.com/fg-labs/holodeck
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Modern NGS read simulator
  dev_url: https://github.com/fg-labs/holodeck

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  skip-lints:
    - compiler_needs_stdlib_c  # until https://github.com/bioconda/bioconda-utils/issues/1095 is resolved
  recipe-maintainers:
    - tfenne
