#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "no commands are defined. Please refer to the list of available actions."
    exit 1
fi

SOURCE="${BASH_SOURCE[0]}"
echo "SOURCE:$SOURCE"

while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

JAR=$(find $DIR/.. -name p2m2tools*.jar)

java -cp $JAR $*

