diff --git a/Makefile b/Makefile
index 7151435..fdb936f 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-CC=			gcc
+#CC=			gcc
 #CC=			clang --analyze
 CFLAGS=		-g -Wall -Wno-unused-function -O2
 WRAP_MALLOC=-DUSE_MALLOC_WRAPPERS
