--- Makefile	2016-04-15 14:10:52.000000000 +0200
+++ Makefile.new	2016-05-02 23:58:44.000000000 +0200
@@ -20,7 +20,7 @@
 # define variables for GCC version check here
 GCC_MAJOR_VERSION_GE_4 := $(shell expr `$(GCC) -dumpversion | cut -f1 -d.` \>= 4)
 GCC_MINOR_VERSION_GE_7 := $(shell expr `$(GCC) -dumpversion | cut -f2 -d.` \>= 7)
-GCC_MAC ?= /opt/local/bin/g++-mp-4.8
+GCC_MAC ?= g++


 # CPP_FILES := $(wildcard $(SOURCE)/*/*.cpp) $(wildcard $(SOURCE)/*.cpp) $(wildcard $(SOURCE)/libs/*/*.cpp)
