--- Makefile    2015-11-16 00:52:31.000000000 +0000
+++ Makefile.new        2016-01-29 21:17:56.776587094 +0000
@@ -15,7 +15,7 @@
 # define variables for GCC version check here
 GCC_MAJOR_VERSION_GE_4 := $(shell expr `$(GCC) -dumpversion | cut -f1 -d.` \>= 4)
 GCC_MINOR_VERSION_GE_7 := $(shell expr `$(GCC) -dumpversion | cut -f2 -d.` \>= 7)
-GCC_MAC ?= /opt/local/bin/g++-mp-4.8
+GCC_MAC ?= g++


 CPP_FILES := $(wildcard $(SOURCE)/*/*.cpp) $(wildcard $(SOURCE)/*.cpp)
