{% set name = "perl-sereal" %}
{% set version = "5.009" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-{{ version }}.tar.gz
  sha256: 597e7b00d38dbae2e83ecccbf4636a008ab4b125b3c310ed7ddbe33a01ea3053

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('perl-sereal', max_pin="x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-pathtools
    - perl-scalar-list-utils
    - perl-test-deep 
    - perl-test-differences
    - perl-test-longstring
    - perl-test-simple
    - perl-test-warn
    - perl-sereal-decoder >={{ version }}
    - perl-sereal-encoder >={{ version }}
  run:
    - perl
    - perl-sereal-decoder >={{ version }}
    - perl-sereal-encoder >={{ version }}

test:
  imports:
    - Sereal

about:
  home: "https://metacpan.org/pod/Sereal"
  license: "Perl_5"
  summary: "Fast, compact, powerful binary (de-)serialization."
  doc_url: "https://metacpan.org/pod/Sereal"
