diff --git a/gdc_2/Gdc2/makefile.linux b/gdc_2/Gdc2/makefile.linux
index d613945..1d935ff 100644
--- a/gdc_2/Gdc2/makefile.linux
+++ b/gdc_2/Gdc2/makefile.linux
@@ -2,7 +2,7 @@ all: gdc2
 	
 CC 	= g++
 CFLAGS	= -Wall -O3 -m64 -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -std=c++11 
-CLINK	= -lm -O3 -m64 -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -std=c++11 -lz
+CLINK	= -lm -O3 -m64 -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -std=c++11 -L${PREFIX}/lib -lz
 
 .cpp.o:
 	$(CC) $(CFLAGS) -c $< -o $@
