--- Makefile	2024-08-12 19:59:07.000000000 +0200
+++ Makefile	2024-08-12 19:59:07.000000000 +0200
@@ -46,7 +46,7 @@
 	cd deps/libbdsg-easy && make
 
 hal2vg : hal2vg.o ${basicLibsDependencies}
-	${cpp} ${CXXFLAGS} -fopenmp -pthread hal2vg.o  ${basicLibs}  -o hal2vg
+	${cpp} ${CXXFLAGS} -fopenmp -pthread hal2vg.o  ${basicLibs} -lhdf5 -o hal2vg
 
 clip-vg.o : clip-vg.cpp ${basicLibsDependencies}
 	${cpp} ${CXXFLAGS} -I . clip-vg.cpp -c
