--- Makefile	2018-04-11 15:02:06.000000000 +0200
+++ Makefile.new	2019-07-16 13:58:05.148556861 +0200
@@ -1,7 +1,7 @@
 SRCDIR := src
 BUILDDIR := build
 EXECDIR := bin
-INC := -I include
+INC := -I include -I ${PREFIX}/include
 
 SRCEXT := cpp
 SOURCES := $(wildcard $(SRCDIR)/*.$(SRCEXT))
