diff --git a/Makefile b/Makefile
index 9708d7f..26ecad7 100644
--- a/Makefile
+++ b/Makefile
@@ -1,13 +1,13 @@
 SRCDIR := src
 BUILDDIR := build
 EXECDIR := bin
-INC := -I include
+INC := -I include -I $(PREFIX)/include
 
 SRCEXT := cpp
 SOURCES := $(wildcard $(SRCDIR)/*.$(SRCEXT))
 OBJECTS := $(patsubst %.$(SRCEXT),$(BUILDDIR)/%.o,$(notdir $(SOURCES)))
 
-CXXFLAGS := --std=c++14 -Wall -Ofast 
+CXXFLAGS := --std=c++14 -Wall -Ofast
 LDFLAGS  =
 
 
@@ -20,7 +20,7 @@ TARGET := bin/dinamo
 endif
 
 ifeq ($(BINARY_NAME),dinamo-windows-x64.exe)
-	LDFLAGS = -static -static-libgcc -static-libstdc++ 
+	LDFLAGS = -static -static-libgcc -static-libstdc++
 endif
 
 
