--- Makefile	2019-07-15 17:17:29.019415608 +0200
+++ Makefile.new	2019-07-16 13:35:52.112318352 +0200
@@ -1,7 +1,7 @@
 SRCDIR := src
 BUILDDIR := build
 EXECDIR := bin
-INC := -I ${PREFIX}/include
+INC := -I include -I ${PREFIX}/include
 
 SRCEXT := cpp
 SOURCES := $(wildcard $(SRCDIR)/*.$(SRCEXT))
