diff --git a/gtools/Makefile b/gtools/Makefile
index e0ca80d..8241600 100755
--- a/gtools/Makefile
+++ b/gtools/Makefile
@@ -9,10 +9,10 @@
 BINDIR = ../bin
 CC = g++
 CFLAGS = -g -O2 -Wall $(cflags)
-INCLUDE = -Isamtools
+INCLUDE = -I${PREFIX}/include
 HEADER = gzstream.h core.h genomic_intervals.h 
 OBJ = gzstream.o core.o genomic_intervals.o 
-LIB = -Lsamtools -lbam -lm -lz -lgslcblas -lgsl 
+LIB = -L${PREFIX}/lib -lbam -lm -lz -lgslcblas -lgsl 
 
 
 # Explicit rules
