#!/usr/bin/env bash
set -euo pipefail

cmake -S . -B build -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DSALMON_ENABLE_TESTS=OFF \
  -DSALMON_USE_SYSTEM_DEPS=ON \
  -DSALMON_FETCH_MISSING_DEPS=OFF \
  -DSALMON_BOOST_USE_STATIC_LIBS=OFF \
  -DSALMON_USE_ZLIB_NG=REQUIRED \
  -DSALMON_USE_HTSLIB=REQUIRED \
  -DSALMON_USE_MIMALLOC=AUTO \
  -DSALMON_PUFFERFISH_SOURCE_DIR="${SRC_DIR}/pufferfish" \
  -DSALMON_FQFEEDER_SOURCE_DIR="${SRC_DIR}/FQFeeder" \
  -DFETCHCONTENT_SOURCE_DIR_SALMON_LIBGFF="${SRC_DIR}/libgff"

cmake --build build --parallel "${CPU_COUNT:-4}"
cmake --install build
