{% set name = "salmon" %}
{% set version = "1.11.2" %}
{% set sha256 = "cb99a018f8571b70326caffdc0fee16dc3c527a44f2bdde71884d2465a7a36e5" %}
{% set pufferfish_sha256 = "4ca26b1172b5c9b22340f44ca7555e5551151f2f68e723c2ecd90a8da6df9568" %}
{% set fqfeeder_sha256 = "f962fa55a6f534f91c6f6a761206a56dd4a0b272bcb6d6f9e1b4ca0689abc94d" %}
{% set gff_sha256 = "96d2bda64aaf9cf7b6c1a42205e408b0ef2a353ba42dad560db215e7ec105e2e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/COMBINE-lab/salmon/archive/refs/tags/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://github.com/COMBINE-lab/pufferfish/archive/81b6622d58be80566aa37a5793bd3e48f3463976.tar.gz
    sha256: {{ pufferfish_sha256 }}
    folder: vendor/pufferfish
  - url: https://github.com/rob-p/FQFeeder/archive/f5b08d1002351c192b69048ac9f6cf4c7c116265.tar.gz
    sha256: {{ fqfeeder_sha256 }}
    folder: vendor/FQFeeder
  - url: https://github.com/COMBINE-lab/libgff/archive/refs/tags/v2.0.1.tar.gz
    sha256: {{ gff_sha256 }}
    folder: vendor/libgff
    
build:
  number: 0
  run_exports:
    - {{ pin_subpackage("salmon", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.24
    - ninja
    - make
    - pkg-config
  host:
    - boost-cpp >=1.84
    - tbb >=2021.4
    - htslib >=1.23
    - mimalloc >=3.2.8
    - tbb-devel >=2022.3.0
    - zlib-ng-compat
    - libiconv
    - bzip2
    - xz
    - curl
  run:
    - {{ pin_compatible('htslib') }}
    - {{ pin_compatible('boost-cpp') }}
    - tbb
    - zlib-ng-compat
    - bzip2
    - xz
    - curl
    - boost-cpp
    - icu

test:
  source_files:
    - sample_data.tgz
  commands:
    - salmon --help

about:
  home: "https://github.com/COMBINE-lab/salmon"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Highly-accurate & wicked fast transcript-level quantification from RNA-seq reads using selective alignment."
  dev_url: "https://github.com/COMBINE-lab/salmon"
  doc_url: "https://combine-lab.github.io/salmon"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - rob-p
    - k3yavi
    - mjsteinbaugh
  identifiers:
    - biotools:salmon
    - usegalaxy-eu:salmon
    - usegalaxy-eu:salmonquantmerge
    - usegalaxy-eu:alevin
    - doi:10.1038/nmeth.4197
