{% set version = "1.1.0" %}

package:
  name: ecolityper-chtyper-data
  version: {{ version }}

source:
  url: https://github.com/bbeckley-hub/EcoliTyper/releases/download/v{{ version }}/ecolityper-chtyper-data-v{{ version }}.tar.gz
  sha256: a28f8484d0da5c0d3854c2f5391ce7c5c35093107d0836b33a844cbf6010b47c

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage('ecolityper-chtyper-data', max_pin="x") }}

requirements:
  run:
    - python

test:
  commands:
    - test -f $SP_DIR/ecoliTyper/modules/CHTyper_module/blaster.py

about:
  home: https://github.com/bbeckley-hub/EcoliTyper
  license: MIT
  summary: 'CHTyper database and scripts for ecoliTyper'
