{% set name = "f5c" %}
{% set version = "1.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hasindu2008/f5c/releases/download/v{{ version }}/f5c-v{{ version }}-release.tar.gz
  sha256: 043eeb57733a81c6d27b4a4978909d771e496f5c568f6eb43df99200c02e7200

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - hdf5
    - wget
  run:
    - hdf5

test:
  commands:
    - f5c --help
    - f5c --version

about:
  home: https://github.com/hasindu2008/f5c
  license: MIT
  license_file: LICENSE
  summary: 'An optimised re-implementation of the call-methylation and eventalign modules in Nanopolish.'

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
