diff --git a/Makefile b/Makefile
index 9210241..c66a340 100644
--- a/Makefile
+++ b/Makefile
@@ -53,7 +53,7 @@ endif
 
 DEFINES = -DBUFFERED_FILE_BUFFERSIZE=${BUFFERED_FILE_BUFFERSIZE} -DIM_BUFFERSIZE=${IM_BUFFERSIZE}
 
-CFLAGS	= -g -Wall ${DEFINES} ${DEBUGDEF} ${OPTDEF} -Wno-deprecated -std=gnu++0x -I. -I$(SRC_DIR) -I$(ZLIB_DIR) #-fopenmp
+CFLAGS	= -g -Wall ${DEFINES} ${DEBUGDEF} ${OPTDEF} -Wno-deprecated -std=gnu++0x -I. -I$(SRC_DIR) -I$(PREFIX)/include -I$(ZLIB_DIR) #-fopenmp
 CXXFLAGS= ${CFLAGS}
 LIBS 	=
 
