--- a/tools/Makefile	2022-06-08 14:47:19.000000000 -0600
+++ b/tools/Makefile	2022-06-08 14:49:16.000000000 -0600
@@ -1,18 +1,17 @@
-CC=g++
-CFLAGS=-O3
+CPPFLAGS=-O3
 LDFLAGS=-O3
 
 all: RepeatFinder
 
 RepeatFinder: main.o circularLinkedList.o
-	$(CC) $(LDFLAGS) main.o circularLinkedList.o -o RepeatFinder
+	$(CXX) $(LDFLAGS) main.o circularLinkedList.o -o RepeatFinder
 	strip RepeatFinder
 
 main.o: main.cpp
-	$(CC) $(CFLAGS) -c main.cpp -o main.o
+	$(CXX) $(CPPFLAGS) -c main.cpp -o main.o
 
 circularLinkedList.o: circularLinkedList.cpp circularLinkedList.hpp
-	$(CC) $(CFLAGS) -c circularLinkedList.cpp -o circularLinkedList.o
+	$(CXX) $(CPPFLAGS) -c circularLinkedList.cpp -o circularLinkedList.o
 
 clean:
 	rm -f *.o RepeatFinder
