{% set name = "staphscope" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bbeckley-hub/staphscope-typing-tool/archive/v{{ version }}.tar.gz
  sha256: 0ea49f2678bbb93d3c30a7188dc5543e939997369492d548862e75d4c046a7a4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - staphscope = staphscope.staphscope:main
  run_exports:
    - {{ pin_subpackage('staphscope', max_pin="x") }}

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - pandas >=1.5.0
    - biopython >=1.80
    - psutil >=5.9.0
    - requests >=2.28.0
    - tqdm >=4.64.0
    - click >=8.0.0
    - beautifulsoup4 >=4.11.0
    - lxml >=4.9.0
    - matplotlib-base >=3.5.0
    - seaborn >=0.12.0
    - scipy >=1.10.1
    - plotly >=5.10.0
    - abricate >=1.0.1
    - perl
    - any2fasta
    - blast >=2.13.0
    - perl-moo
    - perl-list-moreutils
    - perl-json
    - perl-lwp-protocol-https
    - perl-path-tiny
    - perl-data-dumper
    - perl-getopt-long
    - perl-file-which

test:
  imports:
    - staphscope
  commands:
    - staphscope --help

about:
  home: https://github.com/bbeckley-hub/staphscope-typing-tool
  license: MIT
  license_file: LICENSE
  summary: 'Advanced Staphylococcus aureus Typing & Lineage Analysis Platform'
  description: |
    StaphScope is a comprehensive bioinformatics tool for Staphylococcus aureus
    genomic analysis including MLST typing, spa typing, SCCmec analysis,
    antimicrobial resistance detection, virulence factors, plasmid profiling,
    and lineage prediction from whole genome sequencing data.
  doc_url: https://github.com/bbeckley-hub/staphscope-typing-tool
  dev_url: https://github.com/bbeckley-hub/staphscope-typing-tool

extra:
  recipe-maintainers:
    - bbeckley-hub
