--- src/rseg/Makefile	2015-08-15 18:33:02.000000000 +0000
+++ src/rseg/Makefile.new	2016-01-25 22:39:34.564813985 +0000
@@ -34,8 +34,10 @@
 
 INCLUDEDIRS = $(SMITHLAB_CPP) $(COMMON_LIB) $(GSL_LIB) $(SAMTOOL_LIB)
 INCLUDEARGS = $(addprefix -I,$(INCLUDEDIRS))
+INCLUDEARGS += $(patsubst %,-I%,$(subst :, ,$(C_INCLUDE_PATH)))
 
 LIBS = -lz -lm
+LIBS += $(patsubst %,-L%,$(subst :, ,$(LIBRARY_PATH)))
 
 CXX = g++
 CC = gcc
