diff --git a/Makefile b/Makefile
index 2b2facf..7ecda8d 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-CC = g++ -std=c++11
+CC = ${CXX} -std=c++11
 CFLAGS  = -Wall -O3 -std=c++11
 LDFLAGS = -lpthread -LBMEAN/spoa/build/lib -lspoa
 
