{% set name = "ThermoRawFileParser" %}
{% set version = "2.0.0" %}
{% set tag = "v.2.0.0-dev" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  run_exports:
    - {{ pin_subpackage('thermorawfileparser', max_pin="x.x.x") }}
  number: 0
  noarch: generic
  script:
    - git clone --depth 1 --branch {{ tag }} https://github.com/CompOmics/ThermoRawFileParser.git main
    - git clone --depth 1 --sparse https://github.com/thermofisherlsms/RawFileReader ThermoPKG
    - cd ThermoPKG
    - git sparse-checkout set --no-cone /Libs/NetCore/Net8/*.nupkg
    - dotnet nuget add source -n ThermoPKG `pwd`/Libs/NetCore/Net8
    - cd ..
    - dotnet publish --configuration Release --framework net8.0 main/ThermoRawFileParser.csproj -o publish
    - mkdir -p $PREFIX/bin
    - cp -r publish/* $PREFIX/bin
    - chmod +x $PREFIX/bin/ThermoRawFileParser
    - ln -s $PREFIX/bin/ThermoRawFileParser $PREFIX/bin/thermorawfileparser
    - rm -rf main
    - rm -rf ThermoPKG

requirements:
  build:
    - git
    - dotnet =8
  run:
    - openssl
    - dotnet-runtime =8
    - dotnet-aspnetcore =8
  
test:
  requires:
    - wget
  commands:
    - ThermoRawFileParser 2>&1 | grep metadata
    - wget https://github.com/CompOmics/ThermoRawFileParser/raw/refs/heads/master/ThermoRawFileParserTest/Data/small.RAW
    - ThermoRawFileParser -i small.RAW

about:
  home: https://github.com/compomics/ThermoRawFileParser
  license: Apache Software
  license_family: APACHE
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A tool allowing reading Thermo RAW files and converting to common open formats
  dev_url: https://github.com/compomics/ThermoRawFileParser
  doc_url: https://github.com/compomics/ThermoRawFileParser/blob/master/README.md

extra:
  recipe-maintainers:
    - RECETOX
    - hechth
