{% set name = "perl-module-load-conditional" %}
{% set version = "0.74" %}
{% set sha256 = "54c354a9393820f1ebc2a095da084ea0392dcbccb0cb38a187a71831cc60a730" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Module-Load-Conditional-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-locale-maketext-simple
    - perl-version
    - perl-module-corelist
    - perl-module-metadata >=1.000005
    - perl-module-load
    - perl-params-check
    - perl-extutils-makemaker
    - perl-test-more
  run:
    - perl
    - perl-version
    - perl-module-corelist
    - perl-module-metadata >=1.000005
    - perl-module-load
    - perl-params-check
    - perl-locale-maketext-simple

test:
  imports:
    - Module::Load::Conditional

about:
  home: "https://metacpan.org/pod/Module::Load::Conditional"
  license: "perl_5"
  summary: "Looking up module information / loading at runtime."
  doc_url: "https://metacpan.org/pod/Module::Load::Conditional"
