diff --git a/Makefile b/Makefile
index bcffebc..7d8382c 100644
--- a/Makefile
+++ b/Makefile
@@ -24,7 +24,6 @@ LD_INC_FLAGS=-I./src/ -I./ -I./src/tinyFA -I./src/tinyFA/pliib -I./$(BUILD_DIR)
 ifneq ($(CONDA_PREFIX),)
 	LD_LIB_FLAGS += -L$(CONDA_PREFIX)/lib/
 	LD_INC_FLAGS += -I$(CONDA_PREFIX)/include
-	PREFIX = $(CONDA_PREFIX)
 endif
 
 gfak: $(BUILD_DIR)/main.o src/gfakluge.hpp src/tinyFA/pliib/pliib.hpp src/tinyFA/tinyFA.hpp | $(BUILD_DIR) $(BIN_DIR)
