--- Makefile	2018-11-19 16:52:26.000000000 +0100
+++ Makefile	2019-09-16 16:17:38.000000000 +0200
@@ -1,7 +1,7 @@
 prefix=$(shell pwd)
 
-BAMTOOLS_INCLUDE_DIR=$(prefix)/bamtools/install/include/bamtools
-BAMTOOLS_LIB_DIR=$(prefix)/bamtools/install/lib/bamtools
+BAMTOOLS_INCLUDE_DIR=${PREFIX}/include/bamtools/
+BAMTOOLS_LIB_DIR=${PREFIX}/lib
 
 all:
 	g++ -std=c++14 -o Blacklist blacklist.cpp -I$(BAMTOOLS_INCLUDE_DIR) -L$(BAMTOOLS_LIB_DIR) -lbamtools -lz -Wl,-rpath,$(BAMTOOLS_LIB_DIR)
