{% set version = "2.10.1" %}
{% set sha256 = "98b30b296f50d320dc5caae23e2aac2c93744a75b8b5b0202f22565115768922" %}

package:
  name: svdb
  version: {{ version }}

source:
  url: https://github.com/J35P312/SVDB/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --no-cache-dir . -vvv
  run_exports:
    - {{ pin_subpackage('svdb', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - setuptools
    - rapidfuzz
  run:
    - python
    - numpy
    - rapidfuzz

test:
  commands:
    - svdb --help

about:
  home: "https://github.com/J35P312/SVDB"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Structural variant database software."
  dev_url: "https://github.com/J35P312/SVDB"
  doc_url: "https://github.com/J35P312/SVDB/blob/{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
