{% set name = "scSTEM" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/s/scSTEM/scSTEM-0.0.2-py3-none-any.whl
  sha256: b021aa0af8364238664e03c756f4e69b7a48a6f5f989354645a26e2cdb344c15

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation scSTEM-0.0.2-py3-none-any.whl
  noarch: python
  run_exports:
    - {{ pin_subpackage("scstem", max_pin="x") }}

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytorch
    - scanpy >=1.8.2
    - tqdm >=4.60.0
    - seaborn >=0.11.1

test:
  imports:
    - STEM

about:
  home: https://github.com/WhirlFirst/STEM
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: A method for mapping single-cell and spatial transcriptomics data with transfer learning

extra:
  recipe-maintainers:
    - askmadsen