{% set name = "aoptk" %}
{% set version = "0.4.0" %}
{% set owner = "rdurnik" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aoptk-{{ version }}.tar.gz
  sha256: 9bc124d7fade5cd804ac190f5453832078e4f71ee082184dbeb468024d310d3b

build:
  entry_points:
    - chemical-identifier = aoptk.application.chemical_identifier:cli
    - publication-tracker = aoptk.application.publication_tracker:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-cache-dir
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0.0
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8
    - pandas
    - pymupdf
    - metapub
    - requests
    - scispacy
    - spacy >=3.0.0,<3.8.0
    - huggingface_hub >=0.1.0,<1.0
    - beautifulsoup4
    - biopython
    - transformers
    - pytorch
    - openpyxl
    - click >=8.1
    - openai
    - spacy-layout

test:
  imports:
    - aoptk
  commands:
    - chemical-identifier --help
    - publication-tracker --help

about:
  summary: "Tools to support data mining for the development of (q)AOPs."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  home: "https://github.com/{{owner}}/aoptk"
  dev_url: "https://github.com/{{owner}}/aoptk"
  doc_url: "https://github.com/{{owner}}/aoptk"

extra:
  recipe-maintainers:
    - hechth
    - rdurnik
