{% set name = "k2tools" %}
{% set version = "v0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fulcrumgenomics/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 24c84a1fb6dd735a85548654106508528f5b42b408cdbc3f8fc6dc4046f49687

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('k2tools', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - k2tools --help

about:
  home: "https://github.com/fulcrumgenomics/{{ name }}"
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "Tools for post-processing kraken2 outputs."
  dev_url: "https://github.com/fulcrumgenomics/{{ name }}"
  doc_url: "https://github.com/fulcrumgenomics/{{ name }}/blob/{{ name }}-v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - nh13
    - tfenne
