--- Makefile
+++ Makefile
@@ -17,5 +17,5 @@
 	mkdir -p bin
-	g++ -I./ $(BOOST_PATH) $(STATIC) $(NOBAMWAR) -Wall -pedantic  -O3  $(ALLCPP)  -o bin/$@ $(VER) $(BOOST_S) $(BOOST_PO) $(BOOST_FS) $(Z) $(M) $(BOOST_TH)  $(PTHREAD) -std=c++0x
+	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(LDFLAGS) -I./ $(BOOST_PATH) $(STATIC) $(NOBAMWAR) -Wall -pedantic  -O3  $(ALLCPP)  -o bin/$@ $(VER) $(BOOST_S) $(BOOST_PO) $(BOOST_FS) $(Z) $(M) $(BOOST_TH)  $(PTHREAD) -std=c++0x
 	@echo "PeakRanger compilation complete."
 %.o : %.cpp
-	g++ -Wall -pedantic $(NOBAMWAR) $(LOG) $(VER) -O3  -c $< -o $@
+	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(LDFLAGS) -Wall -pedantic $(NOBAMWAR) $(LOG) $(VER) -O3  -c $< -o $@
