{% set version = "alpha" %}
{% set name = "himito" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/broadinstitute/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3b49b6c0af5c2c5a1f94d584cf61e1a06f16efad30a8ea3f33e102eb3abdba90

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin=None) }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - clangdev
    - make
    - cmake
    - pkg-config
  host:
    - openssl
    - zlib
    - bzip2
    - xz
    - libcurl
  run:
    - openssl
    - zlib
    - bzip2
    - xz
    - libcurl

test:
  commands:
    - Himito --help

about:
  home: https://github.com/broadinstitute/Himito
  license: MIT
  license_file: LICENSE
  summary: Graph-based toolkit for mitochondrial genome analysis

extra:
  recipe-maintainers:
    - "@fellen31"
