{% set name = "himito" %}
{% set version = "alpha" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/broadinstitute/Himito/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3b49b6c0af5c2c5a1f94d584cf61e1a06f16efad30a8ea3f33e102eb3abdba90

build:
  run_exports:
    - {{ pin_subpackage(name, max_pin=None) }}

  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - make
    - perl
    - cmake
    - clang
    - libclang
  host:
    - openssl
    - zlib
    - bzip2
    - xz
    - curl

test:
  commands:
    - himito --help

about:
  home: https://github.com/broadinstitute/Himito
  summary: 'Mitochondrial variant caller for long reads'
  description: |
    Building Mitochondrial anchor-based graphical genome from long reads. 
    Filter Numts reads, assemble major haplotypes, call homoplasmic and heteroplasmic variants, 
    analyze methylation signals
  license: MIT
  license_file: 
      - "LICENSE"
      - THIRDPARTY.yml
  license_url: https://github.com/broadinstitute/Himito/blob/main/LICENSE
  documentation: https://github.com/broadinstitute/Himito/blob/main/docs/User_guide.md
  repository: https://github.com/broadinstitute/Himito

extra:
  recipe-maintainers:
    - eliottBo
  additional-platforms:
    - linux-aarch64
    - osx-arm64