{% set name = "taxutils" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/SwabSeq/taxutils.git
  git_rev: v{{ version }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=68
    - wheel
  run:
    - python >=3.10
    - numpy
    - pandas

test:
  imports:
    - taxutils
  commands:
    - python -c "from taxutils import taxutils; assert callable(taxutils)"

about:
  home: https://github.com/SwabSeq/taxutils
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Utilities for working with NCBI taxonomic data.
  doc_url: https://pypi.org/project/taxutils/
  dev_url: https://github.com/SwabSeq/taxutils

extra:
  recipe-maintainers:
    - wgobrien
