--- Makefile
+++ Makefile
@@ -43,8 +43,10 @@ PROGS += bam2mr
 endif
 INCLUDEDIRS = $(SMITHLAB_CPP) $(SAMTOOLS_DIR)
 INCLUDEARGS = $(addprefix -I,$(INCLUDEDIRS))
+INCLUDEARGS += $(patsubst %,-I%,$(subst :, ,$(C_INCLUDE_PATH)))
 
 LIBS += -lgsl -lgslcblas -lz
+LIBS += $(patsubst %,-L%,$(subst :, ,$(LIBRARY_PATH)))
 
 CXX = g++ 
 CXXFLAGS = -Wall -fPIC -fmessage-length=50
-- 
1.9.1

