{% set name = "dstar" %}
{% set version = "1.0.1" %}

package:
  name: dstar
  version: {{ version }}

source:
  url: https://github.com/TQ-Smith/DSTAR/archive/refs/tags/DSTARv{{ version }}.tar.gz
  sha256: 13981d5789492190de4af7e05b54ba036bfe9a1e482dd8280dd435bb5c74f3bd

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - zlib

test:
  commands:
    - dstar

about:
  home: https://github.com/TQ-Smith/DSTAR
  summary: D Statistic with Allelic Rarefaction 
  description: |
    D* uses the imbalance of private alleles between pairs of populations
    in a three population tree to locate regions of introgression. D* includes
    multiallelic sites, does not require an outgroup, and performs an implicit
    sample size correction. D* is written in C with no dependencies.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/TQ-Smith/DSTAR/wiki/Manual
  dev_url: https://github.com/TQ-Smith/DSTAR

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - TQ-Smith
  skip-lints:
    - compiler_needs_stdlib_c
