--- Makefile.old	2019-04-27 03:30:11.985568647 -0500
+++ Makefile	2019-04-27 03:53:03.818653203 -0500
@@ -23,7 +23,7 @@
 export MANDIR = ${PREFIX}/bin/man1
 export MODDIR = ${PREFIX}/lib/perl5/site_perl
 
-DIRS = cpp perl
+DIRS = cpp
 install:
 	    @mkdir -p $(BINDIR); mkdir -p $(MODDIR); mkdir -p $(MANDIR); \
 	    cp ${PREFIX}/cpp/vcftools.1 $(MANDIR); \
--- cpp/Makefile.old	2019-04-27 03:30:11.980568647 -0500
+++ cpp/Makefile	2019-04-27 03:30:11.974568646 -0500
@@ -2,9 +2,6 @@
 # Author: Adam Auton
 # ($Revision: 230 $)
 
-# Compiler
-CC = gcc
-CPP = g++
 # Output executable
 EXECUTABLE = vcftools
 # Flag used to turn on compilation of PCA routines
@@ -12,13 +9,13 @@
 	VCFTOOLS_PCA = 0
 endif
 # Compiler flags
-CFLAGS = -O2 -m64
+CFLAGS = -O2 -m64 -I${PREFIX}/include -Wno-narrowing
 #CFLAGS = -Wall -O2 -pg -m64
-CPPFLAGS = -O2 -D_FILE_OFFSET_BITS=64 
+CPPFLAGS = -O2 -D_FILE_OFFSET_BITS=64 -I${PREFIX}/include -Wno-narrowing
 #CPPFLAGS = -O2 -Wall -pg -D_FILE_OFFSET_BITS=64
 # Included libraries (zlib)
-LIB = -lz 
-#LIB = -lz -I/opt/local/include/ -L/opt/local/lib/
+LIB = -L${PREFIX}/lib -lm ${PREFIX}/lib/libz.a
+#LIB = -lz -I${PREFIX}/include/ -L${PREFIX}/lib/
 
 OBJS = vcftools.o bcf_file.o vcf_file.o variant_file.o \
 	header.o bcf_entry.o vcf_entry.o entry.o entry_getters.o entry_setters.o \
@@ -35,7 +32,7 @@
 endif
 
 vcftools: $(OBJS)
-	$(CPP) $(CPPFLAGS) $(OBJS) -o vcftools $(LIB)
+	$(CXX) $(CPPFLAGS) $(OBJS) -o vcftools $(LIB)
 ifdef BINDIR
 	cp $(CURDIR)/$@ $(BINDIR)/$@
 endif
@@ -47,8 +44,8 @@
 -include $(OBJS:.o=.d)
 
 %.o: %.cpp
-	$(CPP) -c $(CPPFLAGS) $*.cpp -o $*.o
-	$(CPP) -MM $(CPPFLAGS) $*.cpp > $*.d
+	$(CXX) -c $(CPPFLAGS) $*.cpp -o $*.o
+	$(CXX) -MM $(CPPFLAGS) $*.cpp > $*.d
 
 # remove compilation products
 clean:
