{% set name = "checkv" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ed675601dafa8c6a10739c86499af7493c50d38bb491c3da87933759c1ef5f4a

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  entry_points:
    - checkv=checkv.cli:cli
    - anicalc=checkv.commands.anicalc:cli
    - aniclust=checkv.commands.aniclust:cli
  run_exports:
    - {{ pin_subpackage("checkv", max_pin="x.x") }}

requirements:
  host:
    - python
    - pip
    - flit-core >=3.10,<4
  run:
    - python
    - biopython
    - importlib-metadata >=0.12
    - numpy >=1.5
    - pyrodigal-gv >=0.3.1
    - psutil
    - requests
    - kcounter
    - click >=8.0
    - loguru >=0.7
    - diamond <=2.1.8
    - hmmer >=3.3

test:
  commands:
    - checkv --help

about:
  home: "https://bitbucket.org/berkeleylab/checkv"
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE
  summary: "Assess the quality of metagenome-assembled viral genomes."

extra:
  identifiers:
    - biotools:checkv
    - doi:10.1038/s41587-020-00774-7
