{% set name = "checkv" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a2c04298109bc23c72ffb7a745fc5f7c9d6503e4753525324bc20085af7441fd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - checkv=checkv.cli:cli
  run_exports:
    - {{ pin_subpackage("checkv", max_pin="x") }}

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=3.6
    - biopython
    - importlib-metadata >=0.12
    - numpy
    - psutil
    - requests
    - kcounter
    - diamond <=2.1.8
    - hmmer
    - prodigal-gv

test:
  commands:
    - checkv --help

about:
  home: "https://bitbucket.org/berkeleylab/checkv"
  license: Modified BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Assess the quality of metagenome-assembled viral genomes."

extra:
  identifiers:
    - biotools:checkv
    - doi:10.1038/s41587-020-00774-7
