export BASILISK_CUSTOM_PYTHON_3_11_9="${CONDA_PREFIX}/bin/python"
export BASILISK_NO_PYENV=1
echo "BASILISK_CUSTOM_PYTHON_3_11_9 has been set to: ${BASILISK_CUSTOM_PYTHON_3_11_9}"
echo "BASILISK_NO_PYENV has been set to: ${BASILISK_NO_PYENV}"