{% set version = "1.11" %}

package:
  name: alcor
  version: {{ version }}

build:
   # Passes some invalid flags for clang
   number: 0
   run_exports:
     - {{ pin_subpackage('alcor', max_pin="x") }}

source:
  url: https://github.com/cobilab/alcor/archive/v{{ version }}.tar.gz
  sha256: 59014b0d07943f25f88047866bfc9265180299c8068121f8f869e81d1793e43f

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - cmake <4
    - pkg-config
  host:
    - zlib

test:
  commands:
    - AlcoR --help # Test that alcor can be run with the --help flag

about:
  home: "https://github.com/cobilab/alcor"
  license: "GPL-3.0-or-later"
  license_file: LICENSE
  license_family: GPL3
  summary: "Software for alignment-free simulation, mapping, and visualization of low-complexity regions in FASTA data."
  dev_url: "https://github.com/cobilab/alcor"
  doc_url: "https://cobilab.github.io/alcor"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
