{% set version = "1.2.0" %}

package:
  name: staphscope-mlst-data
  version: {{ version }}

source:
  url: https://github.com/bbeckley-hub/staphscope-typing-tool/releases/download/v{{ version }}/staphscope-mlst-data-v{{ version }}.tar.gz
  sha256: 8738c00aa778e22c497fc50735a51152da9cac169aa3edfb2635cf49b07f434a

build:
  noarch: generic
  number: 1                
  run_exports:
    - {{ pin_subpackage('staphscope-mlst-data', max_pin="x") }}

test:
  commands:
    - test -f $SP_DIR/staphscope/modules/mlst_module/mlst_module.py

about:
  home: https://github.com/bbeckley-hub/staphscope-typing-tool
  summary: 'MLST typing database for StaphScope'
  license: MIT
