--- sabre-039a55e500ba07b7e6432ea6ec2ddcfb3471d949/Makefile	2013-09-28 01:08:01.000000000 +0100
+++ Makefile	2019-06-25 13:33:59.000000000 +0100
@@ -1,7 +1,6 @@
 PROGRAM_NAME = sabre
 VERSION = 1.00
-CC = gcc
-CFLAGS = -Wall -pedantic -DVERSION=$(VERSION)
+CFLAGS = -Wall -pedantic -DVERSION=$(VERSION) -I$(PREFIX)/include -L$(PREFIX)/lib
 DEBUG = -g
 OPT = -O3
 ARCHIVE = $(PROGRAM_NAME)_$(VERSION)
