--- Makefile.bak	2019-05-16 14:13:15.886972883 +0200
+++ Makefile	2019-05-17 10:06:33.580388551 +0200
@@ -94,11 +94,11 @@
 
 gcc:
 	cd Zoe; make;
-	make $(APP)  CC="gcc" CFLAGS="-O2 -Wall -Werror"
-	make $(APP2) CC="gcc" CFLAGS="-O2 -Wall -Werror"
-	make $(APP3) CC="gcc" CFLAGS="-O2 -Wall -Werror"
-	make $(APP4) CC="gcc" CFLAGS="-O2 -Wall -Werror"
-	make $(APP5) CC="gcc" CFLAGS="-O2 -Wall -Werror"
+	make $(APP)  CC=$(CC) CFLAGS="-O2 -Wall"
+	make $(APP2) CC=$(CC) CFLAGS="-O2"
+	make $(APP3) CC=$(CC) CFLAGS="-O2 -Wall"
+	make $(APP4) CC=$(CC) CFLAGS="-O2 -Wall"
+	make $(APP5) CC=$(CC) CFLAGS="-O2 -Wall"
 
 
 ###################
